---
title: "Multimedia"
---
= Multimedia
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
Ross Lippert

[[_multimedia_synopsis]]
== Synopsis


FreeBSD supports a wide variety of sound cards, allowing users to enjoy high fidelity output from a FreeBSD system.
This includes the ability to record and play back audio in the MPEG Audio Layer 3 ([acronym]``MP3``), Waveform Audio File ([acronym]``WAV``), Ogg Vorbis, and other formats.
The FreeBSD Ports Collection contains many applications for editing recorded audio, adding sound effects, and controlling attached MIDI devices.

FreeBSD also supports the playback of video files and [acronym]``DVD``s.
The FreeBSD Ports Collection contains applications to encode, convert, and playback various video media.

This chapter describes how to configure sound cards, video playback, TV tuner cards, and scanners on FreeBSD.
It also describes some of the applications which are available for using these devices.

After reading this chapter, you will know how to:

* Configure a sound card on FreeBSD.
* Troubleshoot the sound setup.
* Playback and encode MP3s and other audio.
* Prepare a FreeBSD system for video playback.
* Play [acronym]``DVD``s, [path]``.mpg`` , and [path]``.avi`` files.
* Rip [acronym]``CD`` and [acronym]``DVD``	  content into files.
* Configure a TV card.
* Install and setup MythTV on FreeBSD
* Configure an image scanner.
* Configure a Bluetooth headset.


Before reading this chapter, you should:

* Know how to install applications as described in <<_ports>>.


[[_sound_setup]]
== Setting Up the Sound Card
= Setting Up the Sound Card
:imagesdir: ./images
Moses Moore; Marc Fonvieille

(((PCI)))

(((sound cards)))


Before beginning the configuration, determine the model of the sound card and the chip it uses.
FreeBSD supports a wide variety of sound cards.
Check the supported audio devices list of the https://www.FreeBSD.org/releases/12.0R/hardware.html[Hardware
	Notes] to see if the card is supported and which FreeBSD driver it uses.

(((kernel,configuration)))


In order to use the sound device, its device driver must be loaded.
The easiest way is to load a kernel module for the sound card with  {{< manpage "kldload" "8" >}}
.
This example loads the driver for a built-in audio chipset based on the Intel specification:

----
# kldload snd_hda
----


To automate the loading of this driver at boot time, add the driver to [path]``/boot/loader.conf``
.
The line for this driver is:

[source]
----
snd_hda_load="YES"
----


Other available sound modules are listed in [path]``/boot/defaults/loader.conf``
.
When unsure which driver to use, load the [path]``snd_driver``
 module:

----
# kldload snd_driver
----


This is a metadriver which loads all of the most common sound drivers and can be used to speed up the search for the correct driver.
It is also possible to load all sound drivers by adding the metadriver to [path]``/boot/loader.conf``
.

To determine which driver was selected for the sound card after loading the [path]``snd_driver``
 metadriver, type [command]``cat /dev/sndstat``.

=== Configuring a Custom Kernel with Sound Support


This section is for users who prefer to statically compile in support for the sound card in a custom kernel.
For more information about recompiling a kernel, refer to <<_kernelconfig>>.

When using a custom kernel to provide sound support, make sure that the audio framework driver exists in the custom kernel configuration file:

[source]
----
device sound
----


Next, add support for the sound card.
To continue the example of the built-in audio chipset based on the Intel specification from the previous section, use the following line in the custom kernel configuration file:

[source]
----
device snd_hda
----


Be sure to read the manual page of the driver for the device name to use for the driver.

Non-PnP ISA sound cards may require the IRQ and I/O port settings of the card to be added to [path]``/boot/device.hints``
.
During the boot process,  {{< manpage "loader" "8" >}}
 reads this file and passes the settings to the kernel.
For example, an old Creative SoundBlaster(TM)
 16 ISA non-PnP card will use the  {{< manpage "snd_sbc" "4" >}}
 driver in conjunction with ``snd_sb16``.
For this card, the following lines must be added to the kernel configuration file:

[source]
----
device snd_sbc
device snd_sb16
----


If the card uses the `0x220` I/O port and IRQ ``5``, these lines must also be added to [path]``/boot/device.hints``
:

[source]
----
hint.sbc.0.at="isa"
hint.sbc.0.port="0x220"
hint.sbc.0.irq="5"
hint.sbc.0.drq="1"
hint.sbc.0.flags="0x15"
----


The syntax used in [path]``/boot/device.hints``
	is described in  {{< manpage "sound" "4" >}}
 and the manual page for the driver of the sound card.

The settings shown above are the defaults.
In some cases, the IRQ or other settings may need to be changed to match the card.
Refer to  {{< manpage "snd_sbc" "4" >}}
 for more information about this card.

[[_sound_testing]]
=== Testing Sound


After loading the required module or rebooting into the custom kernel, the sound card should be detected.
To confirm, run [command]``dmesg | grep pcm``.
This example is from a system with a built-in Conexant CX20590 chipset:

----
pcm0: <NVIDIA (0x001c) (HDMI/DP 8ch)> at nid 5 on hdaa0
pcm1: <NVIDIA (0x001c) (HDMI/DP 8ch)> at nid 6 on hdaa0
pcm2: <Conexant CX20590 (Analog 2.0+HP/2.0)> at nid 31,25 and 35,27 on hdaa1
----


The status of the sound card may also be checked using this command:

----
# cat /dev/sndstatFreeBSD Audio Driver (newpcm: 64bit 2009061500/amd64)
Installed devices:
pcm0: <NVIDIA (0x001c) (HDMI/DP 8ch)> (play)
pcm1: <NVIDIA (0x001c) (HDMI/DP 8ch)> (play)
pcm2: <Conexant CX20590 (Analog 2.0+HP/2.0)> (play/rec) default
----


The output will vary depending upon the sound card.
If no [path]``pcm``
 devices are listed, double-check that the correct device driver was loaded or compiled into the kernel.
The next section lists some common problems and their solutions.

If all goes well, the sound card should now work in FreeBSD.
If the [acronym]``CD`` or [acronym]``DVD`` drive is properly connected to the sound card, one can insert an audio [acronym]``CD`` in the drive and play it with  {{< manpage "cdcontrol" "1" >}}
:

----
% cdcontrol -f /dev/acd0 play 1
----

[WARNING]
====
Audio [acronym]``CD``s have specialized encodings which means that they should not be mounted using  {{< manpage "mount" "8" >}}
.
====


Various applications, such as [package]#audio/workman#
, provide a friendlier interface.
The [package]#audio/mpg123#
 port can be installed to listen to MP3 audio files.

Another quick way to test the card is to send data to [path]``/dev/dsp``
:

----
% cat filename > /dev/dsp
----


where [path]``filename``
 can be any type of file.
This command should produce some noise, confirming that the sound card is working.

[NOTE]
====
The [path]``/dev/dsp*``
 device nodes will be created automatically as needed.
When not in use, they do not exist and will not appear in the output of  {{< manpage "ls" "1" >}}
.
====

[[_bluetooth_headset]]
=== Setting up Bluetooth Sound Devices


Connecting to a Bluetooth device is out of scope for this chapter.
Refer to <<_network_bluetooth>> for more information.

To get Bluetooth sound sink working with FreeBSD's sound system, users have to install [package]#audio/virtual_oss#
 first:

----
# pkg install virtual_oss
----

[package]#audio/virtual_oss#
 requires `cuse` to be loaded into the kernel:

----
# kldload cuse
----


To load `cuse` during system startup, run this command:

----
# sysrc -f /boot/loader.conf cuse_load=yes
----


To use headphones as a sound sink with [package]#audio/virtual_oss#
, users need to create a virtual device after connecting to a Bluetooth audio device:

----
# virtual_oss -C 2 -c 2 -r 48000 -b 16 -s 768 -R /dev/null -P /dev/bluetooth/headphones -d dsp
----

[NOTE]
====
[replaceable]``headphones`` in this example is a hostname from [path]``/etc/bluetooth/hosts``
. `BT_ADDR` could be used instead.
====


Refer to  {{< manpage "virtual_oss" "8" >}}
 for more information.

[[_troubleshooting]]
=== Troubleshooting Sound

(((device nodes)))

(((I/O port)))

(((IRQ)))

(((DSP)))

<<_multimedia_sound_common_error_messages>>	lists some common error messages and their solutions:

[[_multimedia_sound_common_error_messages]]
.Common Error Messages
[cols="1,1", frame="none", options="header"]
|===
| Error
| Solution

|``sb_dspwr(XX) timed
		  out``
|

The I/O port is not set correctly.

|``bad irq XX``
|

The IRQ is set incorrectly.
Make sure that the set IRQ and the sound IRQ are the same.

|``xxx: gus pcm not attached, out of
		  memory``
|

There is not enough available memory to use the device.

|``xxx: can't open
		  /dev/dsp!``
|

Type [command]``fstat \| grep
		  dsp`` to check if another application is holding the device open.
Noteworthy troublemakers are [app]``esound`` and [app]``KDE``'s sound support.
|===


Modern graphics cards often come with their own sound driver for use with [acronym]``HDMI``.
This sound device is sometimes enumerated before the sound card meaning that the sound card will not be used as the default playback device.
To check if this is the case, run [app]``dmesg`` and look for ``pcm``.
The output looks something like this:

[source]
----
...
hdac0: HDA Driver Revision: 20100226_0142
hdac1: HDA Driver Revision: 20100226_0142
hdac0: HDA Codec #0: NVidia (Unknown)
hdac0: HDA Codec #1: NVidia (Unknown)
hdac0: HDA Codec #2: NVidia (Unknown)
hdac0: HDA Codec #3: NVidia (Unknown)
pcm0: <HDA NVidia (Unknown) PCM #0 DisplayPort> at cad 0 nid 1 on hdac0
pcm1: <HDA NVidia (Unknown) PCM #0 DisplayPort> at cad 1 nid 1 on hdac0
pcm2: <HDA NVidia (Unknown) PCM #0 DisplayPort> at cad 2 nid 1 on hdac0
pcm3: <HDA NVidia (Unknown) PCM #0 DisplayPort> at cad 3 nid 1 on hdac0
hdac1: HDA Codec #2: Realtek ALC889
pcm4: <HDA Realtek ALC889 PCM #0 Analog> at cad 2 nid 1 on hdac1
pcm5: <HDA Realtek ALC889 PCM #1 Analog> at cad 2 nid 1 on hdac1
pcm6: <HDA Realtek ALC889 PCM #2 Digital> at cad 2 nid 1 on hdac1
pcm7: <HDA Realtek ALC889 PCM #3 Digital> at cad 2 nid 1 on hdac1
...
----


In this example, the graphics card (``NVidia``) has been enumerated before the sound card (``Realtek ALC889``).  To use the sound card as the default playback device, change [var]``hw.snd.default_unit`` to the unit that should be used for playback:

----
# sysctl hw.snd.default_unit=n
----


where `n` is the number of the sound device to use.
In this example, it should be ``4``.
Make this change permanent by adding the following line to [path]``/etc/sysctl.conf``
:

[source]
----
hw.snd.default_unit=4
----

[[_sound_multiple_sources]]
=== Utilizing Multiple Sound Sources
= Utilizing Multiple Sound Sources
:imagesdir: ./images
Munish Chopra


It is often desirable to have multiple sources of sound that are able to play simultaneously.
FreeBSD uses "`Virtual Sound Channels`"
 to multiplex the sound card's playback by mixing sound in the kernel.

Three  {{< manpage "sysctl" "8" >}}
 knobs are available for configuring virtual channels:

----
# sysctl dev.pcm.0.play.vchans=4
# sysctl dev.pcm.0.rec.vchans=4
# sysctl hw.snd.maxautovchans=4
----


This example allocates four virtual channels, which is a practical number for everyday use.
Both [var]``dev.pcm.0.play.vchans=4`` and [var]``dev.pcm.0.rec.vchans=4`` are configurable after a device has been attached and represent the number of virtual channels [path]``pcm0``
 has for playback and recording.
Since the [path]``pcm``
 module can be loaded independently of the hardware drivers, [var]``hw.snd.maxautovchans`` indicates how many virtual channels will be given to an audio device when it is attached.
Refer to  {{< manpage "pcm" "4" >}}
 for more information.

[NOTE]
====
The number of virtual channels for a device cannot be changed while it is in use.
First, close any programs using the device, such as music players or sound daemons.
====


The correct [path]``pcm``
 device will automatically be allocated transparently to a program that requests [path]``/dev/dsp0``
.

=== Setting Default Values for Mixer Channels
= Setting Default Values for Mixer Channels
:imagesdir: ./images
Josef El-Rayes


The default values for the different mixer channels are hardcoded in the source code of the  {{< manpage "pcm" "4" >}}
 driver.
While sound card mixer levels can be changed using  {{< manpage "mixer" "8" >}}
 or third-party applications and daemons, this is not a permanent solution.
To instead set default mixer values at the driver level, define the appropriate values in [path]``/boot/device.hints``
, as seen in this example:

[source]
----
hint.pcm.0.vol="50"
----


This will set the volume channel to a default value of `50` when the  {{< manpage "pcm" "4" >}}
 module is loaded.

[[_sound_mp3]]
== MP3 Audio
= MP3 Audio
:imagesdir: ./images
Chern Lee


This section describes some [acronym]``MP3`` players available for FreeBSD, how to rip audio [acronym]``CD`` tracks, and how to encode and decode [acronym]``MP3``s.

=== MP3 Players


A popular graphical [acronym]``MP3`` player is [app]``Audacious``.
It supports [app]``Winamp`` skins and additional plugins.
The interface is intuitive, with a playlist, graphic equalizer, and more.
Those familiar with [app]``Winamp`` will find [app]``Audacious`` simple to use.
On FreeBSD, [app]``Audacious`` can be installed from the [package]#multimedia/audacious#
 port or package.
Audacious is a descendant of XMMS.

The [package]#audio/mpg123#
 package or port provides an alternative, command-line [acronym]``MP3``	player.
Once installed, specify the [acronym]``MP3``	file to play on the command line.
If the system has multiple audio devices, the sound device can also be specified:

----
# mpg123 -a /dev/dsp1.0 Foobar-GreatestHits.mp3High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.18.1; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes

Playing MPEG stream from Foobar-GreatestHits.mp3 ...
MPEG 1.0 layer III, 128 kbit/s, 44100 Hz joint-stereo
----


Additional [acronym]``MP3`` players are available in the FreeBSD Ports Collection.

[[_rip_cd]]
=== Ripping CD Audio Tracks


Before encoding a [acronym]``CD`` or [acronym]``CD`` track to [acronym]``MP3``, the audio data on the [acronym]``CD`` must be ripped to the hard drive.
This is done by copying the raw [acronym]``CD`` Digital Audio ([acronym]``CDDA``) data to [acronym]``WAV`` files.

The [command]``cdda2wav`` tool, which is installed with the [package]#sysutils/cdrtools#
 suite, can be used to rip audio information from [acronym]``CD``s.

With the audio [acronym]``CD`` in the drive, the following command can be issued as [username]``root``
 to rip an entire [acronym]``CD`` into individual, per track, [acronym]``WAV`` files:

----
# cdda2wav -D 0,1,0 -B
----


In this example, the [option]``-D [replaceable]``0,1,0```` indicates the [acronym]``SCSI`` device [path]``0,1,0``
	containing the [acronym]``CD`` to rip.
Use [command]``cdrecord -scanbus`` to determine the correct device parameters for the system.

To rip individual tracks, use [option]``-t`` to specify the track:

----
# cdda2wav -D 0,1,0 -t 7
----


To rip a range of tracks, such as track one to seven, specify a range:

----
# cdda2wav -D 0,1,0 -t 1+7
----


To rip from an [acronym]``ATAPI``	([acronym]``IDE``) [acronym]``CDROM`` drive, specify the device name in place of the [acronym]``SCSI`` unit numbers.
For example, to rip track 7 from an IDE drive:

----
# cdda2wav -D /dev/acd0 -t 7
----


Alternately, [command]``dd`` can be used to extract audio tracks on [acronym]``ATAPI`` drives, as described in <<_duplicating_audiocds>>.

[[_mp3_encoding]]
=== Encoding and Decoding MP3s

[app]``
Lame`` is a popular [acronym]``MP3`` encoder which can be installed from the [package]#audio/lame#
 port.
Due to patent issues, a package is not available.

The following command will convert the ripped [acronym]``WAV`` file [path]``audio01.wav``
 to [path]``audio01.mp3``
:

----
# lame -h -b 128 --tt "Foo Song Title" --ta "FooBar Artist" --tl "FooBar Album" \
--ty "2014" --tc "Ripped and encoded by Foo" --tg "Genre" audio01.wav audio01.mp3
----


The specified 128{nbsp}kbits is a standard [acronym]``MP3`` bitrate while the 160 and 192 bitrates provide higher quality.
The higher the bitrate, the larger the size of the resulting [acronym]``MP3``.
The [option]``-h`` turns on the "`higher quality but a little slower`"
	mode.
The options beginning with [option]``--t``	indicate [acronym]``ID3`` tags, which usually contain song information, to be embedded within the [acronym]``MP3`` file.
Additional encoding options can be found in the [app]``lame`` manual page.

In order to burn an audio [acronym]``CD`` from [acronym]``MP3``s, they must first be converted to a non-compressed file format.
 [app]``XMMS``	can be used to convert to the [acronym]``WAV`` format, while [app]``mpg123`` can be used to convert to the raw Pulse-Code Modulation ([acronym]``PCM``) audio data format.

To convert [path]``audio01.mp3``
 using [app]``mpg123``, specify the name of the [acronym]``PCM`` file:

----
# mpg123 -s audio01.mp3 > audio01.pcm
----


To use [app]``XMMS`` to convert a [acronym]``MP3`` to [acronym]``WAV`` format, use these steps:

.Procedure: Converting to [acronym]``WAV`` Format in[app]``XMMS``
. Launch [app]``XMMS``.
. Right-click the window to bring up the [app]``XMMS`` menu.
. Select `Preferences` under ``Options``.
. Change the Output Plugin to "`Disk Writer Plugin`" .
. Press ``Configure``.
. Enter or browse to a directory to write the uncompressed files to.
. Load the [acronym]``MP3`` file into [app]``XMMS`` as usual, with volume at 100% and EQ settings turned off.
. Press ``Play``. The [app]``XMMS`` will appear as if it is playing the [acronym]``MP3``, but no music will be heard. It is actually playing the [acronym]``MP3``	    to a file.
. When finished, be sure to set the default Output Plugin back to what it was before in order to listen to [acronym]``MP3``s again.


Both the [acronym]``WAV`` and [acronym]``PCM``	formats can be used with [app]``cdrecord``.
When using [acronym]``WAV`` files, there will be a small tick sound at the beginning of each track.
This sound is the header of the [acronym]``WAV`` file.
The [package]#audio/sox#
 port or package can be used to remove the header:

----
% sox -t wav -r 44100 -s -w -c 2 track.wav track.raw
----


Refer to <<_creating_cds>> for more information on using a [acronym]``CD`` burner in FreeBSD.

== Video Playback
= Video Playback
:imagesdir: ./images
Ross Lippert


Before configuring video playback, determine the model and chipset of the video card.
While [app]``Xorg`` supports a wide variety of video cards, not all provide good playback performance.
To obtain a list of extensions supported by the [app]``Xorg`` server using the card, run [command]``xdpyinfo`` while [app]``Xorg`` is running.

It is a good idea to have a short MPEG test file for evaluating various players and options.
Since some [acronym]``DVD`` applications look for [acronym]``DVD`` media in [path]``/dev/dvd``
 by default, or have this device name hardcoded in them, it might be useful to make a symbolic link to the proper device:

----
# ln -sf /dev/cd0 /dev/dvd
----


Due to the nature of  {{< manpage "devfs" "5" >}}
, manually created links will not persist after a system reboot.
In order to recreate the symbolic link automatically when the system boots, add the following line to [path]``/etc/devfs.conf``
:

[source]
----
link cd0 dvd
----

[acronym]``
DVD`` decryption invokes certain functions that require write permission to the [acronym]``DVD`` device.

To enhance the shared memory [app]``Xorg`` interface, it is recommended to increase the values of these  {{< manpage "sysctl" "8" >}}
 variables:

[source]
----
kern.ipc.shmmax=67108864
kern.ipc.shmall=32768
----

[[_video_interface]]
=== Determining Video Capabilities

(((XVideo)))

(((SDL)))

(((DGA)))


There are several possible ways to display video under [app]``Xorg`` and what works is largely hardware dependent.
Each method described below will have varying quality across different hardware.

Common video interfaces include:

. [app]``Xorg``: normal output using shared memory.
. XVideo: an extension to the [app]``Xorg`` interface which allows video to be directly displayed in drawable objects through a special acceleration. This extension provides good quality playback even on low-end machines. The next section describes how to determine if this extension is running.
. [acronym]``SDL``: the Simple Directmedia Layer is a porting layer for many operating systems, allowing cross-platform applications to be developed which make efficient use of sound and graphics. [acronym]``SDL`` provides a low-level abstraction to the hardware which can sometimes be more efficient than the [app]``Xorg`` interface. On FreeBSD, [acronym]``SDL`` can be installed using the [package]#devel/sdl20# package or port.
. [acronym]``DGA``: the Direct Graphics Access is an [app]``Xorg`` extension which allows a program to bypass the [app]``Xorg`` server and directly alter the framebuffer. Because it relies on a low level memory mapping, programs using it must be run as [username]``root`` . The [acronym]``DGA`` extension can be tested and benchmarked using  {{< manpage "dga" "1" >}} . When [command]``dga`` is running, it changes the colors of the display whenever a key is pressed. To quit, press kbd:[q] .
. SVGAlib: a low level console graphics layer.


[[_video_interface_xvideo]]
==== XVideo


To check whether this extension is running, use [command]``xvinfo``:

----
% xvinfo
----


XVideo is supported for the card if the result is similar to:

----
X-Video Extension version 2.2
  screen #0
  Adaptor #0: "Savage Streams Engine"
    number of ports: 1
    port base: 43
    operations supported: PutImage
    supported visuals:
      depth 16, visualID 0x22
      depth 16, visualID 0x23
    number of attributes: 5
      "XV_COLORKEY" (range 0 to 16777215)
              client settable attribute
              client gettable attribute (current value is 2110)
      "XV_BRIGHTNESS" (range -128 to 127)
              client settable attribute
              client gettable attribute (current value is 0)
      "XV_CONTRAST" (range 0 to 255)
              client settable attribute
              client gettable attribute (current value is 128)
      "XV_SATURATION" (range 0 to 255)
              client settable attribute
              client gettable attribute (current value is 128)
      "XV_HUE" (range -180 to 180)
              client settable attribute
              client gettable attribute (current value is 0)
    maximum XvImage size: 1024 x 1024
    Number of image formats: 7
      id: 0x32595559 (YUY2)
        guid: 59555932-0000-0010-8000-00aa00389b71
        bits per pixel: 16
        number of planes: 1
        type: YUV (packed)
      id: 0x32315659 (YV12)
        guid: 59563132-0000-0010-8000-00aa00389b71
        bits per pixel: 12
        number of planes: 3
        type: YUV (planar)
      id: 0x30323449 (I420)
        guid: 49343230-0000-0010-8000-00aa00389b71
        bits per pixel: 12
        number of planes: 3
        type: YUV (planar)
      id: 0x36315652 (RV16)
        guid: 52563135-0000-0000-0000-000000000000
        bits per pixel: 16
        number of planes: 1
        type: RGB (packed)
        depth: 0
        red, green, blue masks: 0x1f, 0x3e0, 0x7c00
      id: 0x35315652 (RV15)
        guid: 52563136-0000-0000-0000-000000000000
        bits per pixel: 16
        number of planes: 1
        type: RGB (packed)
        depth: 0
        red, green, blue masks: 0x1f, 0x7e0, 0xf800
      id: 0x31313259 (Y211)
        guid: 59323131-0000-0010-8000-00aa00389b71
        bits per pixel: 6
        number of planes: 3
        type: YUV (packed)
      id: 0x0
        guid: 00000000-0000-0000-0000-000000000000
        bits per pixel: 0
        number of planes: 0
        type: RGB (packed)
        depth: 1
        red, green, blue masks: 0x0, 0x0, 0x0
----


The formats listed, such as YUV2 and YUV12, are not present with every implementation of XVideo and their absence may hinder some players.

If the result instead looks like:

----
X-Video Extension version 2.2
screen #0
no adaptors present
----


XVideo is probably not supported for the card.
This means that it will be more difficult for the display to meet the computational demands of rendering video, depending on the video card and processor.

[[_video_ports]]
=== Ports and Packages Dealing with Video

(((video ports)))

(((video packages)))


This section introduces some of the software available from the FreeBSD Ports Collection which can be used for video playback.

[[_video_mplayer]]
==== MPlayer and MEncoder

[app]``
MPlayer`` is a command-line video player with an optional graphical interface which aims to provide speed and flexibility.
Other graphical front-ends to [app]``MPlayer`` are available from the FreeBSD Ports Collection.

(((MPlayer)))

[app]``
MPlayer`` can be installed using the [package]#multimedia/mplayer#
 package or port.
Several compile options are available and a variety of hardware checks occur during the build process.
For these reasons, some users prefer to build the port rather than install the package.

When compiling the port, the menu options should be reviewed to determine the type of support to compile into the port.
If an option is not selected, [app]``MPlayer`` will not be able to display that type of video format.
Use the arrow keys and spacebar to select the required formats.
When finished, press kbd:[Enter]
 to continue the port compile and installation.

By default, the package or port will build the [command]``mplayer`` command line utility and the [command]``gmplayer`` graphical utility.
To encode videos, compile the [package]#multimedia/mencoder#
	  port.
Due to licensing restrictions, a package is not available for [app]``MEncoder``.

The first time [app]``MPlayer`` is run, it will create [path]``~/.mplayer``
 in the user's home directory.
This subdirectory contains default versions of the user-specific configuration files.

This section describes only a few common uses.
Refer to mplayer(1) for a complete description of its numerous options.

To play the file [path]``testfile.avi``
, specify the video interfaces with [option]``-vo``, as seen in the following examples:

----
% mplayer -vo xv testfile.avi
----

----
% mplayer -vo sdl testfile.avi
----

----
% mplayer -vo x11 testfile.avi
----

----
# mplayer -vo dga testfile.avi
----

----
# mplayer -vo 'sdl:dga' testfile.avi
----


It is worth trying all of these options, as their relative performance depends on many factors and will vary significantly with hardware.

To play a [acronym]``DVD``, replace [path]``testfile.avi``
	  with [option]``dvd://[replaceable]``N`` -dvd-device
	   [replaceable]``DEVICE````, where [replaceable]``N`` is the title number to play and [replaceable]``DEVICE`` is the device node for the [acronym]``DVD``.
For example, to play title 3 from [path]``/dev/dvd``
:

----
# mplayer -vo xv dvd://3 -dvd-device /dev/dvd
----

[NOTE]
====
The default [acronym]``DVD`` device can be defined during the build of the [app]``MPlayer`` port by including the [var]``WITH_DVD_DEVICE=/path/to/desired/device``	    option.
By default, the device is [path]``/dev/cd0``
.
More details can be found in the port's [path]``Makefile.options``
.
====


To stop, pause, advance, and so on, use a keybinding.
To see the list of keybindings, run [command]``mplayer
	    -h`` or read mplayer(1).

Additional playback options include [option]``-fs
	    -zoom``, which engages fullscreen mode, and [option]``-framedrop``, which helps performance.

Each user can add commonly used options to their [path]``~/.mplayer/config``
 like so:

[source]
----
vo=xv
fs=yes
zoom=yes
----

[command]``
mplayer`` can be used to rip a [acronym]``DVD`` title to a [path]``.vob``
.
To dump the second title from a [acronym]``DVD``:

----
# mplayer -dumpstream -dumpfile out.vob dvd://2 -dvd-device /dev/dvd
----


The output file, [path]``out.vob``
, will be in [acronym]``MPEG`` format.

Anyone wishing to obtain a high level of expertise with UNIX(R) video should consult http://www.mplayerhq.hu/DOCS/[mplayerhq.hu/DOCS]	  as it is technically informative.
This documentation should be considered as required reading before submitting any bug reports.

(((mencoder)))


Before using [command]``mencoder``, it is a good idea to become familiar with the options described at http://www.mplayerhq.hu/DOCS/HTML/en/mencoder.html[mplayerhq.hu/DOCS/HTML/en/mencoder.html].
There are innumerable ways to improve quality, lower bitrate, and change formats, and some of these options may make the difference between good or bad performance.
Improper combinations of command line options can yield output files that are unplayable even by [command]``mplayer``.

Here is an example of a simple copy:

----
% mencoder input.avi -oac copy -ovc copy -o output.avi
----


To rip to a file, use [option]``-dumpfile`` with [command]``mplayer``.

To convert [path]``input.avi``
 to the MPEG4 codec with MPEG3 audio encoding, first install the [package]#audio/lame#
 port.
Due to licensing restrictions, a package is not available.
Once installed, type:

----
% mencoder input.avi -oac mp3lame -lameopts br=192 \
	 -ovc lavc -lavcopts vcodec=mpeg4:vhq -o output.avi
----


This will produce output playable by applications such as [command]``mplayer`` and [command]``xine``.

[path]``input.avi``
	  can be replaced with [option]``dvd://1 -dvd-device
	    /dev/dvd`` and run as [username]``root``
 to re-encode a [acronym]``DVD`` title directly.
Since it may take a few tries to get the desired result, it is recommended to instead dump the title to a file and to work on the file.

[[_video_xine]]
==== The xine Video Player

[app]``
xine`` is a video player with a reusable base library and a modular executable which can be extended with plugins.
It can be installed using the [package]#multimedia/xine#
 package or port.

In practice, [app]``xine`` requires either a fast CPU with a fast video card, or support for the XVideo extension.
The [app]``xine`` video player performs best on XVideo interfaces.

By default, the [app]``xine`` player starts a graphical user interface.
The menus can then be used to open a specific file.

Alternatively, [app]``xine`` may be invoked from the command line by specifying the name of the file to play:

----
% xine -g -p mymovie.avi
----


Refer to http://www.xine-project.org/faq[
	    xine-project.org/faq] for more information and troubleshooting tips.

[[_video_ports_transcode]]
==== The Transcode Utilities

[app]``
Transcode`` provides a suite of tools for re-encoding video and audio files. [app]``Transcode`` can be used to merge video files or repair broken files using command line tools with stdin/stdout stream interfaces.

In FreeBSD, [app]``Transcode`` can be installed using the [package]#multimedia/transcode#
	  package or port.
Many users prefer to compile the port as it provides a menu of compile options for specifying the support and codecs to compile in.
If an option is not selected, [app]``Transcode`` will not be able to encode that format.
Use the arrow keys and spacebar to select the required formats.
When finished, press kbd:[Enter]
 to continue the port compile and installation.

This example demonstrates how to convert a DivX file into a PAL MPEG-1 file (PAL VCD):

----
% transcode -i input.avi -V --export_prof vcd-pal -o output_vcd
% mplex -f 1 -o output_vcd.mpg output_vcd.m1v output_vcd.mpa
----


The resulting [acronym]``MPEG`` file, [path]``output_vcd.mpg``
, is ready to be played with [app]``MPlayer``.
The file can be burned on a [acronym]``CD`` media to create a video [acronym]``CD`` using a utility such as [package]#multimedia/vcdimager#
 or [package]#sysutils/cdrdao#
.

In addition to the manual page for [command]``transcode``, refer to  http://www.transcoding.org/cgi-bin/transcode[transcoding.org/cgi-bin/transcode]	  for further information and examples.

[[_tvcard]]
== TV Cards
= TV Cards
:imagesdir: ./images
Josef El-Rayes; Marc Fonvieille

(((TV cards)))


TV cards can be used to watch broadcast or cable TV on a computer.
Most cards accept composite video via an [acronym]``RCA`` or S-video input and some cards include a [acronym]``FM`` radio tuner.

FreeBSD provides support for PCI-based TV cards using a Brooktree Bt848/849/878/879 video capture chip with the  {{< manpage "bktr" "4" >}}
 driver.
This driver supports most Pinnacle PCTV video cards.
Before purchasing a TV card, consult  {{< manpage "bktr" "4" >}}
 for a list of supported tuners.

=== Loading the Driver


In order to use the card, the  {{< manpage "bktr" "4" >}}
 driver must be loaded.
To automate this at boot time, add the following line to [path]``/boot/loader.conf``
:

[source]
----
bktr_load="YES"
----


Alternatively, one can statically compile support for the TV card into a custom kernel.
In that case, add the following lines to the custom kernel configuration file:

[source]
----
device	 bktr
device	iicbus
device	iicbb
device	smbus
----


These additional devices are necessary as the card components are interconnected via an I2C bus.
Then, build and install a new kernel.

To test that the tuner is correctly detected, reboot the system.
The TV card should appear in the boot messages, as seen in this example:

[source]
----
bktr0: <BrookTree 848A> mem 0xd7000000-0xd7000fff irq 10 at device 10.0 on pci0
iicbb0: <I2C bit-banging driver> on bti2c0
iicbus0: <Philips I2C bus> on iicbb0 master-only
iicbus1: <Philips I2C bus> on iicbb0 master-only
smbus0: <System Management Bus> on bti2c0
bktr0: Pinnacle/Miro TV, Philips SECAM tuner.
----


The messages will differ according to the hardware.
If necessary, it is possible to override some of the detected parameters using  {{< manpage "sysctl" "8" >}}
 or custom kernel configuration options.
For example, to force the tuner to a Philips SECAM tuner, add the following line to a custom kernel configuration file:

[source]
----
options OVERRIDE_TUNER=6
----


or, use  {{< manpage "sysctl" "8" >}}
:

----
# sysctl hw.bt848.tuner=6
----


Refer to  {{< manpage "bktr" "4" >}}
 for a description of the available  {{< manpage "sysctl" "8" >}}
 parameters and kernel options.

=== Useful Applications


To use the TV card, install one of the following applications:

* [package]#multimedia/fxtv# provides TV-in-a-window and image/audio/video capture capabilities.
* [package]#multimedia/xawtv# is another TV application with similar features.
* [package]#audio/xmradio# provides an application for using the FM radio tuner of a TV card.


More applications are available in the FreeBSD Ports Collection.

=== Troubleshooting


If any problems are encountered with the TV card, check that the video capture chip and the tuner are supported by  {{< manpage "bktr" "4" >}}
 and that the right configuration options were used.
For more support or to ask questions about supported TV cards, refer to the link:freebsd-multimedia mailing list.

== MythTV


MythTV is a popular, open source Personal Video Recorder ([acronym]``PVR``) application.
This section demonstrates how to install and setup MythTV on FreeBSD.
Refer to http://www.mythtv.org/wiki/[mythtv.org/wiki] for more information on how to use MythTV.

MythTV requires a frontend and a backend.
These components can either be installed on the same system or on different machines.

The frontend can be installed on FreeBSD using the [package]#multimedia/mythtv-frontend#
 package or port. [app]``Xorg`` must also be installed and configured as described in <<_x11>>.
Ideally, this system has a video card that supports X-Video Motion Compensation ([acronym]``XvMC``) and, optionally, a Linux Infrared Remote Control ([acronym]``LIRC``)-compatible remote.

To install both the backend and the frontend on FreeBSD, use the [package]#multimedia/mythtv#
 package or port.
A MySQL(TM)
 database server is also required and should automatically be installed as a dependency.
Optionally, this system should have a tuner card and sufficient storage to hold recorded data.

=== Hardware


MythTV uses Video for Linux ([acronym]``V4L``) to access video input devices such as encoders and tuners.
In FreeBSD, MythTV works best with [acronym]``USB`` DVB-S/C/T cards as they are well supported by the [package]#multimedia/webcamd#
 package or port which provides a [acronym]``V4L`` userland application.
Any Digital Video Broadcasting ([acronym]``DVB``) card supported by [app]``webcamd`` should work with MythTV.
A list of known working cards can be found at https://wiki.freebsd.org/WebcamCompat[wiki.freebsd.org/WebcamCompat].
Drivers are also available for Hauppauge cards in the [package]#multimedia/pvr250#
 and [package]#multimedia/pvrxxx#
 ports, but they provide a non-standard driver interface that does not work with versions of MythTV greater than 0.23.
Due to licensing restrictions, no packages are available and these two ports must be compiled.

The https://wiki.freebsd.org/HTPC[wiki.freebsd.org/HTPC]	page contains a list of all available [acronym]``DVB``	drivers.

=== Setting up the MythTV Backend


To install MythTV using binary packages:

----
# pkg install mythtv
----


Alternatively, to install from the Ports Collection:

----
# cd /usr/ports/multimedia/mythtv
# make install
----


Once installed, set up the MythTV database:

----
# mysql -uroot -p < /usr/local/share/mythtv/database/mc.sql
----


Then, configure the backend:

----
# mythtv-setup
----


Finally, start the backend:

----
# sysrc mythbackend_enable=yes
# service mythbackend start
----

[[_scanners]]
== Image Scanners
= Image Scanners
:imagesdir: ./images
Marc Fonvieille

(((image scanners)))


In FreeBSD, access to image scanners is provided by [app]``SANE`` (Scanner Access Now Easy), which is available in the FreeBSD Ports Collection. [app]``SANE`` will also use some FreeBSD device drivers to provide access to the scanner hardware.

FreeBSD supports both [acronym]``SCSI`` and [acronym]``USB`` scanners.
Depending upon the scanner interface, different device drivers are required.
Be sure the scanner is supported by [app]``SANE`` prior to performing any configuration.
Refer to http://www.sane-project.org/sane-supported-devices.html[
      http://www.sane-project.org/sane-supported-devices.html] for more information about supported scanners.

This chapter describes how to determine if the scanner has been detected by FreeBSD.
It then provides an overview of how to configure and use [app]``SANE`` on a FreeBSD system.

[[_scanners_kernel_usb]]
=== Checking the Scanner


The [path]``GENERIC``
 kernel includes the device drivers needed to support [acronym]``USB``	scanners.
Users with a custom kernel should ensure that the following lines are present in the custom kernel configuration file:

[source]
----
device usb
device uhci
device ohci
device ehci
----


To determine if the [acronym]``USB`` scanner is detected, plug it in and use [command]``dmesg`` to determine whether the scanner appears in the system message buffer.
If it does, it should display a message similar to this:

----
ugen0.2: <EPSON> at usbus0
----


In this example, an EPSON
  Perfection(TM)
{nbsp}1650 [acronym]``USB`` scanner was detected on [path]``/dev/ugen0.2``
.

If the scanner uses a [acronym]``SCSI`` interface, it is important to know which [acronym]``SCSI``	controller board it will use.
Depending upon the [acronym]``SCSI`` chipset, a custom kernel configuration file may be needed.
The [path]``GENERIC``
 kernel supports the most common [acronym]``SCSI`` controllers.
Refer to [path]``/usr/src/sys/conf/NOTES``
 to determine the correct line to add to a custom kernel configuration file.
In addition to the [acronym]``SCSI`` adapter driver, the following lines are needed in a custom kernel configuration file:

[source]
----
device scbus
device pass
----


Verify that the device is displayed in the system message buffer:

----
pass2 at aic0 bus 0 target 2 lun 0
pass2: <AGFA SNAPSCAN 600 1.10> Fixed Scanner SCSI-2 device
pass2: 3.300MB/s transfers
----


If the scanner was not powered-on at system boot, it is still possible to manually force detection by performing a [acronym]``SCSI`` bus scan with [command]``camcontrol``:

----
# camcontrol rescan allRe-scan of bus 0 was successful
Re-scan of bus 1 was successful
Re-scan of bus 2 was successful
Re-scan of bus 3 was successful
----


The scanner should now appear in the [acronym]``SCSI`` devices list:

----
# camcontrol devlist<IBM DDRS-34560 S97B>              at scbus0 target 5 lun 0 (pass0,da0)
<IBM DDRS-34560 S97B>              at scbus0 target 6 lun 0 (pass1,da1)
<AGFA SNAPSCAN 600 1.10>           at scbus1 target 2 lun 0 (pass3)
<PHILIPS CDD3610 CD-R/RW 1.00>     at scbus2 target 0 lun 0 (pass2,cd0)
----


Refer to  {{< manpage "scsi" "4" >}}
 and  {{< manpage "camcontrol" "8" >}}
 for more details about [acronym]``SCSI`` devices on FreeBSD.

=== SANE Configuration


The [app]``SANE`` system is split in two parts: the backends ([package]#graphics/sane-backends#
) and the frontends ([package]#graphics/sane-frontends#
 or [package]#graphics/xsane#
).  The backends provide access to the scanner.
Refer to http://www.sane-project.org/sane-supported-devices.html	to determine which backend supports the scanner.
The frontends provide the graphical scanning interface. [package]#graphics/sane-frontends#
 installs [app]``xscanimage`` while [package]#graphics/xsane#
 installs [app]``xsane``.

To install the two parts from binary packages:

----
# pkg install xsane sane-frontends
----


Alternatively, to install from the Ports Collection

----
# cd /usr/ports/graphics/sane-frontends
# make install clean
# cd /usr/ports/graphics/xsane
# make install clean
----


After installing the [package]#graphics/sane-backends#
 port or package, use [command]``sane-find-scanner`` to check the scanner detection by the [app]``SANE``	system:

----
# sane-find-scanner -qfound SCSI scanner "AGFA SNAPSCAN 600 1.10" at /dev/pass3
----


The output should show the interface type of the scanner and the device node used to attach the scanner to the system.
The vendor and the product model may or may not appear.

[NOTE]
====
Some [acronym]``USB`` scanners require firmware to be loaded.
Refer to sane-find-scanner(1) and sane(7) for details.
====


Next, check if the scanner will be identified by a scanning frontend.
The [app]``SANE``	backends include [command]``scanimage`` which can be used to list the devices and perform an image acquisition.
Use [option]``-L`` to list the scanner devices.
The first example is for a [acronym]``SCSI`` scanner and the second is for a [acronym]``USB`` scanner:

----
# scanimage -Ldevice `snapscan:/dev/pass3' is a AGFA SNAPSCAN 600 flatbed scanner
# scanimage -Ldevice 'epson2:libusb:/dev/usb:/dev/ugen0.2' is a Epson GT-8200 flatbed scanner
----


In this second example, `'epson2:libusb:/dev/usb:/dev/ugen0.2'` is the backend name (``epson2``) and `/dev/ugen0.2` is the device node used by the scanner.

If [command]``scanimage`` is unable to identify the scanner, this message will appear:

----
# scanimage -LNo scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).
----


If this happens, edit the backend configuration file in [path]``/usr/local/etc/sane.d/``
 and define the scanner device used.
For example, if the undetected scanner model is an EPSON
  Perfection(TM)
{nbsp}1650 and it uses the `epson2` backend, edit [path]``/usr/local/etc/sane.d/epson2.conf``
.
When editing, add a line specifying the interface and the device node used.
In this case, add the following line:

[source]
----
usb /dev/ugen0.2
----


Save the edits and verify that the scanner is identified with the right backend name and the device node:

----
# scanimage -Ldevice 'epson2:libusb:/dev/usb:/dev/ugen0.2' is a Epson GT-8200 flatbed scanner
----


Once [command]``scanimage -L`` sees the scanner, the configuration is complete and the scanner is now ready to use.

While [command]``scanimage`` can be used to perform an image acquisition from the command line, it is often preferable to use a graphical interface to perform image scanning.
The [package]#graphics/sane-frontends#
	package or port installs a simple but efficient graphical interface, [app]``xscanimage``.

Alternately, [app]``xsane``, which is installed with the [package]#graphics/xsane#
 package or port, is another popular graphical scanning frontend.
It offers advanced features such as various scanning modes, color correction, and batch scans.
Both of these applications are usable as a [app]``GIMP`` plugin.

=== Scanner Permissions


In order to have access to the scanner, a user needs read and write permissions to the device node used by the scanner.
In the previous example, the [acronym]``USB`` scanner uses the device node [path]``/dev/ugen0.2``
 which is really a symlink to the real device node [path]``/dev/usb/0.2.0``
.
The symlink and the device node are owned, respectively, by the [groupname]``wheel``
 and [groupname]``operator``
 groups.
While adding the user to these groups will allow access to the scanner, it is considered insecure to add a user to [groupname]``wheel``
.
A better solution is to create a group and make the scanner device accessible to members of this group.

This example creates a group called [groupname]``usb``
:

----
# pw groupadd usb
----


Then, make the [path]``/dev/ugen0.2``
 symlink and the [path]``/dev/usb/0.2.0``
 device node accessible to the [groupname]``usb``
 group with write permissions of `0660` or `0664` by adding the following lines to [path]``/etc/devfs.rules``
:

[source]
----
[system=5]
add path ugen0.2 mode 0660 group usb
add path usb/0.2.0 mode 0666 group usb
----


Finally, add the users to [groupname]``usb``
	in order to allow access to the scanner:

----
# pw groupmod usb -m joe
----


For more details refer to  {{< manpage "pw" "8" >}}
.

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]