---
title: "Resources on the Internet"
---

:sectnums!:

[appendix]
[[_eresources]]
= Resources on the Internet


The rapid pace of FreeBSD progress makes print media impractical as a means of following the latest developments.
Electronic resources are the best, if not often the only, way to stay informed of the latest advances.
Since FreeBSD is a volunteer effort, the user community itself also generally serves as a "`technical support department`"
 of sorts, with electronic mail, web forums, and USENET news being the most effective way of reaching that community.

The most important points of contact with the FreeBSD user community are outlined below.
Please send other resources not mentioned here to the link:FreeBSD documentation project mailing list so that they may also be included.

[[_eresources_www]]
== Websites

* https://forums.FreeBSD.org/[The FreeBSD Forums] provide a web based discussion forum for FreeBSD questions and technical discussion.
* https://planet.freebsd.org/[Planet FreeBSD] offers an aggregation feed of dozens of blogs written by FreeBSD developers. Many developers use this to post quick notes about what they are working on, new patches, and other works in progress.
* The http://www.youtube.com/bsdconferences[BSDConferences YouTube Channel] provides a collection of high quality videos from BSD conferences around the world. This is a great way to watch key developers give presentations about new work in FreeBSD.


[[_eresources_mail]]
== Mailing Lists


The mailing lists are the most direct way of addressing questions or opening a technical discussion to a concentrated FreeBSD audience.
There are a wide variety of lists on a number of different FreeBSD topics.
Sending questions to the most appropriate mailing list will invariably assure a faster and more accurate response.

The charters for the various lists are given at the bottom of this document.
 __Please read the charter before
      joining or sending mail to any list__.
Most list subscribers receive many hundreds of FreeBSD related messages every day, and the charters and rules for use are meant to keep the signal-to-noise ratio of the lists high.
To do less would see the mailing lists ultimately fail as an effective communications medium for the Project.

[NOTE]
====
_To test the ability to send email to FreeBSD lists,
	  send a test message to link:freebsd-test._  Please do not send test messages to any other list.
====


When in doubt about what list to post a question to, see link:/doc/en_US.ISO8859-1/en_US.ISO8859-1/articles/freebsd-questions[How to get
	best results from the FreeBSD-questions mailing
	list].

Before posting to any list, please learn about how to best use the mailing lists, such as how to help avoid frequently-repeated discussions, by reading the link:/doc/en_US.ISO8859-1/en_US.ISO8859-1/articles/mailing-list-faq[Mailing List
	Frequently Asked Questions] (FAQ) document.

Archives are kept for all of the mailing lists and can be searched using the link:@@URL_RELPREFIX@@/search/index.html[FreeBSD World Wide
	Web server].
The keyword searchable archive offers an excellent way of finding answers to frequently asked questions and should be consulted before posting a question.
Note that this also means that messages sent to FreeBSD mailing lists are archived in perpetuity.
When protecting privacy is a concern, consider using a disposable secondary email address and posting only public information.

[[_eresources_summary]]
=== List Summary

_
General lists:_ The following are general lists which anyone is free (and encouraged) to join:

[cols="1,1", frame="none", options="header"]
|===
| List
| Purpose


|link:freebsd-advocacy
|FreeBSD Evangelism

|link:freebsd-announce
|Important events and Project milestones
		(moderated)

|link:freebsd-arch
|Architecture and design discussions

|link:freebsd-bugbusters
|Discussions pertaining to the maintenance of
		the FreeBSD problem report database and related
		tools

|link:freebsd-bugs
|Bug reports

|link:freebsd-chat
|Non-technical items related to the FreeBSD
		community

|link:freebsd-chromium
|FreeBSD-specific Chromium issues

|link:freebsd-current
|Discussion concerning the use of
		FreeBSD-CURRENT

|link:freebsd-isp
|Issues for Internet Service Providers using
		FreeBSD

|link:freebsd-jobs
|FreeBSD employment and consulting
		opportunities

|link:freebsd-questions
|User questions and technical support

|link:freebsd-security-notifications
|Security notifications (moderated)

|link:freebsd-stable
|Discussion concerning the use of
		FreeBSD-STABLE

|link:freebsd-test
|Where to send test messages instead of to
		one of the actual lists

|link:freebsd-women
|FreeBSD advocacy for women
|===

_
Technical lists:_ The following lists are for technical discussion.
Read the charter for each list carefully before joining or sending mail to one as there are firm guidelines for their use and content.

[cols="1,1", frame="none", options="header"]
|===
| List
| Purpose


|link:freebsd-acpi
|ACPI and power management development

|link:freebsd-afs
|Porting AFS to FreeBSD

|link:freebsd-amd64
|Porting FreeBSD to AMD64 systems (moderated)

|link:freebsd-apache
|Discussion about
		[app]``Apache`` related
		ports

|link:freebsd-arm
|Porting FreeBSD to ARM(TM)
 processors

|link:freebsd-atm
|Using ATM networking with FreeBSD

|link:freebsd-bluetooth
|Using Bluetooth(TM)
 technology in FreeBSD

|link:freebsd-cloud
|FreeBSD on cloud platforms (EC2, GCE, Azure,
		etc.)

|link:freebsd-cluster
|Using FreeBSD in a clustered environment

|link:freebsd-database
|Discussing database use and development under
		FreeBSD

|link:freebsd-desktop
|Using and improving FreeBSD on the desktop

|link:dev-ci
|Build and test reports from the Continuous
		Integration servers

|link:dev-reviews
|Notifications of the FreeBSD review
		system

|link:freebsd-doc
|Creating FreeBSD related documents

|link:freebsd-drivers
|Writing device drivers for FreeBSD

|link:freebsd-dtrace
|Using and working on DTrace in FreeBSD

|link:freebsd-eclipse
|FreeBSD users of Eclipse IDE, tools, rich client
		applications and ports.

|link:freebsd-elastic
|FreeBSD-specific ElasticSearch discussions

|link:freebsd-embedded
|Using FreeBSD in embedded applications

|link:freebsd-eol
|Peer support of FreeBSD-related software that
		is no longer supported by the FreeBSD Project.

|link:freebsd-emulation
|Emulation of other systems such as
		Linux/MS-DOS(TM)
/Windows(TM)

|link:freebsd-enlightenment
|Porting [app]``Enlightenment``
		and [app]``Enlightenment``
		applications

|link:freebsd-erlang
|FreeBSD-specific Erlang discussions

|link:freebsd-firewire
|FreeBSD FireWire(TM)
 (iLink, IEEE 1394) technical
		discussion

|link:freebsd-fortran
|Fortran on FreeBSD

|link:freebsd-fs
|File systems

|link:freebsd-games
|Support for Games on FreeBSD

|link:freebsd-gecko
|[app]``Gecko Rendering
		  Engine`` issues

|link:freebsd-geom
|GEOM-specific discussions and
		implementations

|link:freebsd-git
|Discussion of git use in the FreeBSD project

|link:freebsd-gnome
|Porting [app]``GNOME`` and
		[app]``GNOME`` applications

|link:freebsd-hackers
|General technical discussion

|link:freebsd-haskell
|FreeBSD-specific Haskell issues and
		discussions

|link:freebsd-hardware
|General discussion of hardware for running
		FreeBSD

|link:freebsd-i18n
|FreeBSD Internationalization

|link:freebsd-ia32
|FreeBSD on the IA-32 (Intel(TM)
 x86)
		platform

|link:freebsd-ia64
|Porting FreeBSD to Intel(TM)
's upcoming IA64
		systems

|link:freebsd-infiniband
|Infiniband on FreeBSD

|link:freebsd-ipfw
|Technical discussion concerning the redesign
		of the IP firewall code

|link:freebsd-isdn
|ISDN developers

|link:freebsd-jail
|Discussion about the  {{< manpage "jail" "8" >}}

		facility

|link:freebsd-java
|Java(R) developers and people porting JDK(R)s to
		FreeBSD

|link:freebsd-lfs
|Porting LFS to FreeBSD

|link:freebsd-mips
|Porting FreeBSD to MIPS(TM)

|link:freebsd-mobile
|Discussions about mobile computing

|link:freebsd-mono
|Mono and C# applications on FreeBSD

|link:freebsd-multimedia
|Multimedia applications

|link:freebsd-new-bus
|Technical discussions about bus
		architecture

|link:freebsd-net
|Networking discussion and TCP/IP source
		code

|link:freebsd-numerics
|Discussions of high quality implementation of
		libm functions

|link:freebsd-ocaml
|FreeBSD-specific OCaml discussions

|link:freebsd-office
|Office applications on FreeBSD

|link:freebsd-performance
|Performance tuning questions for high
		performance/load installations

|link:freebsd-perl
|Maintenance of a number of
		Perl-related ports

|link:freebsd-pf
|Discussion and questions about the packet filter
		firewall system

|link:freebsd-pkg
|Binary package management and package
		tools discussion

|link:freebsd-pkg-fallout
|Fallout logs from package building

|link:freebsd-pkgbase
|Packaging the FreeBSD base system

|link:freebsd-platforms
|Concerning ports to non Intel(TM)
 architecture
		platforms

|link:freebsd-ports
|Discussion of the Ports Collection

|link:freebsd-ports-announce
|Important news and instructions about the Ports
		Collection (moderated)

|link:freebsd-ports-bugs
|Discussion of the ports bugs/PRs

|link:freebsd-ppc
|Porting FreeBSD to the PowerPC(TM)

|link:freebsd-proliant
|Technical discussion of FreeBSD on HP ProLiant
		server platforms

|link:freebsd-python
|FreeBSD-specific Python issues

|link:freebsd-rc
|Discussion related to the
		[path]``rc.d``
 system and its
		development

|link:freebsd-realtime
|Development of realtime extensions to
		FreeBSD

|link:freebsd-ruby
|FreeBSD-specific Ruby discussions

|link:freebsd-scsi
|The SCSI subsystem

|link:freebsd-security
|Security issues affecting FreeBSD

|link:freebsd-small
|Using FreeBSD in embedded applications
		(obsolete; use link:freebsd-embedded instead)

|link:freebsd-snapshots
|FreeBSD Development Snapshot Announcements

|link:freebsd-sparc64
|Porting FreeBSD to SPARC(TM)
 based systems

|link:freebsd-standards
|FreeBSD's conformance to the C99 and the POSIX(R)
		standards

|link:freebsd-sysinstall
| {{< manpage "sysinstall" "8" >}}
 development

|link:freebsd-tcltk
|FreeBSD-specific Tcl/Tk discussions

|link:freebsd-testing
|Testing on FreeBSD

|link:freebsd-tex
|Porting [app]``TeX`` and its
		applications to FreeBSD

|link:freebsd-threads
|Threading in FreeBSD

|link:freebsd-tilera
|Porting FreeBSD to the Tilera family of
		CPUs

|link:freebsd-tokenring
|Support Token Ring in FreeBSD

|link:freebsd-toolchain
|Maintenance of FreeBSD's integrated
		toolchain

|link:freebsd-translators
|Translating FreeBSD documents and programs

|link:freebsd-transport
|Discussions of transport level network protocols
		in FreeBSD

|link:freebsd-usb
|Discussing FreeBSD support for USB

|link:freebsd-virtualization
|Discussion of various virtualization techniques
		supported by FreeBSD

|link:freebsd-vuxml
|Discussion on VuXML infrastructure

|link:freebsd-x11
|Maintenance and support of X11 on FreeBSD

|link:freebsd-xen
|Discussion of the FreeBSD port to Xen(TM)
 --
		implementation and usage

|link:freebsd-xfce
|[app]``XFCE`` for FreeBSD --
		porting and maintaining

|link:freebsd-zope
|[app]``Zope`` for FreeBSD --
		porting and maintaining
|===

_
Limited lists:_  The following lists are for more specialized (and demanding) audiences and are probably not of interest to the general public.
It is also a good idea to establish a presence in the technical lists before joining one of these limited lists in order to understand the communications etiquette involved.

[cols="1,1", frame="none", options="header"]
|===
| List
| Purpose


|link:freebsd-hubs
|People running mirror sites (infrastructural
		support)

|link:freebsd-user-groups
|User group coordination

|link:freebsd-wip-status
|FreeBSD Work-In-Progress Status

|link:freebsd-wireless
|Discussions of 802.11 stack, tools, device driver
		development
|===

_
Digest lists:_  All of the above lists are available in a digest format.
Once subscribed to a list, the digest options can be changed in the account options section.

_SVN lists:_ The following lists are for people interested in seeing the log messages for changes to various areas of the source tree.
They are _Read-Only_ lists and should not have mail sent to them.

[cols="1,1,1", frame="none", options="header"]
|===
| List
| Source area
| Area Description (source for)


|link:svn-doc-all
|[path]``/usr/doc``
|
All changes to the doc Subversion repository
		(except for [path]``user``
,[path]``projects``
 and[path]``translations``
)

|link:svn-doc-head
|[path]``/usr/doc``
|
All changes to the "`head`"
 branch of
		the doc Subversion repository

|link:svn-doc-projects
|[path]``/usr/doc/projects``
|
All changes to the [path]``projects``

		area of the doc Subversion repository

|link:svn-doc-svnadmin
|[path]``/usr/doc``
|
All changes to the administrative scripts, hooks,
		and other configuration data of the doc Subversion
		repository

|link:svn-ports-all
|[path]``/usr/ports``
|
All changes to the ports Subversion
		repository

|link:svn-ports-head
|[path]``/usr/ports``
|
All changes to the "`head`"
 branch
		of the ports Subversion repository

|link:svn-ports-svnadmin
|[path]``/usr/ports``
|
All changes to the administrative scripts, hooks,
		and other configuration data of the ports Subversion
		repository

|link:svn-src-all
|[path]``/usr/src``
|
All changes to the src Subversion repository
		(except for [path]``user``

		and [path]``projects``
)

|link:svn-src-head
|[path]``/usr/src``
|
All changes to the "`head`"
 branch
		of the src Subversion repository (the FreeBSD-CURRENT
		branch)

|link:svn-src-projects
|[path]``/usr/projects``
|
All changes to the [path]``projects``

		area of the src Subversion repository

|link:svn-src-release
|[path]``/usr/src``
|
All changes to the [path]``releases``

		area of the src Subversion repository

|link:svn-src-releng
|[path]``/usr/src``
|
All changes to the [path]``releng``

		branches of the src Subversion repository (the
		security{nbsp}/ release engineering branches)

|link:svn-src-stable
|[path]``/usr/src``
|
All changes to the all stable branches of the src
		Subversion repository

|link:svn-src-stable-6
|[path]``/usr/src``
|
All changes to the [path]``stable/6``

		branch of the src Subversion repository

|link:svn-src-stable-7
|[path]``/usr/src``
|
All changes to the [path]``stable/7``

		branch of the src Subversion repository

|link:svn-src-stable-8
|[path]``/usr/src``
|
All changes to the [path]``stable/8``

		branch of the src Subversion repository

|link:svn-src-stable-9
|[path]``/usr/src``
|
All changes to the [path]``stable/9``

		branch of the src Subversion repository

|link:svn-src-stable-10
|[path]``/usr/src``
|
All changes to the [path]``stable/10``

		branch of the src Subversion repository

|link:svn-src-stable-11
|[path]``/usr/src``
|
All changes to the [path]``stable/11``

		branch of the src Subversion repository

|link:svn-src-stable-12
|[path]``/usr/src``
|
All changes to the [path]``stable/12``

		branch of the src Subversion repository

|link:svn-src-stable-other
|[path]``/usr/src``
|
All changes to the
		older [path]``stable``
 branches of the src
		Subversion repository

|link:svn-src-svnadmin
|[path]``/usr/src``
|
All changes to the administrative scripts, hooks,
		and other configuration data of the src Subversion
		repository

|link:svn-src-user
|[path]``/usr/src``
|
All changes to the
		experimental [path]``user``
 area of the src
		Subversion repository

|link:svn-src-vendor
|[path]``/usr/src``
|
All changes to the vendor work area of the src
		Subversion repository
|===

[[_eresources_subscribe]]
=== How to Subscribe


To subscribe to a list, click the list name at http://lists.FreeBSD.org/mailman/listinfo.
The page that is displayed should contain all of the necessary subscription instructions for that list.

To actually post to a given list, send mail to 
mailto:listname@FreeBSD.org[<listname@FreeBSD.org>]
.
It will then be redistributed to mailing list members world-wide.

To unsubscribe from a list, click on the URL found at the bottom of every email received from the list.
It is also possible to send an email to 
mailto:listname-unsubscribe@FreeBSD.org[<listname-unsubscribe@FreeBSD.org>]
	to unsubscribe.

It is important to keep discussion in the technical mailing lists on a technical track.
To only receive important announcements, instead join the link:FreeBSD announcements mailing list, which is intended for infrequent traffic.

[[_eresources_charters]]
=== List Charters

_
All_ FreeBSD mailing lists have certain basic rules which must be adhered to by anyone using them.
Failure to comply with these guidelines will result in two (2) written warnings from the FreeBSD Postmaster 
mailto:postmaster@FreeBSD.org[<postmaster@FreeBSD.org>]
, after which, on a third offense, the poster will removed from all FreeBSD mailing lists and filtered from further posting to them.
We regret that such rules and measures are necessary at all, but today's Internet is a pretty harsh environment, it would seem, and many fail to appreciate just how fragile some of its mechanisms are.

Rules of the road:

* The topic of any posting should adhere to the basic charter of the list it is posted to. If the list is about technical issues, the posting should contain technical discussion. Ongoing irrelevant chatter or flaming only detracts from the value of the mailing list for everyone on it and will not be tolerated. For free-form discussion on no particular topic, the link:FreeBSD chat mailing list is freely available and should be used instead.
* No posting should be made to more than 2 mailing lists, and only to 2 when a clear and obvious need to post to both lists exists. For most lists, there is already a great deal of subscriber overlap and except for the most esoteric mixes (say "`-stable & -scsi`" ), there really is no reason to post to more than one list at a time. If a message is received with multiple mailing lists on the `Cc` line, trim the `Cc` line before replying. _The person who replies is still responsible for cross-posting, no matter who the originator might have been._
* Personal attacks and profanity (in the context of an argument) are not allowed, and that includes users and developers alike. Gross breaches of netiquette, like excerpting or reposting private mail when permission to do so was not and would not be forthcoming, are frowned upon but not specifically enforced. __However__, there are also very few cases where such content would fit within the charter of a list and it would therefore probably rate a warning (or ban) on that basis alone.
* Advertising of non-FreeBSD related products or services is strictly prohibited and will result in an immediate ban if it is clear that the offender is advertising by spam.

_
Individual list charters:_

link:freebsd-acpi::
_ACPI and power management
development_

link:freebsd-afs::
_Andrew File System_
+
This list is for discussion on porting and using AFS from CMU/Transarc

link:freebsd-announce::
_Important events /
milestones_
+
This is the mailing list for people interested only in occasional announcements of significant FreeBSD events.
This includes announcements about snapshots and other releases.
It contains announcements of new FreeBSD capabilities.
It may contain calls for volunteers etc.
This is a low volume, strictly moderated mailing list.

link:freebsd-arch::
_Architecture and design
discussions_
+
This list is for discussion of the FreeBSD architecture.
Messages will mostly be kept strictly technical in nature.
Examples of suitable topics are:
** How to re-vamp the build system to have several customized builds running at the same time.
** What needs to be fixed with VFS to make Heidemann layers work.
** How do we change the device driver interface to be able to use the same drivers cleanly on many buses and architectures.
** How to write a network driver.

link:freebsd-bluetooth::
_Bluetooth(TM)
in FreeBSD_
+
This is the forum where FreeBSD's Bluetooth(TM)
users congregate.
Design issues, implementation details, patches, bug reports, status reports, feature requests, and all matters related to Bluetooth(TM)
are fair game.

link:freebsd-bugbusters::
_Coordination of the Problem Report
handling effort_
+
The purpose of this list is to serve as a coordination and discussion forum for the Bugmeister, his Bugbusters, and any other parties who have a genuine interest in the PR database.
This list is not for discussions about specific bugs, patches or PRs.

link:freebsd-bugs::
_Bug reports_
+
This is the mailing list for reporting bugs in FreeBSD.
Whenever possible, bugs should be submitted using the https://bugs.freebsd.org/bugzilla/enter_bug.cgi[web
interface] to it.

link:freebsd-chat::
_Non technical items related to the FreeBSD
community_
+
This list contains the overflow from the other lists about non-technical, social information.
It includes discussion about whether Jordan looks like a toon ferret or not, whether or not to type in capitals, who is drinking too much coffee, where the best beer is brewed, who is brewing beer in their basement, and so on.
Occasional announcements of important events (such as upcoming parties, weddings, births, new jobs, etc) can be made to the technical lists, but the follow ups should be directed to this -chat list.

link:freebsd-chromium::
_FreeBSD-specific Chromium
issues_
+
This is a list for the discussion of Chromium support for FreeBSD.
This is a technical list to discuss development and installation of Chromium.

link:freebsd-cloud::
_Running FreeBSD on various cloud
platforms_
+
This list discusses running FreeBSD on Amazon EC2, Google Compute Engine, Microsoft Azure, and other cloud computing platforms.

freebsd-core::
_FreeBSD core team_
+
This is an internal mailing list for use by the core members.
Messages can be sent to it when a serious FreeBSD-related matter requires arbitration or high-level scrutiny.

link:freebsd-current::
_Discussions about the use of
FreeBSD-CURRENT_
+
This is the mailing list for users of FreeBSD-CURRENT.
It includes warnings about new features coming out in -CURRENT that will affect the users, and instructions on steps that must be taken to remain -CURRENT.
Anyone running "`CURRENT`"
must subscribe to this list.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-desktop::
_Using and improving FreeBSD on the
desktop_
+
This is a forum for discussion of FreeBSD on the desktop.
It is primarily a place for desktop porters and users to discuss issues and improve FreeBSD's desktop support.

link:dev-ci::
_Continuous Integration reports of build
and test results_
+
All Continuous Integration reports of build and test results

link:dev-reviews::
_Notifications of work in progress in
FreeBSD's review tool_
+
Automated notifications of work in progress for review in FreeBSD's review tools, including patches.

link:freebsd-doc::
_Documentation Project_
+
This mailing list is for the discussion of issues and projects related to the creation of documentation for FreeBSD.
The members of this mailing list are collectively referred to as "`The FreeBSD
Documentation Project`"
.
It is an open list; feel free to join and contribute!

link:freebsd-drivers::
_Writing device drivers for
FreeBSD_
+
This is a forum for technical discussions related to device drivers on FreeBSD.
It is primarily a place for device driver writers to ask questions about how to write device drivers using the APIs in the FreeBSD kernel.

link:freebsd-dtrace::
_Using and working on DTrace in
FreeBSD_
+
DTrace is an integrated component of FreeBSD that provides a framework for understanding the kernel as well as user space programs at run time.
The mailing list is an archived discussion for developers of the code as well as those using it.

link:freebsd-eclipse::
_FreeBSD users of Eclipse IDE, tools, rich
client applications and ports._
+
The intention of this list is to provide mutual support for everything to do with choosing, installing, using, developing and maintaining the Eclipse IDE, tools, rich client applications on the FreeBSD platform and assisting with the porting of Eclipse IDE and plugins to the FreeBSD environment.
+
The intention is also to facilitate exchange of information between the Eclipse community and the FreeBSD community to the mutual benefit of both.
+
Although this list is focused primarily on the needs of Eclipse users it will also provide a forum for those who would like to develop FreeBSD specific applications using the Eclipse framework.

link:freebsd-embedded::
_Using FreeBSD in embedded
applications_
+
This list discusses topics related to using FreeBSD in embedded systems.
This is a technical mailing list for which strictly technical content is expected.
For the purpose of this list, embedded systems are those computing devices which are not desktops and which usually serve a single purpose as opposed to being general computing environments.
Examples include, but are not limited to, all kinds of phone handsets, network equipment such as routers, switches and PBXs, remote measuring equipment, PDAs, Point Of Sale systems, and so on.

link:freebsd-emulation::
_Emulation of other systems such as
Linux/MS-DOS(TM)
/Windows(TM)_
+
This is a forum for technical discussions related to running programs written for other operating systems on FreeBSD.

link:freebsd-enlightenment::
_Enlightenment_
+
Discussions concerning the [app]``Enlightenment`` Desktop Environment for FreeBSD systems.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-eol::
_Peer support of FreeBSD-related software
that is no longer supported by the FreeBSD
Project._
+
This list is for those interested in providing or making use of peer support of FreeBSD-related software for which the FreeBSD Project no longer provides official support in the form of security advisories and patches.

link:freebsd-firewire::
_FireWire(TM)
(iLink, IEEE
1394)_
+
This is a mailing list for discussion of the design and implementation of a FireWire(TM)
(aka IEEE 1394 aka iLink) subsystem for FreeBSD.
Relevant topics specifically include the standards, bus devices and their protocols, adapter boards/cards/chips sets, and the architecture and implementation of code for their proper support.

link:freebsd-fortran::
_Fortran on FreeBSD_
+
This is the mailing list for discussion of Fortran related ports on FreeBSD: compilers, libraries, scientific and engineering applications from laptops to HPC clusters.

link:freebsd-fs::
_File systems_
+
Discussions concerning FreeBSD filesystems.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-games::
_Games on FreeBSD_
+
This is a technical list for discussions related to bringing games to FreeBSD.
It is for individuals actively working on porting games to FreeBSD, to bring up problems or discuss alternative solutions.
Individuals interested in following the technical discussion are also welcome.

link:freebsd-gecko::
_Gecko Rendering Engine_
+
This is a forum about [app]``Gecko`` applications using FreeBSD.
+
Discussion centers around Gecko Ports applications, their installation, their development and their support within FreeBSD.

link:freebsd-geom::
_GEOM_
+
Discussions specific to GEOM and related implementations.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-git::
_Use of git in the FreeBSD
project_
+
Discussions of how to use git in FreeBSD infrastructure including the github mirror and other uses of git for project collaboration.
Discussion area for people using git against the FreeBSD github mirror.
People wanting to get started with the mirror or git in general on FreeBSD can ask here.

link:freebsd-gnome::
_GNOME_
+
Discussions concerning The [app]``GNOME`` Desktop Environment for FreeBSD systems.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-infiniband::
_Infiniband on FreeBSD_
+
Technical mailing list discussing Infiniband, OFED, and OpenSM on FreeBSD.

link:freebsd-ipfw::
_IP Firewall_
+
This is the forum for technical discussions concerning the redesign of the IP firewall code in FreeBSD.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-ia64::
_Porting FreeBSD to IA64_
+
This is a technical mailing list for individuals actively working on porting FreeBSD to the IA-64 platform from Intel(TM)
, to bring up problems or discuss alternative solutions.
Individuals interested in following the technical discussion are also welcome.

link:freebsd-isdn::
_ISDN Communications_
+
This is the mailing list for people discussing the development of ISDN support for FreeBSD.

link:freebsd-java::
_Java(R) Development_
+
This is the mailing list for people discussing the development of significant Java(R) applications for FreeBSD and the porting and maintenance of JDK(R)s.

[[_eresources_charters_jobs]]
link:freebsd-jobs::
_Jobs offered and sought_
+
This is a forum for posting employment notices specifically related to FreeBSD and resumes from those seeking FreeBSD-related employment.
This is _not_ a mailing list for general employment issues since adequate forums for that already exist elsewhere.
+
Note that this list, like other [fqdomainname]``FreeBSD.org``
mailing lists, is distributed worldwide.
Be clear about the geographic location and the extent to which telecommuting or assistance with relocation is available.
+
Email should use open formats only -- preferably plain text, but basic Portable Document Format ([acronym]``PDF``), HTML, and a few others are acceptable to many readers.
Closed formats such as Microsoft(TM)
Word ([path]``.doc``
) will be rejected by the mailing list server.

link:freebsd-kde::
_KDE_
+
Discussions concerning [app]``KDE`` on FreeBSD systems.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-hackers::
_Technical discussions_
+
This is a forum for technical discussions related to FreeBSD.
This is the primary technical mailing list.
It is for individuals actively working on FreeBSD, to bring up problems or discuss alternative solutions.
Individuals interested in following the technical discussion are also welcome.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-hardware::
_General discussion of FreeBSD
hardware_
+
General discussion about the types of hardware that FreeBSD runs on, various problems and suggestions concerning what to buy or avoid.

link:freebsd-hubs::
_Mirror sites_
+
Announcements and discussion for people who run FreeBSD mirror sites.

link:freebsd-isp::
_Issues for Internet Service
Providers_
+
This mailing list is for discussing topics relevant to Internet Service Providers (ISPs) using FreeBSD.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-mono::
_Mono and C# applications on
FreeBSD_
+
This is a list for discussions related to the Mono development framework on FreeBSD.
This is a technical mailing list.
It is for individuals actively working on porting Mono or C# applications to FreeBSD, to bring up problems or discuss alternative solutions.
Individuals interested in following the technical discussion are also welcome.

link:freebsd-ocaml::
_FreeBSD-specific OCaml
discussions_
+
This is a list for discussions related to the OCaml support on FreeBSD.
This is a technical mailing list.
It is for individuals working on OCaml ports, 3rd party libraries and frameworks.
Individuals interested in the technical discussion are also welcome.

link:freebsd-office::
_Office applications on
FreeBSD_
+
Discussion centers around office applications, their installation, their development and their support within FreeBSD.

link:freebsd-ops-announce::
_Project Infrastructure
Announcements_
+
This is the mailing list for people interested in changes and issues related to the FreeBSD.org Project infrastructure.
+
This moderated list is strictly for announcements: no replies, requests, discussions, or opinions.

link:freebsd-performance::
_Discussions about tuning or speeding up
FreeBSD_
+
This mailing list exists to provide a place for hackers, administrators, and/or concerned parties to discuss performance related topics pertaining to FreeBSD.
Acceptable topics includes talking about FreeBSD installations that are either under high load, are experiencing performance problems, or are pushing the limits of FreeBSD.
Concerned parties that are willing to work toward improving the performance of FreeBSD are highly encouraged to subscribe to this list.
This is a highly technical list ideally suited for experienced FreeBSD users, hackers, or administrators interested in keeping FreeBSD fast, robust, and scalable.
This list is not a question-and-answer list that replaces reading through documentation, but it is a place to make contributions or inquire about unanswered performance related topics.

link:freebsd-pf::
_Discussion and questions about the packet
filter firewall system_
+
Discussion concerning the packet filter (pf) firewall system in terms of FreeBSD.
Technical discussion and user questions are both welcome.
This list is also a place to discuss the ALTQ QoS framework.

link:freebsd-pkg::
_Binary package management and package
tools discussion_
+
Discussion of all aspects of managing FreeBSD systems by using binary packages to install software, including binary package toolkits and formats, their development and support within FreeBSD, package repository management, and third party packages.
+
Note that discussion of ports which fail to generate packages correctly should generally be considered as ports problems, and so inappropriate for this list.

link:freebsd-pkg-fallout::
_Fallout logs from package
building_
+
All packages building failures logs from the package building clusters

link:freebsd-pkgbase::
_Packaging the FreeBSD base
system._
+
Discussions surrounding implementation and issues regarding packaging the FreeBSD base system.

link:freebsd-platforms::
_Porting to Non Intel(TM)
platforms_
+
Cross-platform FreeBSD issues, general discussion and proposals for non Intel(TM)
FreeBSD ports.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-ports::
_Discussion of
"`ports`"_
+
Discussions concerning FreeBSD's "`ports
collection`"
([path]``/usr/ports``
), ports infrastructure, and general ports coordination efforts.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-ports-announce::
_Important news and instructions about the
FreeBSD{nbsp}"`Ports
Collection`"_
+
Important news for developers, porters, and users of the "`Ports Collection`"
([path]``/usr/ports``
), including architecture/infrastructure changes, new capabilities, critical upgrade instructions, and release engineering information.
This is a low-volume mailing list, intended for announcements.

link:freebsd-ports-bugs::
_Discussion of
"`ports`"
bugs_
+
Discussions concerning problem reports for FreeBSD's "`ports collection`"
([path]``/usr/ports``
), proposed ports, or modifications to ports.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-proliant::
_Technical discussion of FreeBSD on HP
ProLiant server platforms_
+
This mailing list is to be used for the technical discussion of the usage of FreeBSD on HP ProLiant servers, including the discussion of ProLiant-specific drivers, management software, configuration tools, and BIOS updates.
As such, this is the primary place to discuss the hpasmd, hpasmcli, and hpacucli modules.

link:freebsd-python::
_Python on FreeBSD_
+
This is a list for discussions related to improving Python-support on FreeBSD.
This is a technical mailing list.
It is for individuals working on porting Python, its third party modules and [app]``Zope`` stuff to FreeBSD.
Individuals interested in following the technical discussion are also welcome.

link:freebsd-questions::
_User questions_
+
This is the mailing list for questions about FreeBSD.
Do not send "`how to`"
questions to the technical lists unless the question is quite technical.

link:freebsd-ruby::
_FreeBSD-specific Ruby
discussions_
+
This is a list for discussions related to the Ruby support on FreeBSD.
This is a technical mailing list.
It is for individuals working on Ruby ports, third party libraries and frameworks.
+
Individuals interested in the technical discussion are also welcome.

link:freebsd-scsi::
_SCSI subsystem_
+
This is the mailing list for people working on the SCSI subsystem for FreeBSD.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-security::
_Security issues_
+
FreeBSD computer security issues (DES, Kerberos, known security holes and fixes, etc).  This is a technical mailing list for which strictly technical discussion is expected.
Note that this is not a question-and-answer list, but that contributions (BOTH question AND answer) to the FAQ are welcome.

link:freebsd-security-notifications::
_Security Notifications_
+
Notifications of FreeBSD security problems and fixes.
This is not a discussion list.
The discussion list is FreeBSD-security.

link:freebsd-small::
_Using FreeBSD in embedded
applications_
+
This list discusses topics related to unusually small and embedded FreeBSD installations.
This is a technical mailing list for which strictly technical content is expected.
+

NOTE: This list has been obsoleted by link:freebsd-embedded.
+


link:freebsd-snapshots::
_FreeBSD Development Snapshot
Announcements_
+
This list provides notifications about the availability of new FreeBSD development snapshots for the head/ and stable/ branches.

link:freebsd-stable::
_Discussions about the use of
FreeBSD-STABLE_
+
This is the mailing list for users of FreeBSD-STABLE. "`STABLE`"
is the branch where development continues after a RELEASE, including bug fixes and new features.
The ABI is kept stable for binary compatibility.
It includes warnings about new features coming out in -STABLE that will affect the users, and instructions on steps that must be taken to remain -STABLE.
Anyone running "`STABLE`"
should subscribe to this list.
This is a technical mailing list for which strictly technical content is expected.

link:freebsd-standards::
_C99 & POSIX
Conformance_
+
This is a forum for technical discussions related to FreeBSD Conformance to the C99 and the POSIX standards.

link:freebsd-teaching::
_Teaching with FreeBSD_
+
Non technical mailing list discussing teaching with FreeBSD.

link:freebsd-testing::
_Testing on FreeBSD_
+
Technical mailing list discussing testing on FreeBSD, including ATF/Kyua, test build infrastructure, port tests to FreeBSD from other operating systems (NetBSD, ...), etc.

link:freebsd-tex::
_Porting [app]``__TeX__`` and
its applications to FreeBSD_
+
This is a technical mailing list for discussions related to TeX and its applications on FreeBSD.
It is for individuals actively working on porting TeX to FreeBSD, to bring up problems or discuss alternative solutions.
Individuals interested in following the technical discussion are also welcome.

link:freebsd-toolchain::
_Maintenance of FreeBSD's integrated
toolchain_
+
This is the mailing list for discussions related to the maintenance of the toolchain shipped with FreeBSD.
This could include the state of Clang and GCC, but also pieces of software such as assemblers, linkers and debuggers.

link:freebsd-transport::
_Discussions of transport level network
protocols in FreeBSD_
+
The transport mailing list exists for the discussion of issues and designs around the transport level protocols in the FreeBSD network stack, including TCP, SCTP and UDP.
Other networking topics, including driver specific and network protocol issues should be discussed on the link:FreeBSD networking mailing list.

link:freebsd-translators::
_Translating FreeBSD documents and
programs_
+
A discussion list where translators of FreeBSD documents from English into other languages can talk about translation methods and tools.
New members are asked to introduce themselves and mention the languages they are interested in translating.

link:freebsd-usb::
_Discussing FreeBSD support for
USB_
+
This is a mailing list for technical discussions related to FreeBSD support for USB.

link:freebsd-user-groups::
_User Group Coordination
List_
+
This is the mailing list for the coordinators from each of the local area Users Groups to discuss matters with each other and a designated individual from the Core Team.
This mail list should be limited to meeting synopsis and coordination of projects that span User Groups.

link:freebsd-virtualization::
_Discussion of various virtualization
techniques supported by FreeBSD_
+
A list to discuss the various virtualization techniques supported by FreeBSD.
On one hand the focus will be on the implementation of the basic functionality as well as adding new features.
On the other hand users will have a forum to ask for help in case of problems or to discuss their use cases.

link:freebsd-wip-status::
_FreeBSD Work-In-Progress
Status_
+
This mailing list can be used by developers to announce the creation and progress of FreeBSD related work.
Messages will be moderated.
It is suggested to send the message "To:" a more topical FreeBSD list and only "BCC:" this list.
This way the WIP can also be discussed on the topical list, as no discussion is allowed on this list.
+
Look inside the archives for examples of suitable messages.
+
An editorial digest of the messages to this list might be posted to the FreeBSD website every few months as part of the Status Reports footnote:[https://www.freebsd.org/news/status/]
.
Past reports are archived.

link:freebsd-wireless::
_Discussions of 802.11 stack, tools device
driver development_
+
The FreeBSD-wireless list focuses on 802.11 stack (sys/net80211), device driver and tools development.
This includes bugs, new features and maintenance.

link:freebsd-xen::
_Discussion of the FreeBSD port to Xen(TM)
-- implementation and usage_
+
A list that focuses on the FreeBSD Xen(TM)
port.
The anticipated traffic level is small enough that it is intended as a forum for both technical discussions of the implementation and design details as well as administrative deployment issues.

link:freebsd-xfce::
_XFCE_
+
This is a forum for discussions related to bring the [app]``XFCE`` environment to FreeBSD.
This is a technical mailing list.
It is for individuals actively working on porting [app]``XFCE`` to FreeBSD, to bring up problems or discuss alternative solutions.
Individuals interested in following the technical discussion are also welcome.

link:freebsd-zope::
_Zope_
+
This is a forum for discussions related to bring the [app]``Zope`` environment to FreeBSD.
This is a technical mailing list.
It is for individuals actively working on porting [app]``Zope`` to FreeBSD, to bring up problems or discuss alternative solutions.
Individuals interested in following the technical discussion are also welcome.


[[_eresources_mailfiltering]]
=== Filtering on the Mailing Lists


The FreeBSD mailing lists are filtered in multiple ways to avoid the distribution of spam, viruses, and other unwanted emails.
The filtering actions described in this section do not include all those used to protect the mailing lists.

Only certain types of attachments are allowed on the mailing lists.
All attachments with a MIME content type not found in the list below will be stripped before an email is distributed on the mailing lists.

* application/octet-stream
* application/pdf
* application/pgp-signature
* application/x-pkcs7-signature
* message/rfc822
* multipart/alternative
* multipart/related
* multipart/signed
* text/html
* text/plain
* text/x-diff
* text/x-patch


[NOTE]
====
Some of the mailing lists might allow attachments of other MIME content types, but the above list should be applicable for most of the mailing lists.
====


If an email contains both an HTML and a plain text version, the HTML version will be removed.
If an email contains only an HTML version, it will be converted to plain text.

[[_eresources_news]]
== Usenet Newsgroups


In addition to two FreeBSD specific newsgroups, there are many others in which FreeBSD is discussed or are otherwise relevant to FreeBSD users.

=== BSD Specific Newsgroups

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce]
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:de.comp.os.unix.bsd[de.comp.os.unix.bsd]	    (German)
* link:news:fr.comp.os.bsd[fr.comp.os.bsd]	    (French)


=== Other UNIX(R) Newsgroups of Interest

* link:news:comp.unix[comp.unix]
* link:news:comp.unix.questions[comp.unix.questions]
* link:news:comp.unix.admin[comp.unix.admin]
* link:news:comp.unix.programmer[comp.unix.programmer]
* link:news:comp.unix.shell[comp.unix.shell]
* link:news:comp.unix.misc[comp.unix.misc]
* link:news:comp.unix.bsd[comp.unix.bsd]


=== X Window System

* link:news:comp.windows.x[comp.windows.x]


[[_eresources_web]]
== Official Mirrors

<<_central_www,
Central Servers>>, <<_mirrors_am_www,Armenia>>, <<_mirrors_au_www,Australia>>, <<_mirrors_at_www,Austria>>, <<_mirrors_ca_www,Canada>>, <<_mirrors_cz_www,Czech Republic>>, <<_mirrors_dk_www,Denmark>>, <<_mirrors_fi_www,Finland>>, <<_mirrors_fr_www,France>>, <<_mirrors_de_www,Germany>>, <<_mirrors_hk_www,Hong Kong>>, <<_mirrors_ie_www,Ireland>>, <<_mirrors_jp_www,Japan>>, <<_mirrors_lv_www,Latvia>>, <<_mirrors_lt_www,Lithuania>>, <<_mirrors_nl_www,Netherlands>>, <<_mirrors_no_www,Norway>>, <<_mirrors_ru_www,Russia>>, <<_mirrors_si_www,Slovenia>>, <<_mirrors_za_www,South Africa>>, <<_mirrors_es_www,Spain>>, <<_mirrors_se_www,Sweden>>, <<_mirrors_ch_www,Switzerland>>, <<_mirrors_tw_www,Taiwan>>, <<_mirrors_uk_www,United Kingdom>>, <<_mirrors_us_www,USA>>.

(as of   UTC)

* {empty}
+[[_central_www]]
+
Central Servers
** http://www.FreeBSD.org/
* {empty}
+[[_mirrors_am_www]]
+
Armenia
** http://www1.am.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_au_www]]
+
Australia
** http://www.au.FreeBSD.org/
** http://www2.au.FreeBSD.org/
* {empty}
+[[_mirrors_at_www]]
+
Austria
** http://www.at.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_ca_www]]
+
Canada
** http://www.ca.FreeBSD.org/
** http://www2.ca.FreeBSD.org/
* {empty}
+[[_mirrors_cz_www]]
+
Czech Republic
** http://www.cz.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_dk_www]]
+
Denmark
** http://www.dk.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_fi_www]]
+
Finland
** http://www.fi.FreeBSD.org/
* {empty}
+[[_mirrors_fr_www]]
+
France
** http://www1.fr.FreeBSD.org/
* {empty}
+[[_mirrors_de_www]]
+
Germany
** http://www.de.FreeBSD.org/
* {empty}
+[[_mirrors_hk_www]]
+
Hong Kong
** http://www.hk.FreeBSD.org/
* {empty}
+[[_mirrors_ie_www]]
+
Ireland
** http://www.ie.FreeBSD.org/
* {empty}
+[[_mirrors_jp_www]]
+
Japan
** http://www.jp.FreeBSD.org/www.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_lv_www]]
+
Latvia
** http://www.lv.FreeBSD.org/
* {empty}
+[[_mirrors_lt_www]]
+
Lithuania
** http://www.lt.FreeBSD.org/
* {empty}
+[[_mirrors_nl_www]]
+
Netherlands
** http://www.nl.FreeBSD.org/
* {empty}
+[[_mirrors_no_www]]
+
Norway
** http://www.no.FreeBSD.org/
* {empty}
+[[_mirrors_ru_www]]
+
Russia
** http://www.ru.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_si_www]]
+
Slovenia
** http://www.si.FreeBSD.org/
* {empty}
+[[_mirrors_za_www]]
+
South Africa
** http://www.za.FreeBSD.org/
* {empty}
+[[_mirrors_es_www]]
+
Spain
** http://www.es.FreeBSD.org/
** http://www2.es.FreeBSD.org/
* {empty}
+[[_mirrors_se_www]]
+
Sweden
** http://www.se.FreeBSD.org/
* {empty}
+[[_mirrors_ch_www]]
+
Switzerland
** http://www.ch.FreeBSD.org/ (IPv6)
** http://www2.ch.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_tw_www]]
+
Taiwan
** http://www.tw.FreeBSD.org/
** http://www2.tw.FreeBSD.org/
** http://www4.tw.FreeBSD.org/
** http://www5.tw.FreeBSD.org/ (IPv6)
* {empty}
+[[_mirrors_uk_www]]
+
United Kingdom
** http://www1.uk.FreeBSD.org/
** http://www3.uk.FreeBSD.org/
* {empty}
+[[_mirrors_us_www]]
+
USA
** http://www5.us.FreeBSD.org/ (IPv6)


:sectnums: