---
title: "Mandatory Access Control"
---
[[_mac]]
= Mandatory Access Control
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
Tom Rhodes

[[_mac_synopsis]]
== Synopsis

(((MAC)))

(((Mandatory Access Control)))


FreeBSD supports security extensions  based on the POSIX(R).1e draft.
These security mechanisms include file system Access Control Lists (<<_fs_acl>>) and Mandatory Access Control ([acronym]``MAC``).  [acronym]``MAC`` allows access control modules to be loaded in order to implement security policies.
Some modules provide protections for a narrow subset of the system, hardening a particular service.
Others provide comprehensive labeled security across all subjects and objects.
The mandatory part of the definition indicates that enforcement of controls is performed by administrators and the operating system.
This is in contrast to the default security mechanism of Discretionary Access Control ([acronym]``DAC``) where enforcement is left to the discretion of users.

This chapter focuses on the [acronym]``MAC`` framework and the set of pluggable security policy modules FreeBSD provides for enabling various security mechanisms.

After reading this chapter, you will know:

* The terminology associated with the [acronym]``MAC`` framework.
* The capabilities of [acronym]``MAC`` security policy modules as well as the difference between a labeled and non-labeled policy.
* The considerations to take into account before configuring a system to use the [acronym]``MAC`` framework.
* Which [acronym]``MAC`` security policy modules are included in FreeBSD and how to configure them.
* How to implement a more secure environment using the [acronym]``MAC`` framework.
* How to test the [acronym]``MAC`` configuration to ensure the framework has been properly implemented.


Before reading this chapter, you should:

* Understand UNIX(R) and FreeBSD basics (<<_basics>>).
* Have some familiarity with security and how it pertains to FreeBSD (<<_security>>).


[WARNING]
====
Improper [acronym]``MAC`` configuration may cause loss of system access, aggravation of users, or inability to access the features provided by [app]``Xorg``.
More importantly, [acronym]``MAC`` should not be relied upon to completely secure a system.
The [acronym]``MAC`` framework only augments an existing security policy.
Without sound security practices and regular security checks, the system will never be completely secure.

The examples contained within this chapter are for demonstration purposes and the example settings should _not_ be implemented on a production system.
Implementing any security policy takes a good deal of understanding, proper design, and thorough testing.
====


While this chapter covers a broad range of security issues relating to the [acronym]``MAC`` framework, the development of new [acronym]``MAC`` security policy modules will not be covered.
A number of security policy modules included with the [acronym]``MAC`` framework have specific characteristics which are provided for both testing and new module development.
Refer to  {{< manpage "mac_test" "4" >}}
,  {{< manpage "mac_stub" "4" >}}
 and  {{< manpage "mac_none" "4" >}}
 for more information on these security policy modules and the various mechanisms they provide.

[[_mac_inline_glossary]]
== Key Terms


The following key terms are used when referring to the [acronym]``MAC`` framework:

* __compartment__: a set of programs and data to be partitioned or separated, where users are given explicit access to specific component of a system. A compartment represents a grouping, such as a work group, department, project, or topic. Compartments make it possible to implement a need-to-know-basis security policy.
* __integrity__: the level of trust which can be placed on data. As the integrity of the data is elevated, so does the ability to trust that data.
* __level__: the increased or decreased setting of a security attribute. As the level increases, its security is considered to elevate as well.
* __label__: a security attribute which can be applied to files, directories, or other items in the system. It could be considered a confidentiality stamp. When a label is placed on a file, it describes the security properties of that file and will only permit access by files, users, and resources with a similar security setting. The meaning and interpretation of label values depends on the policy configuration. Some policies treat a label as representing the integrity or secrecy of an object while other policies might use labels to hold rules for access.
* __multilabel__: this property is a file system option which can be set in single-user mode using  {{< manpage "tunefs" "8" >}} , during boot using  {{< manpage "fstab" "5" >}} , or during the creation of a new file system. This option permits an administrator to apply different [acronym]``MAC``	  labels on different objects. This option only applies to security policy modules which support labeling.
* __single label__: a policy where the entire file system uses one label to enforce access control over the flow of data. Whenever [option]``multilabel``	  is not set, all files will conform to the same label setting.
* __object__: an entity through which information flows under the direction of a __subject__. This includes directories, files, fields, screens, keyboards, memory, magnetic storage, printers or any other data storage or moving device. An object is a data container or a system resource. Access to an object effectively means access to its data.
* __subject__: any active entity that causes information to flow between _objects_ such as a user, user process, or system process. On FreeBSD, this is almost always a thread acting in a process on behalf of a user.
* __policy__: a collection of rules which defines how objectives are to be achieved. A policy usually documents how certain items are to be handled. This chapter considers a policy to be a collection of rules which controls the flow of data and information and defines who has access to that data and information.
* __high-watermark__: this type of policy permits the raising of security levels for the purpose of accessing higher level information. In most cases, the original level is restored after the process is complete. Currently, the FreeBSD [acronym]``MAC``	  framework does not include this type of policy.
* __low-watermark__: this type of policy permits lowering security levels for the purpose of accessing information which is less secure. In most cases, the original security level of the user is restored after the process is complete. The only security policy module in FreeBSD to use this is  {{< manpage "mac_lomac" "4" >}} .
* __sensitivity__: usually used when discussing Multilevel Security ([acronym]``MLS``).  A sensitivity level describes how important or secret the data should be. As the sensitivity level increases, so does the importance of the secrecy, or confidentiality, of the data.


[[_mac_understandlabel]]
== Understanding MAC Labels


A [acronym]``MAC`` label is a security attribute which may be applied to subjects and objects throughout the system.
When setting a label, the administrator must understand its implications in order to prevent unexpected or undesired behavior of the system.
The attributes available on an object depend on the loaded policy module, as policy modules interpret their attributes in different ways.

The security label on an object is used as a part of a security access control decision by a policy.
With some policies, the label contains all of the information necessary to make a decision.
In other policies, the labels may be processed as part of a larger rule set.

There are two types of label policies: single label and multi label.
By default, the system will use single label.
The administrator should be aware of the pros and cons of each in order to implement policies which meet the requirements of the system's security model.

A single label security policy only permits one label to be used for every subject or object.
Since a single label policy enforces one set of access permissions across the entire system, it provides lower administration overhead, but decreases the flexibility of policies which support labeling.
However, in many environments, a single label policy may be all that is required.

A single label policy is somewhat similar to [acronym]``DAC`` as [username]``root``
 configures the policies so that users are placed in the appropriate categories and access levels.
A notable difference is that many policy modules can also restrict [username]``root``
.
Basic control over objects will then be released to the group, but [username]``root``
 may revoke or modify the settings at any time.

When appropriate, a multi label policy can be set on a [acronym]``UFS`` file system by passing [option]``multilabel`` to  {{< manpage "tunefs" "8" >}}
.
A multi label policy permits each subject or object to have its own independent [acronym]``MAC`` label.
The decision to use a multi label or single label policy is only required for policies which implement the labeling feature, such as ``biba``, ``lomac``, and ``mls``.
Some policies, such as ``seeotheruids``, `portacl` and ``partition``, do not use labels at all.

Using a multi label policy on a partition and establishing a multi label security model can increase administrative overhead as everything in that file system has a label.
This includes directories, files, and even device nodes.

The following command will set [option]``multilabel`` on the specified [acronym]``UFS`` file system.
This may only be done in single-user mode and is not a requirement for the swap file system:

----
# tunefs -l enable /
----

[NOTE]
====
Some users have experienced problems with setting the [option]``multilabel`` flag on the root partition.
If this is the case, please review <<_mac_troubleshoot>>.
====


Since the multi label policy is set on a per-file system basis, a multi label policy may not be needed if the file system layout is well designed.
Consider an example security [acronym]``MAC`` model for a FreeBSD web server.
This machine uses the single label, ``biba/high``, for everything in the default file systems.
If the web server needs to run at `biba/low` to prevent write up capabilities, it could be installed to a separate [acronym]``UFS``[path]``/usr/local``
 file system set at ``biba/low``.

=== Label Configuration


Virtually all aspects of label policy module configuration will be performed using the base system utilities.
These commands provide a simple interface for object or subject configuration or the manipulation and verification of the configuration.

All configuration may be done using [command]``setfmac``, which is used to set [acronym]``MAC`` labels on system objects, and [command]``setpmac``, which is used to set the labels on system subjects.
For example, to set the `biba`[acronym]``MAC`` label to `high` on [path]``test``
:

----
# setfmac biba/high test
----


If the configuration is successful, the prompt will be returned without error.
A common error is `Permission denied` which usually occurs when the label is being set or modified on a restricted object.
Other conditions may produce different failures.
For instance, the file may not be owned by the user attempting to relabel the object, the object may not exist, or the object may be read-only.
A mandatory policy will not allow the process to relabel the file, maybe because of a property of the file, a property of the process, or a property of the proposed new label value.
For example, if a user running at low integrity tries to change the label of a high integrity file, or a user running at low integrity tries to change the label of a low integrity file to a high integrity label, these operations will fail.

The system administrator may use [command]``setpmac`` to override the policy module's settings by assigning a different label to the invoked process:

----
# setfmac biba/high test
# setpmac biba/low setfmac biba/high test
# getfmac testtest: biba/high
----


For currently running processes, such as [app]``sendmail``, [command]``getpmac`` is usually used instead.
This command takes a process ID ([acronym]``PID``) in place of a command name.
If users attempt to manipulate a file not in their access, subject to the rules of the loaded policy modules, the `Operation not permitted`	error will be displayed.

=== Predefined Labels


A few FreeBSD policy modules which support the labeling feature offer three predefined labels: ``low``, ``equal``, and ``high``, where:

* `low` is considered the lowest label setting an object or subject may have. Setting this on objects or subjects blocks their access to objects or subjects marked high.
* `equal` sets the subject or object to be disabled or unaffected and should only be placed on objects considered to be exempt from the policy.
* `high` grants an object or subject the highest setting available in the Biba and [acronym]``MLS`` policy modules.


Such policy modules include  {{< manpage "mac_biba" "4" >}}
,  {{< manpage "mac_mls" "4" >}}
 and  {{< manpage "mac_lomac" "4" >}}
.
Each of the predefined labels establishes a different information flow directive.
Refer to the manual page of the module to determine the traits of the generic label configurations.

=== Numeric Labels


The Biba and [acronym]``MLS`` policy modules support a numeric label which may be set to indicate the precise level of hierarchical control.
This numeric level is used to partition or sort information into different groups of classification, only permitting access to that group or a higher group level.
For example:

[source]
----
biba/10:2+3+6(5:2+3-20:2+3+4+5+6)
----


may be interpreted as "`Biba Policy Label/Grade
	  10:Compartments 2, 3 and 6: (grade 5 ...`"
)

In this example, the first grade would be considered the effective grade with effective compartments, the second grade is the low grade, and the last one is the high grade.
In most configurations, such fine-grained settings are not needed as they are considered to be advanced configurations.

System objects only have a current grade and compartment.
System subjects reflect the range of available rights in the system, and network interfaces, where they are used for access control.

The grade and compartments in a subject and object pair are used to construct a relationship known as [term]_dominance_
, in which a subject dominates an object, the object dominates the subject, neither dominates the other, or both dominate each other.
The "`both
	  dominate`"
 case occurs when the two labels are equal.
Due to the information flow nature of Biba, a user has rights to a set of compartments that might correspond to projects, but objects also have a set of compartments.
Users may have to subset their rights using [command]``su`` or [command]``setpmac`` in order to access objects in a compartment from which they are not restricted.

=== User Labels


Users are required to have labels so that their files and processes properly interact with the security policy defined on the system.
This is configured in [path]``/etc/login.conf``
 using login classes.
Every policy module that uses labels will implement the user class setting.

To set the user class default label which will be enforced by [acronym]``MAC``, add a [option]``label`` entry.
An example [option]``label`` entry containing every policy module is displayed below.
Note that in a real configuration, the administrator would never enable every policy module.
It is recommended that the rest of this chapter be reviewed before any configuration is implemented.

[source]
----
default:\
	:copyright=/etc/COPYRIGHT:\
	:welcome=/etc/motd:\
	:setenv=MAIL=/var/mail/$,BLOCKSIZE=K:\
	:path=~/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:\
	:manpath=/usr/share/man /usr/local/man:\
	:nologin=/usr/sbin/nologin:\
	:cputime=1h30m:\
	:datasize=8M:\
	:vmemoryuse=100M:\
	:stacksize=2M:\
	:memorylocked=4M:\
	:memoryuse=8M:\
	:filesize=8M:\
	:coredumpsize=8M:\
	:openfiles=24:\
	:maxproc=32:\
	:priority=0:\
	:requirehome:\
	:passwordtime=91d:\
	:umask=022:\
	:ignoretime@:\
	:label=partition/13,mls/5,biba/10(5-15),lomac/10[2]:
----


While users can not modify the default value, they may change their label after they login, subject to the constraints of the policy.
The example above tells the Biba policy that a process's minimum integrity is ``5``, its maximum is ``15``, and the default effective label is ``10``.
The process will run at `10` until it chooses to change label, perhaps due to the user using [command]``setpmac``, which will be constrained by Biba to the configured range.

After any change to [path]``login.conf``
, the login class capability database must be rebuilt using [command]``cap_mkdb``.

Many sites have a large number of users requiring several different user classes.
In depth planning is required as this can become difficult to manage.

=== Network Interface Labels


Labels may be set on network interfaces to help control the flow of data across the network.
Policies using network interface labels function in the same way that policies function with respect to objects.
Users at high settings in Biba, for example, will not be permitted to access network interfaces with a label of ``low``.

When setting the [acronym]``MAC`` label on network interfaces, [option]``maclabel`` may be passed to [command]``ifconfig``:

----
# ifconfig bge0 maclabel biba/equal
----


This example will set the [acronym]``MAC`` label of `biba/equal` on the `bge0`	interface.
When using a setting similar to ``biba/high(low-high)``, the entire label should be quoted to prevent an error from being returned.

Each policy module which supports labeling has a tunable which may be used to disable the [acronym]``MAC`` label on network interfaces.
Setting the label to [option]``equal`` will have a similar effect.
Review the output of [command]``sysctl``, the policy manual pages, and the information in the rest of this chapter for more information on those tunables.

[[_mac_planning]]
== Planning the Security Configuration


Before implementing any [acronym]``MAC`` policies, a planning phase is recommended.
During the planning stages, an administrator should consider the implementation requirements and goals, such as:

* How to classify information and resources available on the target systems.
* Which information or resources to restrict access to along with the type of restrictions that should be applied.
* Which [acronym]``MAC`` modules will be required to achieve this goal.


A trial run of the trusted system and its configuration should occur _before_ a [acronym]``MAC`` implementation is used on production systems.
Since different environments have different needs and requirements, establishing a complete security profile will decrease the need of changes once the system goes live.

Consider how the [acronym]``MAC`` framework augments the security of the system as a whole.
The various security policy modules provided by the [acronym]``MAC`` framework could be used to protect the network and file systems or to block users from accessing certain ports and sockets.
Perhaps the best use of the policy modules is to load several security policy modules at a time in order to provide a [acronym]``MLS`` environment.
This approach differs from a hardening policy, which typically hardens elements of a system which are used only for specific purposes.
The downside to [acronym]``MLS`` is increased administrative overhead.

The overhead is minimal when compared to the lasting effect of a framework which provides the ability to pick and choose which policies are required for a specific configuration and which keeps performance overhead down.
The reduction of support for unneeded policies can increase the overall performance of the system as well as offer flexibility of choice.
A good implementation would consider the overall security requirements and effectively implement the various security policy modules offered by the framework.

A system utilizing [acronym]``MAC`` guarantees that a user will not be permitted to change security attributes at will.
All user utilities, programs, and scripts must work within the constraints of the access rules provided by the selected security policy modules and control of the [acronym]``MAC`` access rules is in the hands of the system administrator.

It is the duty of the system administrator to carefully select the correct security policy modules.
For an environment that needs to limit access control over the network, the  {{< manpage "mac_portacl" "4" >}}
,  {{< manpage "mac_ifoff" "4" >}}
, and  {{< manpage "mac_biba" "4" >}}
 policy modules make good starting points.
For an environment where strict confidentiality of file system objects is required, consider the  {{< manpage "mac_bsdextended" "4" >}}
 and  {{< manpage "mac_mls" "4" >}}
 policy modules.

Policy decisions could be made based on network configuration.
If only certain users should be permitted access to  {{< manpage "ssh" "1" >}}
, the  {{< manpage "mac_portacl" "4" >}}
 policy module is a good choice.
In the case of file systems, access to objects might be considered confidential to some users, but not to others.
As an example, a large development team might be broken off into smaller projects where  developers in project A might not be permitted to access objects written by developers in project B.
Yet both projects might need to access objects created by developers in project C.
Using the different security policy modules provided by the [acronym]``MAC`` framework, users could be divided into these groups and then given access to the appropriate objects.

Each security policy module has a unique way of dealing with the overall security of a system.
Module selection should be based on a well thought out security policy which may require revision and reimplementation.
Understanding the different security policy modules offered by the [acronym]``MAC`` framework will help administrators choose the best policies for their situations.

The rest of this chapter covers the available modules, describes their use and configuration, and in some cases, provides insight on applicable situations.

[CAUTION]
====
Implementing [acronym]``MAC`` is much like implementing a firewall since care must be taken to prevent being completely locked out of the system.
The ability to revert back to a previous configuration should be considered and the implementation of [acronym]``MAC`` over a remote connection should be done with extreme caution.
====

[[_mac_policies]]
== Available MAC Policies


The default FreeBSD kernel includes ``options MAC``.
This means that every module included with the [acronym]``MAC`` framework can be loaded with [command]``kldload`` as a run-time kernel module.
After testing the module, add the module name to [path]``/boot/loader.conf``
 so that it will load during boot.
Each module also provides a kernel option for those administrators who choose to compile their own custom kernel.

FreeBSD includes a group of policies that will cover most security requirements.
Each policy is summarized below.
The last three policies support integer settings in place of the three default labels.

[[_mac_seeotheruids]]
=== The MAC See Other UIDs Policy

(((MAC See Other UIDs Policy)))


Module name: [path]``mac_seeotheruids.ko``

Kernel configuration line: `options MAC_SEEOTHERUIDS`

Boot option: `mac_seeotheruids_load="YES"`

The  {{< manpage "mac_seeotheruids" "4" >}}
 module extends the [var]``security.bsd.see_other_uids`` and [var]``security.bsd.see_other_gids``[command]``sysctl`` tunables.
This option does not require any labels to be set before configuration and can operate transparently with other modules.

After loading the module, the following [command]``sysctl`` tunables may be used to control its features:

* [var]``security.mac.seeotheruids.enabled``	    enables the module and implements the default settings which deny users the ability to view processes and sockets owned by other users.
* [var]``security.mac.seeotheruids.specificgid_enabled``	    allows specified groups to be exempt from this policy. To exempt specific groups, use the [var]``security.mac.seeotheruids.specificgid=[replaceable]``XXX````[command]``sysctl`` tunable, replacing [replaceable]``XXX`` with the numeric group ID to be exempted.
* [var]``security.mac.seeotheruids.primarygroup_enabled``	    is used to exempt specific primary groups from this policy. When using this tunable, [var]``security.mac.seeotheruids.specificgid_enabled``	    may not be set.


[[_mac_bsdextended]]
=== The MAC BSD Extended Policy

(((MAC,File System Firewall Policy)))


Module name: [path]``mac_bsdextended.ko``

Kernel configuration line: `options MAC_BSDEXTENDED`

Boot option: `mac_bsdextended_load="YES"`

The  {{< manpage "mac_bsdextended" "4" >}}
 module enforces a file system firewall.
It provides an extension to the standard file system permissions model, permitting an administrator to create a firewall-like ruleset to protect files, utilities, and directories in the file system hierarchy.
When access to a file system object is attempted, the list of rules is iterated until either a matching rule is located or the end is reached.
This behavior may be changed using [var]``security.mac.bsdextended.firstmatch_enabled``.
Similar to other firewall modules in FreeBSD, a file containing the access control rules can be created and read by the system at boot time using an  {{< manpage "rc.conf" "5" >}}
 variable.

The rule list may be entered using  {{< manpage "ugidfw" "8" >}}
 which has a syntax similar to  {{< manpage "ipfw" "8" >}}
.
More tools can be written by using the functions in the  {{< manpage "libugidfw" "3" >}}
	library.

After the  {{< manpage "mac_bsdextended" "4" >}}
 module has been loaded, the following command may be used to list the current rule configuration:

----
# ugidfw list0 slots, 0 rules
----


By default, no rules are defined and everything is completely accessible.
To create a rule which blocks all access by users but leaves [username]``root``
 unaffected:

----
# ugidfw add subject not uid root new object not uid root mode n
----


While this rule is simple to implement, it is a very bad idea as it blocks all users from issuing any commands.
A more realistic example blocks [username]``user1``
 all access, including directory listings, to [username]``user2``
's home directory:

----
# ugidfw set 2 subject uid user1 object uid user2 mode n
# ugidfw set 3 subject uid user1 object gid user2 mode n
----


Instead of [username]``user1``
, [option]``not
	  uid [replaceable]``user2```` could be used in order to enforce the same access restrictions for all users.
However, the [username]``root``
 user is unaffected by these rules.

[NOTE]
====
Extreme caution should be taken when working with this module as incorrect use could block access to certain parts of the file system.
====

[[_mac_ifoff]]
=== The MAC Interface Silencing Policy


Module name: [path]``mac_ifoff.ko``

Kernel configuration line: `options
	  MAC_IFOFF`

Boot option: `mac_ifoff_load="YES"`

The  {{< manpage "mac_ifoff" "4" >}}
 module is used to disable network interfaces on the fly and to keep network interfaces from being brought up during system boot.
It does not use labels and does not depend on any other [acronym]``MAC`` modules.

Most of this module's control is performed through these [command]``sysctl`` tunables:

* [var]``security.mac.ifoff.lo_enabled``	    enables or disables all traffic on the loopback,  {{< manpage "lo" "4" >}} , interface.
* [var]``security.mac.ifoff.bpfrecv_enabled``	    enables or disables all traffic on the Berkeley Packet Filter interface,  {{< manpage "bpf" "4" >}} .
* [var]``security.mac.ifoff.other_enabled``	    enables or disables traffic on all other interfaces.


One of the most common uses of  {{< manpage "mac_ifoff" "4" >}}
 is network monitoring in an environment where network traffic should not be permitted during the boot sequence.
Another use would be to write a script which uses an application such as [package]#security/aide#
 to automatically block network traffic if it finds new or altered files in protected directories.

[[_mac_portacl]]
=== The MAC Port Access Control List Policy

(((MAC Port Access Control List Policy)))


Module name: [path]``mac_portacl.ko``

Kernel configuration line: `MAC_PORTACL`

Boot option: `mac_portacl_load="YES"`

The  {{< manpage "mac_portacl" "4" >}}
 module is used to limit binding to local [acronym]``TCP`` and [acronym]``UDP`` ports, making it possible to allow non-[username]``root``
 users to bind to specified privileged ports below 1024.

Once loaded, this module enables the [acronym]``MAC`` policy on all sockets.
The following tunables are available:

* [var]``security.mac.portacl.enabled``	    enables or disables the policy completely.
* [var]``security.mac.portacl.port_high``	    sets the highest port number that  {{< manpage "mac_portacl" "4" >}} protects.
* [var]``security.mac.portacl.suser_exempt``, when set to a non-zero value, exempts the [username]``root`` user from this policy.
* [var]``security.mac.portacl.rules``	    specifies the policy as a text string of the form ``rule[,rule,...]``, with as many rules as needed, and where each rule is of the form ``idtype:id:protocol:port``. The [parameter]``idtype`` is either `uid` or ``gid``. The [parameter]``protocol`` parameter can be `tcp` or ``udp``. The [parameter]``port`` parameter is the port number to allow the specified user or group to bind to. Only numeric values can be used for the user ID, group ID, and port parameters.


By default, ports below 1024 can only be used by privileged processes which run as [username]``root``
.
For  {{< manpage "mac_portacl" "4" >}}
	to allow non-privileged processes to bind to ports below 1024, set the following tunables as follows:

----
# sysctl security.mac.portacl.port_high=1023
# sysctl net.inet.ip.portrange.reservedlow=0
# sysctl net.inet.ip.portrange.reservedhigh=0
----


To prevent the [username]``root``
 user from being affected by this policy, set [var]``security.mac.portacl.suser_exempt`` to a non-zero value.

----
# sysctl security.mac.portacl.suser_exempt=1
----


To allow the [username]``www``
	user with [acronym]``UID`` 80 to bind to port 80 without ever needing [username]``root``
 privilege:

----
# sysctl security.mac.portacl.rules=uid:80:tcp:80
----


This next example permits the user with the [acronym]``UID`` of 1001 to bind to [acronym]``TCP`` ports 110 (POP3) and 995 (POP3s):

----
# sysctl security.mac.portacl.rules=uid:1001:tcp:110,uid:1001:tcp:995
----

[[_mac_partition]]
=== The MAC Partition Policy

(((MAC Process Partition Policy)))


Module name: [path]``mac_partition.ko``

Kernel configuration line: `options MAC_PARTITION`

Boot option: `mac_partition_load="YES"`

The  {{< manpage "mac_partition" "4" >}}
 policy drops processes into specific "`partitions`"
 based on their [acronym]``MAC`` label.
Most configuration for this policy is done using  {{< manpage "setpmac" "8" >}}
.
One [command]``sysctl`` tunable is available for this policy:

* [var]``security.mac.partition.enabled``	    enables the enforcement of [acronym]``MAC`` process partitions.


When this policy is enabled, users will only be permitted to see their processes, and any others within their partition, but will not be permitted to work with utilities outside the scope of this partition.
For instance, a user in the `insecure` class will not be permitted to access [command]``top`` as well as many other commands that must spawn a process.

This example adds [command]``top`` to the label set on users in the `insecure` class.
All processes spawned by users in the `insecure`	class will stay in the `partition/13`	label.

----
# setpmac partition/13 top
----


This command displays the partition label and the process list:

----
# ps Zax
----


This command displays another user's process partition label and that user's currently running processes:

----
# ps -ZU trhodes
----

[NOTE]
====
Users can see processes in [username]``root``
's label unless the  {{< manpage "mac_seeotheruids" "4" >}}
 policy is loaded.
====

[[_mac_mls]]
=== The MAC Multi-Level Security Module

(((MAC Multi-Level Security Policy)))


Module name: [path]``mac_mls.ko``

Kernel configuration line: `options MAC_MLS`

Boot option: `mac_mls_load="YES"`

The  {{< manpage "mac_mls" "4" >}}
 policy controls access between subjects and objects in the system by enforcing a strict information flow policy.

In [acronym]``MLS`` environments, a "`clearance`"
 level is set in the label of each subject or object, along with compartments.
Since these clearance levels can reach numbers greater than several thousand, it would be a daunting task to thoroughly configure every subject or object.
To ease this administrative overhead, three labels are included in this policy: ``mls/low``, ``mls/equal``, and ``mls/high``, where:

* Anything labeled with `mls/low` will have a low clearance level and not be permitted to access information of a higher level. This label also prevents objects of a higher clearance level from writing or passing information to a lower level.
* `mls/equal` should be placed on objects which should be exempt from the policy.
* `mls/high` is the highest level of clearance possible. Objects assigned this label will hold dominance over all other objects in the system; however, they will not permit the leaking of information to objects of a lower class.

[acronym]``
MLS`` provides:

* A hierarchical security level with a set of non-hierarchical categories.
* Fixed rules of ``no read up, no write down``. This means that a subject can have read access to objects on its own level or below, but not above. Similarly, a subject can have write access to objects on its own level or above, but not beneath.
* Secrecy, or the prevention of inappropriate disclosure of data.
* A basis for the design of systems that concurrently handle data at multiple sensitivity levels without leaking information between secret and confidential.


The following [command]``sysctl`` tunables are available:

* [var]``security.mac.mls.enabled`` is used to enable or disable the [acronym]``MLS``	    policy.
* [var]``security.mac.mls.ptys_equal``	    labels all  {{< manpage "pty" "4" >}} devices as `mls/equal` during creation.
* [var]``security.mac.mls.revocation_enabled``	    revokes access to objects after their label changes to a label of a lower grade.
* [var]``security.mac.mls.max_compartments``	    sets the maximum number of compartment levels allowed on a system.


To manipulate [acronym]``MLS`` labels, use  {{< manpage "setfmac" "8" >}}
.
To assign a label to an object:

----
# setfmac mls/5 test
----


To get the [acronym]``MLS`` label for the file [path]``test``
:

----
# getfmac test
----


Another approach is to create a master policy file in [path]``/etc/``
 which specifies the [acronym]``MLS`` policy information and to feed that file to [command]``setfmac``.

When using the [acronym]``MLS`` policy module, an administrator plans to control the flow of sensitive information.
The default `block read up block write
	  down` sets everything to a low state.
Everything is accessible and an administrator slowly augments the confidentiality of the information.

Beyond the three basic label options, an administrator may group users and groups as required to block the information flow between them.
It might be easier to look at the information in clearance levels using descriptive words, such as classifications of ``Confidential``, ``Secret``, and ``Top Secret``.
Some administrators instead create different groups based on project levels.
Regardless of the classification method, a well thought out plan must exist before implementing a restrictive policy.

Some example situations for the [acronym]``MLS``	policy module include an e-commerce web server, a file server holding critical company information, and financial institution environments.

[[_mac_biba]]
=== The MAC Biba Module

(((MAC Biba Integrity Policy)))


Module name: [path]``mac_biba.ko``

Kernel configuration line: `options
	  MAC_BIBA`

Boot option: `mac_biba_load="YES"`

The  {{< manpage "mac_biba" "4" >}}
 module loads the [acronym]``MAC`` Biba policy.
This policy is similar to the [acronym]``MLS`` policy with the exception that the rules for information flow are slightly reversed.
This is to prevent the downward flow of sensitive information whereas the [acronym]``MLS`` policy prevents the upward flow of sensitive information.

In Biba environments, an "`integrity`"
 label is set on each subject or object.
These labels are made up of hierarchical grades and non-hierarchical components.
As a grade ascends, so does its integrity.

Supported labels are ``biba/low``, ``biba/equal``, and ``biba/high``, where:

* `biba/low` is considered the lowest integrity an object or subject may have. Setting this on objects or subjects blocks their write access to objects or subjects marked as ``biba/high``, but will not prevent read access.
* `biba/equal` should only be placed on objects considered to be exempt from the policy.
* `biba/high` permits writing to objects set at a lower label, but does not permit reading that object. It is recommended that this label be placed on objects that affect the integrity of the entire system.


Biba provides:

* Hierarchical integrity levels with a set of non-hierarchical integrity categories.
* Fixed rules are ``no write up, no read down``, the opposite of [acronym]``MLS``. A subject can have write access to objects on its own level or below, but not above. Similarly, a subject can have read access to objects on its own level or above, but not below.
* Integrity by preventing inappropriate modification of data.
* Integrity levels instead of [acronym]``MLS``	    sensitivity levels.


The following tunables can be used to manipulate the Biba policy:

* [var]``security.mac.biba.enabled`` is used to enable or disable enforcement of the Biba policy on the target machine.
* [var]``security.mac.biba.ptys_equal`` is used to disable the Biba policy on  {{< manpage "pty" "4" >}} devices.
* [var]``security.mac.biba.revocation_enabled``	    forces the revocation of access to objects if the label is changed to dominate the subject.


To access the Biba policy setting on system objects, use [command]``setfmac`` and [command]``getfmac``:

----
# setfmac biba/low test
# getfmac testtest: biba/low
----


Integrity, which is different from sensitivity, is used to guarantee that information is not manipulated by untrusted parties.
This includes information passed between subjects and objects.
It ensures that users will only be able to modify or access information they have been given explicit access to.
The  {{< manpage "mac_biba" "4" >}}
 security policy module permits an administrator to configure which files and programs a user may see and invoke while assuring that the programs and files are trusted by the system for that user.

During the initial planning phase, an administrator must be prepared to partition users into grades, levels, and areas.
The system will default to a high label once this policy module is enabled, and it is up to the administrator to configure the different grades and levels for users.
Instead of using clearance levels, a good planning method could include topics.
For instance, only allow developers modification access to the source code repository, source code compiler, and other development utilities.
Other users would be grouped into other categories such as testers, designers, or end users and would only be permitted read access.

A lower integrity subject is unable to write to a higher integrity subject and a higher integrity subject cannot list or read a lower integrity object.
Setting a label at the lowest possible grade could make it inaccessible to subjects.
Some prospective environments for this security policy module would include a constrained web server, a development and test machine, and a source code repository.
A less useful implementation would be a personal workstation, a machine used as a router, or a network firewall.

[[_mac_lomac]]
=== The MAC Low-watermark Module

(((MAC LOMAC)))


Module name: [path]``mac_lomac.ko``

Kernel configuration line: `options
	  MAC_LOMAC`

Boot option: `mac_lomac_load="YES"`

Unlike the [acronym]``MAC`` Biba policy, the  {{< manpage "mac_lomac" "4" >}}
 policy permits access to lower integrity objects only after decreasing the integrity level to not disrupt any integrity rules.

The Low-watermark integrity policy works almost identically to Biba, with the exception of using floating labels to support subject demotion via an auxiliary grade compartment.
This secondary compartment takes the form ``[auxgrade]``.
When assigning a policy with an auxiliary grade, use the syntax ``lomac/10[2]``, where `2` is the auxiliary grade.

This policy relies on the ubiquitous labeling of all system objects with integrity labels, permitting subjects to read from low integrity objects and then downgrading the label on the subject to prevent future writes to high integrity objects using ``[auxgrade]``.
The policy may provide greater compatibility and require less initial configuration than Biba.

Like the Biba and [acronym]``MLS`` policies, [command]``setfmac`` and [command]``setpmac``	are used to place labels on system objects:

----
# setfmac /usr/home/trhodes lomac/high[low]
# getfmac /usr/home/trhodes lomac/high[low]
----


The auxiliary grade `low` is a feature provided only by the [acronym]``MAC``[acronym]``LOMAC`` policy.

[[_mac_userlocked]]
== User Lock Down


This example considers a relatively small storage system with fewer than fifty users.
Users will have login capabilities and are permitted to store data and access resources.

For this scenario, the  {{< manpage "mac_bsdextended" "4" >}}
 and  {{< manpage "mac_seeotheruids" "4" >}}
 policy modules could co-exist and block access to system objects while hiding user processes.

Begin by adding the following line to [path]``/boot/loader.conf``
:

[source]
----
mac_seeotheruids_load="YES"
----


The  {{< manpage "mac_bsdextended" "4" >}}
 security policy module may be activated by adding this line to [path]``/etc/rc.conf``
:

[source]
----
ugidfw_enable="YES"
----


Default rules stored in [path]``/etc/rc.bsdextended``
 will be loaded at system initialization.
However, the default entries may need modification.
Since this machine is expected only to service users, everything may be left commented out except the last two lines in order to force the loading of user owned system objects by default.

Add the required users to this machine and reboot.
For testing purposes, try logging in as a different user across two consoles.
Run [command]``ps aux`` to see if processes of other users are visible.
Verify that running  {{< manpage "ls" "1" >}}
 on another user's home directory fails.

Do not try to test with the [username]``root``
 user unless the specific [command]``sysctl``s have been modified to block super user access.

[NOTE]
====
When a new user is added, their  {{< manpage "mac_bsdextended" "4" >}}
	rule will not be in the ruleset list.
To update the ruleset quickly, unload the security policy module and reload it again using  {{< manpage "kldunload" "8" >}}
 and  {{< manpage "kldload" "8" >}}
.
====

[[_mac_implementing]]
== Nagios in a MAC Jail

(((Nagios in a MAC Jail)))


This section demonstrates the steps that are needed to implement the [app]``Nagios`` network monitoring system in a [acronym]``MAC`` environment.
This is meant as an example which still requires the administrator to test that the implemented policy meets the security requirements of the network before using in a production environment.

This example requires [option]``multilabel`` to be set on each file system.
It also assumes that [package]#net-mgmt/nagios-plugins#
, [package]#net-mgmt/nagios#
, and [package]#www/apache22#
 are all installed, configured, and working correctly before attempting the integration into the [acronym]``MAC`` framework.

=== Create an Insecure User Class


Begin the procedure by adding the following user class to [path]``/etc/login.conf``
:

[source]
----
insecure:\
:copyright=/etc/COPYRIGHT:\
:welcome=/etc/motd:\
:setenv=MAIL=/var/mail/$,BLOCKSIZE=K:\
:path=~/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
:manpath=/usr/share/man /usr/local/man:\
:nologin=/usr/sbin/nologin:\
:cputime=1h30m:\
:datasize=8M:\
:vmemoryuse=100M:\
:stacksize=2M:\
:memorylocked=4M:\
:memoryuse=8M:\
:filesize=8M:\
:coredumpsize=8M:\
:openfiles=24:\
:maxproc=32:\
:priority=0:\
:requirehome:\
:passwordtime=91d:\
:umask=022:\
:ignoretime@:\
:label=biba/10(10-10):
----


Then, add the following line to the default user class section:

[source]
----
:label=biba/high:
----


Save the edits and issue the following command to rebuild the database:

----
# cap_mkdb /etc/login.conf
----

=== Configure Users


Set the [username]``root``
	user to the default class using:

----
# pw usermod root -L default
----


All user accounts that are not [username]``root``
 will now require a login class.
The login class is required, otherwise users will be refused access to common commands.
The following [command]``sh`` script should do the trick:

----
# for x in `awk -F: '($3 >= 1001) && ($3 != 65534) { print $1 }' \/etc/passwd`; do pw usermod $x -L default; done;
----


Next, drop the [username]``nagios``
 and [username]``www``
 accounts into the insecure class:

----
# pw usermod nagios -L insecure
# pw usermod www -L insecure
----

=== Create the Contexts File


A contexts file should now be created as [path]``/etc/policy.contexts``
:

[source]
----
# This is the default BIBA policy for this system.

# System:
/var/run(/.*)?			biba/equal

/dev/(/.*)?			biba/equal

/var				biba/equal
/var/spool(/.*)?		biba/equal

/var/log(/.*)?			biba/equal

/tmp(/.*)?			biba/equal
/var/tmp(/.*)?			biba/equal

/var/spool/mqueue		biba/equal
/var/spool/clientmqueue		biba/equal

# For Nagios:
/usr/local/etc/nagios(/.*)?	biba/10

/var/spool/nagios(/.*)?		biba/10

# For apache
/usr/local/etc/apache(/.*)?	biba/10
----


This policy enforces security by setting restrictions on the flow of information.
In this specific configuration, users, including [username]``root``
, should never be allowed to access [app]``Nagios``.
Configuration files and processes that are a part of [app]``Nagios`` will be completely self contained or jailed.

This file will be read after running [command]``setfsmac`` on every file system.
This example sets the policy on the root file system:

----
# setfsmac -ef /etc/policy.contexts /
----


Next, add these edits to the main section of [path]``/etc/mac.conf``
:

[source]
----
default_labels file ?biba
default_labels ifnet ?biba
default_labels process ?biba
default_labels socket ?biba
----

=== Loader Configuration


To finish the configuration, add the following lines to [path]``/boot/loader.conf``
:

[source]
----
mac_biba_load="YES"
mac_seeotheruids_load="YES"
security.mac.biba.trust_all_interfaces=1
----


And the following line to the network card configuration stored in [path]``/etc/rc.conf``
.
If the primary network configuration is done via [acronym]``DHCP``, this may need to be configured manually after every system boot:

[source]
----
maclabel biba/equal
----

=== Testing the Configuration

(((MAC Configuration Testing)))


First, ensure that the web server and [app]``Nagios`` will not be started on system initialization and reboot.
Ensure that [username]``root``
 cannot access any of the files in the [app]``Nagios`` configuration directory.
If [username]``root``
	can list the contents of [path]``/var/spool/nagios``
, something is wrong.
Instead, a "`permission denied`"
 error should be returned.

If all seems well, [app]``Nagios``, [app]``Apache``, and [app]``Sendmail`` can now be started:

----
# cd /etc/mail && make stop && \
setpmac biba/equal make start && setpmac biba/10\(10-10\) apachectl start && \
setpmac biba/10\(10-10\) /usr/local/etc/rc.d/nagios.sh forcestart
----


Double check to ensure that everything is working properly.
If not, check the log files for error messages.
If needed, use  {{< manpage "sysctl" "8" >}}
 to disable the  {{< manpage "mac_biba" "4" >}}
	security policy module and try starting everything again as usual.

[NOTE]
====
The [username]``root``
 user can still change the security enforcement and edit its configuration files.
The following command will permit the degradation of the security policy to a lower grade for a newly spawned shell:

----
# setpmac biba/10 csh
----

To block this from happening, force the user into a range using  {{< manpage "login.conf" "5" >}}
.
If  {{< manpage "setpmac" "8" >}}
 attempts to run a command outside of the compartment's range, an error will be returned and the command will not be executed.
In this case, set root to ``biba/high(high-high)``.
====

[[_mac_troubleshoot]]
== Troubleshooting the MAC Framework

(((MAC Troubleshooting)))


This section discusses common configuration errors and how to resolve them.

The [option]``multilabel`` flag does not stay enabled on the root ([path]``/`` ) partition:::
The following steps may resolve this transient error:

.. Edit [path]``/etc/fstab`` and set the root partition to [option]``ro`` for read-only.
.. Reboot into single user mode.
.. Run [command]``tunefs``[option]``-l enable`` on [path]``/`` .
.. Reboot the system.
.. Run [command]``mount``[option]``-urw``[path]``/`` and change the [option]``ro`` back to [option]``rw`` in [path]``/etc/fstab`` and reboot the system again.
.. Double-check the output from [command]``mount`` to ensure that [option]``multilabel`` has been properly set on the root file system.

After establishing a secure environment with [acronym]``MAC``, [app]``Xorg`` no longer starts:::
This could be caused by the [acronym]``MAC````partition`` policy or by a mislabeling in one of the [acronym]``MAC`` labeling policies.
To debug, try the following:

.. Check the error message. If the user is in the `insecure` class, the `partition` policy may be the culprit. Try setting the user's class back to the `default` class and rebuild the database with [command]``cap_mkdb``. If this does not alleviate the problem, go to step two.
.. Double-check that the label policies are set correctly for the user, [app]``Xorg``, and the [path]``/dev`` entries.
.. If neither of these resolve the problem, send the error message and a description of the environment to the link:FreeBSD general questions mailing list.

The `\_secure_path: unable to stat .login_conf` error appears:::
This error can appear when a user attempts to switch from the [username]``root``
user to another user in the system.
This message usually occurs when the user has a higher label setting than that of the user they are attempting to become.
For instance, if [username]``joe``
has a default label of [option]``biba/low`` and [username]``root``
has a label of [option]``biba/high``, [username]``root``
cannot view [username]``joe``
's home directory.
This will happen whether or not [username]``root``
has used [command]``su`` to become [username]``joe``
as the Biba integrity model will not permit [username]``root``
to view objects set at a lower integrity level.

The system no longer recognizes [username]``root`` :::
When this occurs, [command]``whoami`` returns `0` and [command]``su`` returns ``who are you?``.
+
This can happen if a labeling policy has been disabled by  {{< manpage "sysctl" "8" >}}
or the policy module was unloaded.
If the policy is disabled, the login capabilities database needs to be reconfigured.
Double check [path]``/etc/login.conf``
to ensure that all [option]``label`` options have been removed and rebuild the database with [command]``cap_mkdb``.
+
This may also happen if a policy restricts access to [path]``master.passwd``
.
This is usually caused by an administrator altering the file under a label which conflicts with the general policy being used by the system.
In these cases, the user information would be read by the system and access would be blocked as the file has inherited the new label.
Disable the policy using  {{< manpage "sysctl" "8" >}}
and everything should return to normal.


ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]