---
title: "ZFS: The Z File System"
weight: 190
---
:outfilesuffix: /
[[_zfs]]
== The Z File System (ZFS)

The __Z File System__, or [.acronym]#ZFS#, is an advanced file system designed to overcome many of the major problems found in previous designs.

Originally developed at Sun(TM), ongoing open source [.acronym]#ZFS# development has moved to the http://open-zfs.org[OpenZFS Project].

[.acronym]#ZFS# has three major design goals:

* Data integrity: All data includes a <<terms.adoc#_zfs_term_checksum,checksum>> of the data. When data is written, the checksum is calculated and written along with it. When that data is later read back, the checksum is calculated again. If the checksums do not match, a data error has been detected. [.command]#ZFS# will attempt to automatically correct errors when data redundancy is available.
* Pooled storage: physical storage devices are added to a pool, and storage space is allocated from that shared pool. Space is available to all file systems, and can be increased by adding new storage devices to the pool.
* Performance: multiple caching mechanisms provide increased performance. <<terms.adoc#_zfs_term_arc,ARC>> is an advanced memory-based read cache. A second level of disk-based read cache can be added with <<terms.adoc#_zfs_term_l2arc,L2ARC>>, and disk-based synchronous write cache is available with <<terms.adoc#_zfs_term_zil,ZIL>>.

A complete list of features and terminology is shown in <<./terms.adoc#_zfs_term,ZFS Features and Terminology>>.
