---
title: "GEOM: Modular Disk Transformation Framework"
---
[[_geom]]
= GEOM: Modular Disk Transformation Framework
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
Tom Rhodes

[[_geom_synopsis]]
== Synopsis

(((GEOM)))

(((GEOM Disk Framework)))


In FreeBSD, the [acronym]``GEOM`` framework permits access and control to classes, such as Master Boot Records and [acronym]``BSD`` labels, through the use of providers, or the disk devices in [path]``/dev``
.
By supporting various software [acronym]``RAID`` configurations, [acronym]``GEOM`` transparently provides access  to the operating system and operating system utilities.

This chapter covers the use of disks under the [acronym]``GEOM`` framework in FreeBSD.
This includes the major [acronym]``RAID`` control utilities which use the framework for configuration.
This chapter is not a definitive guide to [acronym]``RAID`` configurations and only [acronym]``GEOM``-supported [acronym]``RAID`` classifications are discussed.

After reading this chapter, you will know:

* What type of [acronym]``RAID`` support is available through [acronym]``GEOM``.
* How to use the base utilities to configure, maintain, and manipulate the various [acronym]``RAID``	  levels.
* How to mirror, stripe, encrypt, and remotely connect disk devices through [acronym]``GEOM``.
* How to troubleshoot disks attached to the [acronym]``GEOM`` framework.


Before reading this chapter, you should:

* Understand how FreeBSD treats disk devices (<<_disks>>).
* Know how to configure and install a new kernel (<<_kernelconfig>>).


[[_geom_striping]]
== RAID0 - Striping
= RAID0 - Striping
:imagesdir: ./images
Tom Rhodes; Murray Stokely

(((GEOM)))

(((Striping)))


Striping combines several disk drives into a single volume.
Striping can be performed through the use of hardware [acronym]``RAID`` controllers.
The [acronym]``GEOM`` disk subsystem provides software support for disk striping, also known as [acronym]``RAID0``, without the need for a [acronym]``RAID`` disk controller.

In [acronym]``RAID0``, data is split into blocks that are written across all the drives in the array.
As seen in the following illustration, instead of having to wait on the system to write 256k to one disk, [acronym]``RAID0`` can simultaneously write 64k to each of the four disks in the array, offering superior [acronym]``I/O`` performance.
This performance can be enhanced further by using multiple disk controllers.



image::geom/striping[Disk Striping Illustration]


Each disk in a [acronym]``RAID0`` stripe must be of the same size, since [acronym]``I/O`` requests are interleaved to read or write to multiple disks in parallel.

[NOTE]
====
[acronym]``RAID0`` does _not_	provide any redundancy.
This means that if one disk in the array fails, all of the data on the disks is lost.
If the data is important, implement a backup strategy that regularly saves backups to a remote system or device.
====


The process for creating a software, [acronym]``GEOM``-based [acronym]``RAID0`` on a FreeBSD system using commodity disks is as follows.
Once the stripe is created, refer to  {{< manpage "gstripe" "8" >}}
 for more information on how to control an existing stripe.

.Procedure: Creating a Stripe of Unformatted [acronym]``ATA``Disks
. Load the [path]``geom_stripe.ko`` module:
+

----
# kldload geom_stripe
----
. Ensure that a suitable mount point exists. If this volume will become a root partition, then temporarily use another mount point such as [path]``/mnt`` .
. Determine the device names for the disks which will be striped, and create the new stripe device. For example, to stripe two unused and unpartitioned [acronym]``ATA`` disks with device names of [path]``/dev/ad2`` and [path]``/dev/ad3`` :
+

----
# gstripe label -v st0 /dev/ad2 /dev/ad3Metadata value stored on /dev/ad2.
Metadata value stored on /dev/ad3.
Done.
----
. Write a standard label, also known as a partition table, on the new volume and install the default bootstrap code:
+

----
# bsdlabel -wB /dev/stripe/st0
----
. This process should create two other devices in [path]``/dev/stripe`` in addition to [path]``st0`` . Those include [path]``st0a`` and [path]``st0c`` . At this point, a [acronym]``UFS`` file system can be created on [path]``st0a`` using [command]``newfs``:
+

----
# newfs -U /dev/stripe/st0a
----
+
Many numbers will glide across the screen, and after a few seconds, the process will be complete.
The volume has been created and is ready to be mounted.
. To manually mount the created disk stripe:
+

----
# mount /dev/stripe/st0a /mnt
----
. To mount this striped file system automatically during the boot process, place the volume information in [path]``/etc/fstab`` . In this example, a permanent mount point, named [path]``stripe`` , is created:
+

----
# mkdir /stripe
# echo "/dev/stripe/st0a /stripe ufs rw 2 2" \>> /etc/fstab
----
. The [path]``geom_stripe.ko`` module must also be automatically loaded during system initialization, by adding a line to [path]``/boot/loader.conf`` :
+

----
# sysrc -f /boot/loader.conf geom_stripe_load=YES
----


[[_geom_mirror]]
== RAID1 - Mirroring

(((GEOM)))

(((Disk Mirroring)))

(((RAID1)))

[acronym]``
RAID1``, or __mirroring__, is the technique of writing the same data to more than one disk drive.
Mirrors are usually used to guard against data loss due to drive failure.
Each drive in a mirror contains an identical copy of the data.
When an individual drive fails, the mirror continues to work, providing data from the drives that are still functioning.
The computer keeps running, and the administrator has time to replace the failed drive without user interruption.

Two common situations are illustrated in these examples.
The first creates a mirror out of two new drives and uses it as a replacement for an existing single drive.
The second example creates a mirror on a single new drive, copies the old drive's data to it, then inserts the old drive into the mirror.
While this procedure is slightly more complicated, it only requires one new drive.

Traditionally, the two drives in a mirror are identical in model and capacity, but  {{< manpage "gmirror" "8" >}}
 does not require that.
Mirrors created with dissimilar drives will have a capacity equal to that of the smallest drive in the mirror.
Extra space on larger drives will be unused.
Drives inserted into the mirror later must have at least as much capacity as the smallest drive already in the mirror.

[WARNING]
====
The mirroring procedures shown here are non-destructive, but as with any major disk operation, make a full backup first.
====

[WARNING]
====
While  {{< manpage "dump" "8" >}}
 is used in these procedures to copy file systems, it does not work on file systems with soft updates journaling.
See  {{< manpage "tunefs" "8" >}}
 for information on detecting and disabling soft updates journaling.
====

[[_geom_mirror_metadata]]
=== Metadata Issues


Many disk systems store metadata at the end of each disk.
Old metadata should be erased before reusing the disk for a mirror.
Most problems are caused by two particular types of leftover metadata: [acronym]``GPT`` partition tables and old metadata from a previous mirror.

[acronym]``GPT`` metadata can be erased with  {{< manpage "gpart" "8" >}}
.
This example erases both primary and backup [acronym]``GPT`` partition tables from disk [path]``ada8``
:

----
# gpart destroy -F ada8
----


A disk can be removed from an active mirror and the metadata erased in one step using  {{< manpage "gmirror" "8" >}}
.
Here, the example disk [path]``ada8``
 is removed from the active mirror [path]``gm4``
:

----
# gmirror remove gm4 ada8
----


If the mirror is not running, but old mirror metadata is still on the disk, use [command]``gmirror clear`` to remove it:

----
# gmirror clear ada8
----

 {{< manpage "gmirror" "8" >}}
 stores one block of metadata at the end of the disk.
Because [acronym]``GPT`` partition schemes also store metadata at the end of the disk, mirroring entire [acronym]``GPT`` disks with  {{< manpage "gmirror" "8" >}}
 is not recommended. [acronym]``MBR`` partitioning is used here because it only stores a partition table at the start of the disk and does not conflict with the mirror metadata.

[[_geom_mirror_two_new_disks]]
=== Creating a Mirror with Two New Disks


In this example, FreeBSD has already been installed on a single disk, [path]``ada0``
.
Two new disks, [path]``ada1``
 and [path]``ada2``
, have been connected to the system.
A new mirror will be created on these two disks and used to replace the old single disk.

The [path]``geom_mirror.ko``
 kernel module must either be built into the kernel or loaded at boot- or run-time.
Manually load the kernel module now:

----
# gmirror load
----


Create the mirror with the two new drives:

----
# gmirror label -v gm0 /dev/ada1 /dev/ada2
----

[path]``gm0``
 is a user-chosen device name assigned to the new mirror.
After the mirror has been started, this device name appears in [path]``/dev/mirror/``
.

[acronym]``MBR`` and [app]``bsdlabel`` partition tables can now be created on the mirror with  {{< manpage "gpart" "8" >}}
.
This example uses a traditional file system layout, with partitions for [path]``/``
, swap, [path]``/var``
, [path]``/tmp``
, and [path]``/usr``
.
A single [path]``/``
 and a swap partition will also work.

Partitions on the mirror do not have to be the same size as those on the existing disk, but they must be large enough to hold all the data already present on [path]``ada0``
.

----
# gpart create -s MBR mirror/gm0
# gpart add -t freebsd -a 4k mirror/gm0
# gpart show mirror/gm0=>       63  156301423  mirror/gm0  MBR  (74G)
         63         63                    - free -  (31k)
        126  156301299                 1  freebsd  (74G)
  156301425         61                    - free -  (30k)
----

----
# gpart create -s BSD mirror/gm0s1
# gpart add -t freebsd-ufs  -a 4k -s 2g mirror/gm0s1
# gpart add -t freebsd-swap -a 4k -s 4g mirror/gm0s1
# gpart add -t freebsd-ufs  -a 4k -s 2g mirror/gm0s1
# gpart add -t freebsd-ufs  -a 4k -s 1g mirror/gm0s1
# gpart add -t freebsd-ufs  -a 4k       mirror/gm0s1
# gpart show mirror/gm0s1=>        0  156301299  mirror/gm0s1  BSD  (74G)
          0          2                      - free -  (1.0k)
          2    4194304                   1  freebsd-ufs  (2.0G)
    4194306    8388608                   2  freebsd-swap  (4.0G)
   12582914    4194304                   4  freebsd-ufs  (2.0G)
   16777218    2097152                   5  freebsd-ufs  (1.0G)
   18874370  137426928                   6  freebsd-ufs  (65G)
  156301298          1                      - free -  (512B)
----


Make the mirror bootable by installing bootcode in the [acronym]``MBR`` and bsdlabel and setting the active slice:

----
# gpart bootcode -b /boot/mbr mirror/gm0
# gpart set -a active -i 1 mirror/gm0
# gpart bootcode -b /boot/boot mirror/gm0s1
----


Format the file systems on the new mirror, enabling soft-updates.

----
# newfs -U /dev/mirror/gm0s1a
# newfs -U /dev/mirror/gm0s1d
# newfs -U /dev/mirror/gm0s1e
# newfs -U /dev/mirror/gm0s1f
----


File systems from the original [path]``ada0``
	disk can now be copied onto the mirror with  {{< manpage "dump" "8" >}}
 and  {{< manpage "restore" "8" >}}
.

----
# mount /dev/mirror/gm0s1a /mnt
# dump -C16 -b64 -0aL -f - / | (cd /mnt && restore -rf -)
# mount /dev/mirror/gm0s1d /mnt/var
# mount /dev/mirror/gm0s1e /mnt/tmp
# mount /dev/mirror/gm0s1f /mnt/usr
# dump -C16 -b64 -0aL -f - /var | (cd /mnt/var && restore -rf -)
# dump -C16 -b64 -0aL -f - /tmp | (cd /mnt/tmp && restore -rf -)
# dump -C16 -b64 -0aL -f - /usr | (cd /mnt/usr && restore -rf -)
----


Edit [path]``/mnt/etc/fstab``
 to point to the new mirror file systems:

[source]
----
# Device		Mountpoint	FStype	Options	Dump	Pass#
/dev/mirror/gm0s1a	/		ufs	rw	1	1
/dev/mirror/gm0s1b	none		swap	sw	0	0
/dev/mirror/gm0s1d	/var		ufs	rw	2	2
/dev/mirror/gm0s1e	/tmp		ufs	rw	2	2
/dev/mirror/gm0s1f	/usr		ufs	rw	2	2
----


If the [path]``geom_mirror.ko``
 kernel module has not been built into the kernel, [path]``/mnt/boot/loader.conf``
 is edited to load the module at boot:

[source]
----
geom_mirror_load="YES"
----


Reboot the system to test the new mirror and verify that all data has been copied.
The [acronym]``BIOS`` will see the mirror as two individual drives rather than a mirror.
Because the drives are identical, it does not matter which is selected to boot.

See <<_gmirror_troubleshooting>> if there are problems booting.
Powering down and disconnecting the original [path]``ada0``
 disk will allow it to be kept as an offline backup.

In use, the mirror will behave just like the original single drive.

[[_geom_mirror_existing_drive]]
=== Creating a Mirror with an Existing Drive


In this example, FreeBSD has already been installed on a single disk, [path]``ada0``
.
A new disk, [path]``ada1``
, has been connected to the system.
A one-disk mirror will be created on the new disk, the existing system copied onto it, and then the old disk will be inserted into the mirror.
This slightly complex procedure is required because [command]``gmirror`` needs to put a 512-byte block of metadata at the end of each disk, and the existing [path]``ada0``
 has usually had all of its space already allocated.

Load the [path]``geom_mirror.ko``
 kernel module:

----
# gmirror load
----


Check the media size of the original disk with [command]``diskinfo``:

----
# diskinfo -v ada0 | head -n3/dev/ada0
	512             # sectorsize
	1000204821504   # mediasize in bytes (931G)
----


Create a mirror on the new disk.
To make certain that the mirror capacity is not any larger than the original [path]``ada0``
 drive,  {{< manpage "gnop" "8" >}}
 is used to create a fake drive of the exact same size.
This drive does not store any data, but is used only to limit the size of the mirror.
When  {{< manpage "gmirror" "8" >}}
 creates the mirror, it will restrict the capacity to the size of [path]``gzero.nop``
, even if the new [path]``ada1``
 drive has more space.
Note that the [replaceable]``1000204821504`` in the second line is equal to [path]``ada0``
's media size as shown by [command]``diskinfo`` above.

----
# geom zero load
# gnop create -s 1000204821504 gzero
# gmirror label -v gm0 gzero.nop ada1
# gmirror forget gm0
----


Since [path]``gzero.nop``
 does not store any data, the mirror does not see it as connected.
The mirror is told to "`forget`"
 unconnected components, removing references to [path]``gzero.nop``
.
The result is a mirror device containing only a single disk, [path]``ada1``
.

After creating [path]``gm0``
, view the partition table on [path]``ada0``
.
This output is from a 1{nbsp}TB drive.
If there is some unallocated space at the end of the drive, the contents may be copied directly from [path]``ada0``
 to the new mirror.

However, if the output shows that all of the space on the disk is allocated, as in the following listing, there is no space available for the 512-byte mirror metadata at the end of the disk.

----
# gpart show ada0=>        63  1953525105        ada0  MBR  (931G)
          63  1953525105           1  freebsd  [active]  (931G)
----


In this case, the partition table must be edited to reduce the capacity by one sector on [path]``mirror/gm0``
.
The procedure will be explained later.

In either case, partition tables on the primary disk should be first copied using [command]``gpart backup``	and [command]``gpart restore``.

----
# gpart backup ada0 > table.ada0
# gpart backup ada0s1 > table.ada0s1
----


These commands create two files, [path]``table.ada0``
 and [path]``table.ada0s1``
.
This example is from a 1{nbsp}TB drive:

----
# cat table.ada0MBR 4
1 freebsd         63 1953525105   [active]
----

----
# cat table.ada0s1BSD 8
1  freebsd-ufs          0    4194304
2 freebsd-swap    4194304   33554432
4  freebsd-ufs   37748736   50331648
5  freebsd-ufs   88080384   41943040
6  freebsd-ufs  130023424  838860800
7  freebsd-ufs  968884224  984640881
----


If no free space is shown at the end of the disk, the size of both the slice and the last partition must be reduced by one sector.
Edit the two files, reducing the size of both the slice and last partition by one.
These are the last numbers in each listing.

----
# cat table.ada0MBR 4
1 freebsd         63[active]
----

----
# cat table.ada0s1BSD 8
1  freebsd-ufs          0    4194304
2 freebsd-swap    4194304   33554432
4  freebsd-ufs   37748736   50331648
5  freebsd-ufs   88080384   41943040
6  freebsd-ufs  130023424  838860800
7  freebsd-ufs  968884224
----


If at least one sector was unallocated at the end of the disk, these two files can be used without modification.

Now restore the partition table into [path]``mirror/gm0``
:

----
# gpart restore mirror/gm0 < table.ada0
# gpart restore mirror/gm0s1 < table.ada0s1
----


Check the partition table with [command]``gpart show``.
This example has [path]``gm0s1a``
 for [path]``/``
, [path]``gm0s1d``
 for [path]``/var``
, [path]``gm0s1e``
 for [path]``/usr``
, [path]``gm0s1f``
 for [path]``/data1``
, and [path]``gm0s1g``
 for [path]``/data2``
.

----
# gpart show mirror/gm0=>        63  1953525104  mirror/gm0  MBR  (931G)
          63  1953525042           1  freebsd  [active]  (931G)
  1953525105          62              - free -  (31k)
# gpart show mirror/gm0s1=>         0  1953525042  mirror/gm0s1  BSD  (931G)
           0     2097152             1  freebsd-ufs  (1.0G)
     2097152    16777216             2  freebsd-swap  (8.0G)
    18874368    41943040             4  freebsd-ufs  (20G)
    60817408    20971520             5  freebsd-ufs  (10G)
    81788928   629145600             6  freebsd-ufs  (300G)
   710934528  1242590514             7  freebsd-ufs  (592G)
  1953525042          63                - free -  (31k)
----


Both the slice and the last partition must have at least one free block at the end of the disk.

Create file systems on these new partitions.
The number of partitions will vary to match the original disk, [path]``ada0``
.

----
# newfs -U /dev/mirror/gm0s1a
# newfs -U /dev/mirror/gm0s1d
# newfs -U /dev/mirror/gm0s1e
# newfs -U /dev/mirror/gm0s1f
# newfs -U /dev/mirror/gm0s1g
----


Make the mirror bootable by installing bootcode in the [acronym]``MBR`` and bsdlabel and setting the active slice:

----
# gpart bootcode -b /boot/mbr mirror/gm0
# gpart set -a active -i 1 mirror/gm0
# gpart bootcode -b /boot/boot mirror/gm0s1
----


Adjust [path]``/etc/fstab``
 to use the new partitions on the mirror.
Back up this file first by copying it to [path]``/etc/fstab.orig``
.

----
# cp /etc/fstab /etc/fstab.orig
----


Edit [path]``/etc/fstab``
, replacing [path]``/dev/ada0``
 with [path]``mirror/gm0``
.

[source]
----
# Device		Mountpoint	FStype	Options	Dump	Pass#
/dev/mirror/gm0s1a	/		ufs	rw	1	1
/dev/mirror/gm0s1b	none		swap	sw	0	0
/dev/mirror/gm0s1d	/var		ufs	rw	2	2
/dev/mirror/gm0s1e	/usr		ufs	rw	2	2
/dev/mirror/gm0s1f	/data1		ufs	rw	2	2
/dev/mirror/gm0s1g	/data2		ufs	rw	2	2
----


If the [path]``geom_mirror.ko``
 kernel module has not been built into the kernel, edit [path]``/boot/loader.conf``
 to load it at boot:

[source]
----
geom_mirror_load="YES"
----


File systems from the original disk can now be copied onto the mirror with  {{< manpage "dump" "8" >}}
 and  {{< manpage "restore" "8" >}}
.
Each file system dumped with [command]``dump -L`` will create a snapshot first, which can take some time.

----
# mount /dev/mirror/gm0s1a /mnt
# dump -C16 -b64 -0aL -f - /    | (cd /mnt && restore -rf -)
# mount /dev/mirror/gm0s1d /mnt/var
# mount /dev/mirror/gm0s1e /mnt/usr
# mount /dev/mirror/gm0s1f /mnt/data1
# mount /dev/mirror/gm0s1g /mnt/data2
# dump -C16 -b64 -0aL -f - /usr | (cd /mnt/usr && restore -rf -)
# dump -C16 -b64 -0aL -f - /var | (cd /mnt/var && restore -rf -)
# dump -C16 -b64 -0aL -f - /data1 | (cd /mnt/data1 && restore -rf -)
# dump -C16 -b64 -0aL -f - /data2 | (cd /mnt/data2 && restore -rf -)
----


Restart the system, booting from [path]``ada1``
.
If everything is working, the system will boot from [path]``mirror/gm0``
, which now contains the same data as [path]``ada0``
 had previously.
See <<_gmirror_troubleshooting>> if there are problems booting.

At this point, the mirror still consists of only the single [path]``ada1``
 disk.

After booting from [path]``mirror/gm0``
	successfully, the final step is inserting [path]``ada0``
 into the mirror.

[IMPORTANT]
====
When [path]``ada0``
 is inserted into the mirror, its former contents will be overwritten by data from the mirror.
Make certain that [path]``mirror/gm0``
 has the same contents as [path]``ada0``
 before adding [path]``ada0``
 to the mirror.
If the contents previously copied by  {{< manpage "dump" "8" >}}
 and  {{< manpage "restore" "8" >}}
 are not identical to what was on [path]``ada0``
, revert [path]``/etc/fstab``
 to mount the file systems on [path]``ada0``
, reboot, and start the whole procedure again.
====

----
# gmirror insert gm0 ada0GEOM_MIRROR: Device gm0: rebuilding provider ada0
----


Synchronization between the two disks will start immediately.
Use [command]``gmirror status`` to view the progress.

----
# gmirror statusName    Status  Components
mirror/gm0  DEGRADED  ada1 (ACTIVE)
                      ada0 (SYNCHRONIZING, 64%)
----


After a while, synchronization will finish.

----
GEOM_MIRROR: Device gm0: rebuilding provider ada0 finished.
# gmirror statusName    Status  Components
mirror/gm0  COMPLETE  ada1 (ACTIVE)
                      ada0 (ACTIVE)
----

[path]``mirror/gm0``
 now consists of the two disks [path]``ada0``
 and [path]``ada1``
, and the contents are automatically synchronized with each other.
In use, [path]``mirror/gm0``
 will behave just like the original single drive.

[[_gmirror_troubleshooting]]
=== Troubleshooting


If the system no longer boots, [acronym]``BIOS``	settings may have to be changed to boot from one of the new mirrored drives.
Either mirror drive can be used for booting, as they contain identical data.

If the boot stops with this message, something is wrong with the mirror device:

----
Mounting from ufs:/dev/mirror/gm0s1a failed with error 19.

Loader variables:
  vfs.root.mountfrom=ufs:/dev/mirror/gm0s1a
  vfs.root.mountfrom.options=rw

Manual root filesystem specification:
  <fstype>:<device> [options]
      Mount <device> using filesystem <fstype>
      and with the specified (optional) option list.

    eg. ufs:/dev/da0s1a
        zfs:tank
        cd9660:/dev/acd0 ro
          (which is equivalent to: mount -t cd9660 -o ro /dev/acd0 /)

  ?               List valid disk boot devices
  .               Yield 1 second (for background tasks)
  <empty line>    Abort manual input

mountroot>
----


Forgetting to load the [path]``geom_mirror.ko``
	module in [path]``/boot/loader.conf``
 can cause this problem.
To fix it, boot from a FreeBSD installation media and choose `Shell` at the first prompt.
Then load the mirror module and mount the mirror device:

----
# gmirror load
# mount /dev/mirror/gm0s1a /mnt
----


Edit [path]``/mnt/boot/loader.conf``
, adding a line to load the mirror module:

[source]
----
geom_mirror_load="YES"
----


Save the file and reboot.

Other problems that cause `error 19`	require more effort to fix.
Although the system should boot from [path]``ada0``
, another prompt to select a shell will appear if [path]``/etc/fstab``
 is incorrect.
Enter `ufs:/dev/ada0s1a` at the boot loader prompt and press kbd:[Enter]
.
Undo the edits in [path]``/etc/fstab``
 then mount the file systems from the original disk ([path]``ada0``
) instead of the mirror.
Reboot the system and try the procedure again.

----
Enter full pathname of shell or RETURN for /bin/sh:
# cp /etc/fstab.orig /etc/fstab
# reboot
----

=== Recovering from Disk Failure


The benefit of disk mirroring is that an individual disk can fail without causing the mirror to lose any data.
In the above example, if [path]``ada0``
 fails, the mirror will continue to work, providing data from the remaining working drive, [path]``ada1``
.

To replace the failed drive, shut down the system and physically replace the failed drive with a new drive of equal or greater capacity.
Manufacturers use somewhat arbitrary values when rating drives in gigabytes, and the only way to really be sure is to compare the total count of sectors shown by [command]``diskinfo -v``.
A drive with larger capacity than the mirror will work, although the extra space on the new drive will not be used.

After the computer is powered back up, the mirror will be running in a "`degraded`"
 mode with only one drive.
The mirror is told to forget drives that are not currently connected:

----
# gmirror forget gm0
----


Any old metadata should be cleared from the replacement disk using the instructions in <<_geom_mirror_metadata>>.
Then the replacement disk, [path]``ada4``
 for this example, is inserted into the mirror:

----
# gmirror insert gm0 /dev/ada4
----


Resynchronization begins when the new drive is inserted into the mirror.
This process of copying mirror data to a new drive can take a while.
Performance of the mirror will be greatly reduced during the copy, so inserting new drives is best done when there is low demand on the computer.

Progress can be monitored with [command]``gmirror
	  status``, which shows drives that are being synchronized and the percentage of completion.
During resynchronization, the status will be ``DEGRADED``, changing to `COMPLETE` when the process is finished.

[[_geom_raid3]]
== RAID3 - Byte-level Striping with Dedicated Parity
= RAID3 - Byte-level Striping with
	Dedicated Parity
:imagesdir: ./images
Mark Gladman; Daniel Gerzo; Tom Rhodes; Murray Stokely

(((GEOM)))

(((RAID3)))

[acronym]``
RAID``3 is a method used to combine several disk drives into a single volume with a dedicated parity disk.
In a [acronym]``RAID``3 system, data is split up into a number of bytes that are written across all the drives in the array except for one disk which acts as a dedicated parity disk.
This means that disk reads from a [acronym]``RAID``3 implementation access all disks in the array.
Performance can be enhanced by using multiple disk controllers.
The [acronym]``RAID``3 array provides a fault tolerance of 1 drive, while providing a capacity of 1 - 1/n times the total capacity of all drives in the array, where n is the number of hard drives in the array.
Such a configuration is mostly suitable for storing data of larger sizes such as multimedia files.

At least 3 physical hard drives are required to build a [acronym]``RAID``3 array.
Each disk must be of the same size, since [acronym]``I/O`` requests are interleaved to read or write to multiple disks in parallel.
Also, due to the nature of [acronym]``RAID``3, the number of drives must be equal to 3, 5, 9, 17, and so on, or 2^n + 1.

This section demonstrates how to create a software [acronym]``RAID``3 on a FreeBSD system.

[NOTE]
====
While it is theoretically possible to boot from a [acronym]``RAID``3 array on FreeBSD, that configuration is uncommon and is not advised.
====

=== Creating a Dedicated RAID3 Array


In FreeBSD, support for [acronym]``RAID``3 is implemented by the  {{< manpage "graid3" "8" >}}[acronym]``GEOM``	class.
Creating a dedicated [acronym]``RAID``3 array on FreeBSD requires the following steps.


. First, load the [path]``geom_raid3.ko`` kernel module by issuing one of the following commands:
+

----
# graid3 load
----
+
or:
+

----
# kldload geom_raid3
----
. Ensure that a suitable mount point exists. This command creates a new directory to use as the mount point:
+

----
# mkdir /multimedia
----
. Determine the device names for the disks which will be added to the array, and create the new [acronym]``RAID``3 device. The final device listed will act as the dedicated parity disk. This example uses three unpartitioned [acronym]``ATA`` drives: [path]``ada1`` and [path]``ada2`` for data, and [path]``ada3`` for parity.
+

----
# graid3 label -v gr0 /dev/ada1 /dev/ada2 /dev/ada3Metadata value stored on /dev/ada1.
Metadata value stored on /dev/ada2.
Metadata value stored on /dev/ada3.
Done.
----
. Partition the newly created [path]``gr0`` device and put a [acronym]``UFS`` file system on it:
+

----
# gpart create -s GPT /dev/raid3/gr0
# gpart add -t freebsd-ufs /dev/raid3/gr0
# newfs -j /dev/raid3/gr0p1
----
+
Many numbers will glide across the screen, and after a bit of time, the process will be complete.
The volume has been created and is ready to be mounted:
+

----
# mount /dev/raid3/gr0p1 /multimedia/
----
+
The [acronym]``RAID``3 array is now ready to use.


Additional configuration is needed to retain this setup across system reboots.


. The [path]``geom_raid3.ko`` module must be loaded before the array can be mounted. To automatically load the kernel module during system initialization, add the following line to [path]``/boot/loader.conf`` :
+

[source]
----
geom_raid3_load="YES"
----
. The following volume information must be added to [path]``/etc/fstab`` in order to automatically mount the array's file system during the system boot process:
+

[source]
----
/dev/raid3/gr0p1	/multimedia	ufs	rw	2	2
----


[[_geom_graid]]
== Software RAID Devices
= Software RAID Devices
:imagesdir: ./images
Warren Block

(((GEOM)))

(((Software RAID Devices,Hardware-assisted RAID)))


Some motherboards and expansion cards add some simple hardware, usually just a [acronym]``ROM``, that allows the computer to boot from a [acronym]``RAID`` array.
After booting, access to the [acronym]``RAID`` array is handled by software running on the computer's main processor.
This "`hardware-assisted software
	[acronym]``RAID```"
 gives [acronym]``RAID`` arrays that are not dependent on any particular operating system, and which are functional even before an operating system is loaded.

Several levels of [acronym]``RAID`` are supported, depending on the hardware in use.
See  {{< manpage "graid" "8" >}}
 for a complete list.

 {{< manpage "graid" "8" >}}
 requires the [path]``geom_raid.ko``
 kernel module, which is included in the [path]``GENERIC``
 kernel starting with FreeBSD{nbsp}9.1.
If needed, it can be loaded manually with [command]``graid load``.

[[_geom_graid_creating]]
=== Creating an Array


Software [acronym]``RAID`` devices often have a menu that can be entered by pressing special keys when the computer is booting.
The menu can be used to create and delete [acronym]``RAID`` arrays.
  {{< manpage "graid" "8" >}}
 can also create arrays directly from the command line.

[command]``graid label`` is used to create a new array.
The motherboard used for this example has an Intel software [acronym]``RAID`` chipset, so the Intel metadata format is specified.
The new array is given a label of [path]``gm0``
, it is a mirror ([acronym]``RAID1``), and uses drives [path]``ada0``
 and [path]``ada1``
.

[CAUTION]
====
Some space on the drives will be overwritten when they are made into a new array.
Back up existing data first!
====

----
# graid label Intel gm0 RAID1 ada0 ada1GEOM_RAID: Intel-a29ea104: Array Intel-a29ea104 created.
GEOM_RAID: Intel-a29ea104: Disk ada0 state changed from NONE to ACTIVE.
GEOM_RAID: Intel-a29ea104: Subdisk gm0:0-ada0 state changed from NONE to ACTIVE.
GEOM_RAID: Intel-a29ea104: Disk ada1 state changed from NONE to ACTIVE.
GEOM_RAID: Intel-a29ea104: Subdisk gm0:1-ada1 state changed from NONE to ACTIVE.
GEOM_RAID: Intel-a29ea104: Array started.
GEOM_RAID: Intel-a29ea104: Volume gm0 state changed from STARTING to OPTIMAL.
Intel-a29ea104 created
GEOM_RAID: Intel-a29ea104: Provider raid/r0 for volume gm0 created.
----


A status check shows the new mirror is ready for use:

----
# graid statusName   Status  Components
raid/r0  OPTIMAL  ada0 (ACTIVE (ACTIVE))
                  ada1 (ACTIVE (ACTIVE))
----


The array device appears in [path]``/dev/raid/``
.
The first array is called [path]``r0``
.
Additional arrays, if present, will be [path]``r1``
, [path]``r2``
, and so on.

The [acronym]``BIOS`` menu on some of these devices can create arrays with special characters in their names.
To avoid problems with those special characters, arrays are given simple numbered names like [path]``r0``
.
To show the actual labels, like [path]``gm0``
 in the example above, use  {{< manpage "sysctl" "8" >}}
:

----
# sysctl kern.geom.raid.name_format=1
----

[[_geom_graid_volumes]]
=== Multiple Volumes


Some software [acronym]``RAID`` devices support more than one _volume_ on an array.
Volumes work like partitions, allowing space on the physical drives to be split and used in different ways.
For example, Intel software [acronym]``RAID`` devices support two volumes.
This example creates a 40{nbsp}G mirror for safely storing the operating system, followed by a 20{nbsp}G [acronym]``RAID0`` (stripe) volume for fast temporary storage:

----
# graid label -S 40G Intel gm0 RAID1 ada0 ada1
# graid add -S 20G gm0 RAID0
----


Volumes appear as additional [path]``rX``
 entries in [path]``/dev/raid/``
.
An array with two volumes will show [path]``r0``
 and [path]``r1``
.

See  {{< manpage "graid" "8" >}}
 for the number of volumes supported by different software [acronym]``RAID`` devices.

[[_geom_graid_converting]]
=== Converting a Single Drive to a Mirror


Under certain specific conditions, it is possible to convert an existing single drive to a  {{< manpage "graid" "8" >}}
 array without reformatting.
To avoid data loss during the conversion, the existing drive must meet these minimum requirements:

* The drive must be partitioned with the [acronym]``MBR`` partitioning scheme. [acronym]``GPT`` or other partitioning schemes with metadata at the end of the drive will be overwritten and corrupted by the  {{< manpage "graid" "8" >}} metadata.
* There must be enough unpartitioned and unused space at the end of the drive to hold the  {{< manpage "graid" "8" >}} metadata. This metadata varies in size, but the largest occupies 64{nbsp}M, so at least that much free space is recommended.


If the drive meets these requirements, start by making a full backup.
Then create a single-drive mirror with that drive:

----
# graid label Intel gm0 RAID1 ada0 NONE
----

 {{< manpage "graid" "8" >}}
 metadata was written to the end of the drive in the unused space.
A second drive can now be inserted into the mirror:

----
# graid insert raid/r0 ada1
----


Data from the original drive will immediately begin to be copied to the second drive.
The mirror will operate in degraded status until the copy is complete.

[[_geom_graid_inserting]]
=== Inserting New Drives into the Array


Drives can be inserted into an array as replacements for drives that have failed or are missing.
If there are no failed or missing drives, the new drive becomes a spare.
For example, inserting a new drive into a working two-drive mirror results in a two-drive mirror with one spare drive, not a three-drive mirror.

In the example mirror array, data immediately begins to be copied to the newly-inserted drive.
Any existing information on the new drive will be overwritten.

----
# graid insert raid/r0 ada1GEOM_RAID: Intel-a29ea104: Disk ada1 state changed from NONE to ACTIVE.
GEOM_RAID: Intel-a29ea104: Subdisk gm0:1-ada1 state changed from NONE to NEW.
GEOM_RAID: Intel-a29ea104: Subdisk gm0:1-ada1 state changed from NEW to REBUILD.
GEOM_RAID: Intel-a29ea104: Subdisk gm0:1-ada1 rebuild start at 0.
----

[[_geom_graid_removing]]
=== Removing Drives from the Array


Individual drives can be permanently removed from a from an array and their metadata erased:

----
# graid remove raid/r0 ada1GEOM_RAID: Intel-a29ea104: Disk ada1 state changed from ACTIVE to OFFLINE.
GEOM_RAID: Intel-a29ea104: Subdisk gm0:1-[unknown] state changed from ACTIVE to NONE.
GEOM_RAID: Intel-a29ea104: Volume gm0 state changed from OPTIMAL to DEGRADED.
----

[[_geom_graid_stopping]]
=== Stopping the Array


An array can be stopped without removing metadata from the drives.
The array will be restarted when the system is booted.

----
# graid stop raid/r0
----

[[_geom_graid_status]]
=== Checking Array Status


Array status can be checked at any time.
After a drive was added to the mirror in the example above, data is being copied from the original drive to the new drive:

----
# graid statusName    Status  Components
raid/r0  DEGRADED  ada0 (ACTIVE (ACTIVE))
                   ada1 (ACTIVE (REBUILD 28%))
----


Some types of arrays, like `RAID0` or ``CONCAT``, may not be shown in the status report if disks have failed.
To see these partially-failed arrays, add [option]``-ga``:

----
# graid status -gaName  Status  Components
Intel-e2d07d9a  BROKEN  ada6 (ACTIVE (ACTIVE))
----

[[_geom_graid_deleting]]
=== Deleting Arrays


Arrays are destroyed by deleting all of the volumes from them.
When the last volume present is deleted, the array is stopped and metadata is removed from the drives:

----
# graid delete raid/r0
----

[[_geom_graid_unexpected]]
=== Deleting Unexpected Arrays


Drives may unexpectedly contain  {{< manpage "graid" "8" >}}
 metadata, either from previous use or manufacturer testing.  {{< manpage "graid" "8" >}}
 will detect these drives and create an array, interfering with access to the individual drive.
To remove the unwanted metadata:


. Boot the system. At the boot menu, select `2` for the loader prompt. Enter:
+

----
OKset kern.geom.raid.enable=0OKboot
----
+
The system will boot with  {{< manpage "graid" "8" >}}
disabled.
. Back up all data on the affected drive.
. As a workaround,  {{< manpage "graid" "8" >}} array detection can be disabled by adding
+

[source]
----
kern.geom.raid.enable=0
----
+
to [path]``/boot/loader.conf``
.
+ 
To permanently remove the  {{< manpage "graid" "8" >}}
metadata from the affected drive, boot a FreeBSD installation [acronym]``CD-ROM`` or memory stick, and select ``Shell``.
Use [command]``status``	    to find the name of the array, typically ``raid/r0``:
+

----
# graid statusName   Status  Components
raid/r0  OPTIMAL  ada0 (ACTIVE (ACTIVE))
                  ada1 (ACTIVE (ACTIVE))
----
+
Delete the volume by name:
+

----
# graid delete raid/r0
----
+
If there is more than one volume shown, repeat the process for each volume.
After the last array has been deleted, the volume will be destroyed.
+ 
Reboot and verify data, restoring from backup if necessary.
After the metadata has been removed, the `kern.geom.raid.enable=0` entry in [path]``/boot/loader.conf``
can also be removed.


[[_geom_ggate]]
== GEOM Gate Network

[acronym]``
GEOM`` provides a simple mechanism for providing remote access to devices such as disks, [acronym]``CD``s, and file systems through the use of the [acronym]``GEOM`` Gate network daemon, [app]``ggated``.
The system with the device runs the server daemon which handles requests made by clients using [app]``ggatec``.
The devices should not contain any sensitive data as the connection between the client and the server is not encrypted.

Similar to [acronym]``NFS``, which is discussed in <<_network_nfs>>, [app]``ggated`` is configured using an exports file.
This file specifies which systems are permitted to access the exported resources and what level of access they are offered.
For example, to give the client [ipaddress]``192.168.1.5``
 read and write access to the fourth slice on the first [acronym]``SCSI`` disk, create [path]``/etc/gg.exports``
 with this line:

[source]
----
192.168.1.5 RW /dev/da0s4d
----


Before exporting the device, ensure it is not currently mounted.
Then, start [app]``ggated``:

----
# ggated
----


Several options are available for specifying an alternate listening port or changing the default location of the exports file.
Refer to  {{< manpage "ggated" "8" >}}
 for details.

To access the exported device on the client machine, first use [command]``ggatec`` to specify the [acronym]``IP`` address of the server and the device name of the exported device.
If successful, this command will display a `ggate` device name to mount.
Mount that specified device name on a free mount point.
This example connects to the [path]``/dev/da0s4d``
 partition on ``192.168.1.1``, then mounts [path]``/dev/ggate0``
 on [path]``/mnt``
:

----
# ggatec create -o rw 192.168.1.1 /dev/da0s4dggate0
# mount /dev/ggate0 /mnt
----


The device on the server may now be accessed through [path]``/mnt``
 on the client.
For more details about [command]``ggatec`` and a few usage examples, refer to  {{< manpage "ggatec" "8" >}}
.

[NOTE]
====
The mount will fail if the device is currently mounted on either the server or any other client on the network.
If simultaneous access is needed to network resources, use [acronym]``NFS`` instead.
====


When the device is no longer needed, unmount it with [command]``umount`` so that the resource is available to other clients.

[[_geom_glabel]]
== Labeling Disk Devices

(((Disk Labels)))


During system initialization, the FreeBSD kernel creates device nodes as devices are found.
This method of probing for devices raises some issues.
For instance, what if a new disk device is added via [acronym]``USB``?  It is likely that a flash device may be handed the device name of [path]``da0``
 and the original [path]``da0``
 shifted to [path]``da1``
.
This will cause issues mounting file systems if they are listed in [path]``/etc/fstab``
 which may also prevent the system from booting.

One solution is to chain [acronym]``SCSI`` devices in order so a new device added to the [acronym]``SCSI`` card will be issued unused device numbers.
But what about [acronym]``USB`` devices which may replace the primary [acronym]``SCSI`` disk?  This happens because [acronym]``USB`` devices are usually probed before the [acronym]``SCSI`` card.
One solution is to only insert these devices after the system has been booted.
Another method is to use only a single [acronym]``ATA`` drive and never list the [acronym]``SCSI`` devices in [path]``/etc/fstab``
.

A better solution is to use [command]``glabel`` to label the disk devices and use the labels in [path]``/etc/fstab``
.
Because [command]``glabel`` stores the label in the last sector of a given provider, the label will remain persistent across reboots.
By using this label as a device, the file system may always be mounted regardless of what device node it is accessed through.

[NOTE]
====
[command]``glabel`` can create both transient and permanent labels.
Only permanent labels are consistent across reboots.
Refer to  {{< manpage "glabel" "8" >}}
 for more information on the differences between labels.
====

=== Label Types and Examples


Permanent labels can be a generic or a file system label.
Permanent file system labels can be created with  {{< manpage "tunefs" "8" >}}
 or  {{< manpage "newfs" "8" >}}
.
These types of labels are created in a sub-directory of [path]``/dev``
, and will be named according to the file system type.
For example, [acronym]``UFS``2 file system labels will be created in [path]``/dev/ufs``
.
Generic permanent labels can be created with [command]``glabel label``.
These are not file system specific and will be created in [path]``/dev/label``
.

Temporary labels are destroyed at the next reboot.
These labels are created in [path]``/dev/label``
 and are suited to experimentation.
A temporary label can be created using [command]``glabel create``.

To create a permanent label for a [acronym]``UFS``2 file system without destroying any data, issue the following command:

----
# tunefs -L home /dev/da3
----


A label should now exist in [path]``/dev/ufs``
	which may be added to [path]``/etc/fstab``
:

[source]
----
/dev/ufs/home		/home            ufs     rw              2      2
----

[NOTE]
====
The file system must not be mounted while attempting to run [command]``tunefs``.
====


Now the file system may be mounted:

----
# mount /home
----


From this point on, so long as the [path]``geom_label.ko``
 kernel module is loaded at boot with [path]``/boot/loader.conf``
 or the `GEOM_LABEL` kernel option is present, the device node may change without any ill effect on the system.

File systems may also be created with a default label by using the [option]``-L`` flag with [command]``newfs``.
Refer to  {{< manpage "newfs" "8" >}}
 for more information.

The following command can be used to destroy the label:

----
# glabel destroy home
----


The following example shows how to label the partitions of a boot disk.

.Labeling Partitions on the Boot Disk
====
By permanently labeling the partitions on the boot disk, the system should be able to continue to boot normally, even if the disk is moved to another controller or transferred to a different system.
For this example, it is assumed that a single [acronym]``ATA`` disk is used, which is currently recognized by the system as [path]``ad0``
.
It is also assumed that the standard FreeBSD partition scheme is used, with [path]``/``
, [path]``/var``
, [path]``/usr``
 and [path]``/tmp``
, as well as a swap partition.

Reboot the system, and at the  {{< manpage "loader" "8" >}}
 prompt, press kbd:[4]
 to boot into single user mode.
Then enter the following commands:

----
# glabel label rootfs /dev/ad0s1aGEOM_LABEL: Label for provider /dev/ad0s1a is label/rootfs
# glabel label var /dev/ad0s1dGEOM_LABEL: Label for provider /dev/ad0s1d is label/var
# glabel label usr /dev/ad0s1fGEOM_LABEL: Label for provider /dev/ad0s1f is label/usr
# glabel label tmp /dev/ad0s1eGEOM_LABEL: Label for provider /dev/ad0s1e is label/tmp
# glabel label swap /dev/ad0s1bGEOM_LABEL: Label for provider /dev/ad0s1b is label/swap
# exit
----

The system will continue with multi-user boot.
After the boot completes, edit [path]``/etc/fstab``
 and replace the conventional device names, with their respective labels.
The final [path]``/etc/fstab``
 will look like this:

[source]
----
# Device                Mountpoint      FStype  Options         Dump    Pass#
/dev/label/swap         none            swap    sw              0       0
/dev/label/rootfs       /               ufs     rw              1       1
/dev/label/tmp          /tmp            ufs     rw              2       2
/dev/label/usr          /usr            ufs     rw              2       2
/dev/label/var          /var            ufs     rw              2       2
----

The system can now be rebooted.
If everything went well, it will come up normally and [command]``mount``	  will show:

----
# mount/dev/label/rootfs on / (ufs, local)
devfs on /dev (devfs, local)
/dev/label/tmp on /tmp (ufs, local, soft-updates)
/dev/label/usr on /usr (ufs, local, soft-updates)
/dev/label/var on /var (ufs, local, soft-updates)
----
====


The  {{< manpage "glabel" "8" >}}
 class supports a label type for [acronym]``UFS`` file systems, based on the unique file system id, ``ufsid``.
These labels may be found in [path]``/dev/ufsid``
 and are created automatically during system startup.
It is possible to use `ufsid` labels to mount partitions using [path]``/etc/fstab``
.
Use [command]``glabel
	  status`` to receive a list of file systems and their corresponding `ufsid` labels:

----
% glabel statusName  Status  Components
ufsid/486b6fc38d330916     N/A  ad4s1d
ufsid/486b6fc16926168e     N/A  ad4s1f
----


In the above example, [path]``ad4s1d``
	represents [path]``/var``
, while [path]``ad4s1f``
 represents [path]``/usr``
.
Using the `ufsid` values shown, these partitions may now be mounted with the following entries in [path]``/etc/fstab``
:

[source]
----
/dev/ufsid/486b6fc38d330916        /var        ufs        rw        2      2
/dev/ufsid/486b6fc16926168e        /usr        ufs        rw        2      2
----


Any partitions with `ufsid` labels can be mounted in this way, eliminating the need to manually create permanent labels, while still enjoying the benefits of device name independent mounting.

[[_geom_gjournal]]
== UFS Journaling Through GEOM

(((GEOM)))

(((Journaling)))


Support for journals on [acronym]``UFS`` file systems is available on FreeBSD.
The implementation is provided through the [acronym]``GEOM`` subsystem and is configured using [command]``gjournal``.
Unlike other file system journaling implementations, the [command]``gjournal`` method is block based and not implemented as part of the file system.
It is a [acronym]``GEOM`` extension.

Journaling stores a log of file system transactions, such as changes that make up a complete disk write operation, before meta-data and file writes are committed to the disk.
This transaction log can later be replayed to redo file system transactions, preventing file system inconsistencies.

This method provides another mechanism to protect against data loss and inconsistencies of the file system.
Unlike Soft Updates, which tracks and enforces meta-data updates, and snapshots, which create an image of the file system, a log is stored in disk space specifically for this task.
For better performance, the journal may be stored on another disk.
In this configuration, the journal provider or storage device should be listed after the device to enable journaling on.

The [path]``GENERIC``
 kernel provides support for [command]``gjournal``.
To automatically load the [path]``geom_journal.ko``
 kernel module at boot time, add the following line to [path]``/boot/loader.conf``
:

[source]
----
geom_journal_load="YES"
----


If a custom kernel is used, ensure the following line is in the kernel configuration file:

[source]
----
options	GEOM_JOURNAL
----


Once the module is loaded, a journal can be created on a new file system using the following steps.
In this example, [path]``da4``
 is a new [acronym]``SCSI`` disk:

----
# gjournal load
# gjournal label /dev/da4
----


This will load the module and create a [path]``/dev/da4.journal``
 device node on [path]``/dev/da4``
.

A [acronym]``UFS`` file system may now be created on the journaled device, then mounted on an existing mount point:

----
# newfs -O 2 -J /dev/da4.journal
# mount /dev/da4.journal /mnt
----

[NOTE]
====
In the case of several slices, a journal will be created for each individual slice.
For instance, if [path]``ad4s1``
 and [path]``ad4s2``
 are both slices, then [command]``gjournal`` will create [path]``ad4s1.journal``
 and [path]``ad4s2.journal``
.
====


Journaling may also be enabled on current file systems by using [command]``tunefs``.
However, _always_ make a backup before attempting to alter an existing file system.
In most cases, [command]``gjournal`` will fail if it is unable to create the journal, but this does not protect against data loss incurred as a result of misusing [command]``tunefs``.
Refer to  {{< manpage "gjournal" "8" >}}
 and  {{< manpage "tunefs" "8" >}}
 for more information about these commands.

It is possible to journal the boot disk of a FreeBSD system.
Refer to the article link:/doc/en_US.ISO8859-1/en_US.ISO8859-1/articles/gjournal-desktop[Implementing UFS
	Journaling on a Desktop PC] for detailed instructions.

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]