---
title: "Other File Systems"
---
[[_filesystems]]
= Other File Systems
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images
Tom Rhodes

[[_filesystems_synopsis]]
== Synopsis

(((File Systems)))

(((File Systems Support)))


File systems are an integral part of any operating system.
They allow users to upload and store files, provide access to data, and make hard drives useful.
Different operating systems differ in their native file system.
Traditionally, the native FreeBSD file system has been the Unix File System [acronym]``UFS`` which has been modernized as [acronym]``UFS2``.
Since FreeBSD{nbsp}7.0, the Z File System ([acronym]``ZFS``) is also available as a native file system.
See <<_zfs>> for more information.

In addition to its native file systems, FreeBSD supports a multitude of other file systems so that data from other operating systems can be accessed locally, such as data stored on locally attached [acronym]``USB`` storage devices, flash drives, and hard disks.
This includes support for the Linux(TM)
 Extended File System ([acronym]``EXT``).

There are different levels of FreeBSD support for the various file systems.
Some require a kernel module to be loaded and others may require a toolset to be installed.
Some non-native file system support is full read-write while others are read-only.

After reading this chapter, you will know:

* The difference between native and supported file systems.
* Which file systems are supported by FreeBSD.
* How to enable, configure, access, and make use of non-native file systems.


Before reading this chapter, you should:

* Understand UNIX(R) and <<_basics,FreeBSD basics>>.
* Be familiar with the basics of <<_kernelconfig,kernel configuration and compilation>>.
* Feel comfortable <<_ports,installing software>> in FreeBSD.
* Have some familiarity with <<_disks,disks>>, storage, and device names in FreeBSD.


[[_filesystems_linux]]
== Linux File Systems


FreeBSD provides built-in support for several Linux(TM)
 file systems.
This section demonstrates how to load support for and how to mount the supported Linux(TM)
 file systems.

=== ext2


Kernel support for ext2 file systems has been available since FreeBSD{nbsp}2.2.
In FreeBSD{nbsp}8.x and earlier, the code is licensed under the [acronym]``GPL``.
Since FreeBSD{nbsp}9.0, the code has been rewritten and is now [acronym]``BSD``	licensed.

The  {{< manpage "ext2fs" "5" >}}
 driver allows the FreeBSD kernel to both read and write to ext2 file systems.

[NOTE]
====
This driver can also be used to access ext3 and ext4 file systems.
The  {{< manpage "ext2fs" "5" >}}
 filesystem has full read and write support for ext4 as of FreeBSD{nbsp}12.0-RELEASE.
Additionally, extended attributes and ACLs are also supported, while journalling and encryption are not.
Starting with FreeBSD{nbsp}12.1-RELEASE, a DTrace provider will be available as well.
Prior versions of FreeBSD can access ext4 in read and write mode using [package]#sysutils/fusefs-ext2#
.
====


To access an ext file system, first load the kernel loadable module:

----
# kldload ext2fs
----


Then, mount the ext volume by specifying its FreeBSD partition name and an existing mount point.
This example mounts [path]``/dev/ad1s1``
 on [path]``/mnt``
:

----
# mount -t ext2fs /dev/ad1s1 /mnt
----

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]