---
title: "FreeBSD Basics"
---
[[_basics]]
= FreeBSD Basics
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: ./images

[[_basics_synopsis]]
== Synopsis


This chapter covers the basic commands and functionality of the FreeBSD operating system.
Much of this material is relevant for any UNIX(R)-like operating system.
New FreeBSD users are encouraged to read through this chapter carefully.

After reading this chapter, you will know:

* How to use and configure virtual consoles.
* How to create and manage users and groups on FreeBSD.
* How UNIX(R) file permissions and FreeBSD file flags work.
* The default FreeBSD file system layout.
* The FreeBSD disk organization.
* How to mount and unmount file systems.
* What processes, daemons, and signals are.
* What a shell is, and how to change the default login environment.
* How to use basic text editors.
* What devices and device nodes are.
* How to read manual pages for more information.


[[_consoles]]
== Virtual Consoles and Terminals

(((virtual consoles)))

(((terminals)))

(((console)))


Unless FreeBSD has been configured to automatically start a graphical environment during startup, the system will boot into a command line login prompt, as seen in this example:

----
FreeBSD/amd64 (pc3.example.org) (ttyv0)

login:
----


The first line contains some information about the system.
The `amd64` indicates that the system in this example is running a 64-bit version of FreeBSD.
The hostname is [systemitem]``pc3.example.org``
, and [path]``ttyv0``
 indicates that this is the "`system console`"
.
The second line is the login prompt.

Since FreeBSD is a multiuser system, it needs some way to distinguish between different users.
This is accomplished by requiring every user to log into the system before gaining access to the programs on the system.
Every user has a unique name "`username`"
 and a personal "`password`"
.

To log into the system console, type the username that was configured during system installation, as described in <<_bsdinstall_addusers>>, and press kbd:[Enter]
.
Then enter the password associated with the username and press kbd:[Enter]
.
The password is _not echoed_ for security reasons.

Once the correct password is input, the message of the day ([acronym]``MOTD``) will be displayed followed by a command prompt.
Depending upon the shell that was selected when the user was created, this prompt will be a ``\#``, ``$``, or `%` character.
The prompt indicates that the user is now logged into the FreeBSD system console and ready to try the available commands.

[[_consoles_virtual]]
=== Virtual Consoles


While the system console can be used to interact with the system, a user working from the command line at the keyboard of a FreeBSD system will typically instead log into a virtual console.
This is because system messages are configured by default to display on the system console.
These messages will appear over the command or file that the user is working on, making it difficult to concentrate on the work at hand.

By default, FreeBSD is configured to provide several virtual consoles for inputting commands.
Each virtual console has its own login prompt and shell and it is easy to switch between virtual consoles.
This essentially provides the command line equivalent of having several windows open at the same time in a graphical environment.

The key combinations kbd:[Alt+F1]
	through kbd:[Alt+F8]
	have been reserved by FreeBSD for switching between virtual consoles.
Use kbd:[Alt+F1]
	to switch to the system console ([path]``ttyv0``
), kbd:[Alt+F2]
	to access the first virtual console ([path]``ttyv1``
), kbd:[Alt+F3]
	to access the second virtual console ([path]``ttyv2``
), and so on.
When using [app]``Xorg`` as a graphical console, the combination becomes kbd:[Ctrl+Alt+F1]
 to return to a text-based virtual console.

When switching from one console to the next, FreeBSD manages the screen output.
The result is an illusion of having multiple virtual screens and keyboards that can be used to type commands for FreeBSD to run.
The programs that are launched in one virtual console do not stop running when the user switches to a different virtual console.

Refer to  {{< manpage "kbdcontrol" "1" >}}
,  {{< manpage "vidcontrol" "1" >}}
,  {{< manpage "atkbd" "4" >}}
,  {{< manpage "syscons" "4" >}}
, and  {{< manpage "vt" "4" >}}
 for a more technical description of the FreeBSD console and its keyboard drivers.

In FreeBSD, the number of available virtual consoles is configured in this section of [path]``/etc/ttys``
:

[source]
----
# name    getty                         type  status comments
#
ttyv0   "/usr/libexec/getty Pc"         xterm   on  secure
# Virtual terminals
ttyv1   "/usr/libexec/getty Pc"         xterm   on  secure
ttyv2   "/usr/libexec/getty Pc"         xterm   on  secure
ttyv3   "/usr/libexec/getty Pc"         xterm   on  secure
ttyv4   "/usr/libexec/getty Pc"         xterm   on  secure
ttyv5   "/usr/libexec/getty Pc"         xterm   on  secure
ttyv6   "/usr/libexec/getty Pc"         xterm   on  secure
ttyv7   "/usr/libexec/getty Pc"         xterm   on  secure
ttyv8   "/usr/X11R6/bin/xdm -nodaemon"  xterm   off secure
----


To disable a virtual console, put a comment symbol (``\#``) at the beginning of the line representing that virtual console.
For example, to reduce the number of available virtual consoles from eight to four, put a `\#` in front of the last four lines representing virtual consoles [path]``ttyv5``
	through [path]``ttyv8``
. _Do not_ comment out the line for the system console [path]``ttyv0``
.
Note that the last virtual console ([path]``ttyv8``
) is used to access the graphical environment if [app]``Xorg``	has been installed and configured as described in <<_x11>>.

For a detailed description of every column in this file and the available options for the virtual consoles, refer to  {{< manpage "ttys" "5" >}}
.

[[_consoles_singleuser]]
=== Single User Mode


The FreeBSD boot menu provides an option labelled as "`Boot Single User`"
.
If this option is selected, the system will boot into a special mode known as "`single user mode`"
.
This mode is typically used to repair a system that will not boot or to reset the [username]``root``
 password when it is not known.
While in single user mode, networking and other virtual consoles are not available.
However, full [username]``root``
 access to the system is available, and by default, the [username]``root``
 password is not needed.
For these reasons, physical access to the keyboard is needed to boot into this mode and determining who has physical access to the keyboard is something to consider when securing a FreeBSD system.

The settings which control single user mode are found in this section of [path]``/etc/ttys``
:

[source]
----
# name  getty                           type  status  comments
#
# If console is marked "insecure", then init will ask for the root password
# when going to single-user mode.
console none                            unknown  off  secure
----


By default, the status is set to ``secure``.
This assumes that who has physical access to the keyboard is either not important or it is controlled by a physical security policy.
If this setting is changed to ``insecure``, the assumption is that the environment itself is insecure because anyone can access the keyboard.
When this line is changed to ``insecure``, FreeBSD will prompt for the [username]``root``
 password when a user selects to boot into single user mode.

[NOTE]
====
__Be careful when changing this setting to
	    ``__insecure__``__!  If the [username]``root``
 password is forgotten, booting into single user mode is still possible, but may be difficult for someone who is not familiar with the FreeBSD booting process.
====

[[_consoles_vidcontrol]]
=== Changing Console Video Modes


The FreeBSD console default video mode may be adjusted to 1024x768, 1280x1024, or any other size supported by the graphics chip and monitor.
To use a different video mode load the `VESA` module:

----
# kldload vesa
----


To determine which video modes are supported by the hardware, use  {{< manpage "vidcontrol" "1" >}}
.
To get a list of supported video modes issue the following:

----
# vidcontrol -i mode
----


The output of this command lists the video modes that are supported by the hardware.
To select a new video mode, specify the mode using  {{< manpage "vidcontrol" "1" >}}
 as the [username]``root``
 user:

----
# vidcontrol MODE_279
----


If the new video mode is acceptable, it can be permanently set on boot by adding it to [path]``/etc/rc.conf``
:

[source]
----
allscreens_flags="MODE_279"
----

[[_users_synopsis]]
== Users and Basic Account Management


FreeBSD allows multiple users to use the computer at the same time.
While only one user can sit in front of the screen and use the keyboard at any one time, any number of users can log in to the system through the network.
To use the system, each user should have their own user account.

This chapter describes:

* The different types of user accounts on a FreeBSD system.
* How to add, remove, and modify user accounts.
* How to set limits to control the resources that users and groups are allowed to access.
* How to create groups and add users as members of a group.


[[_users_introduction]]
=== Account Types


Since all access to the FreeBSD system is achieved using accounts and all processes are run by users, user and account management is important.

There are three main types of accounts: system accounts, user accounts, and the superuser account.

[[_users_system]]
==== System Accounts

(((accounts,system)))


System accounts are used to run services such as DNS, mail, and web servers.
The reason for this is security; if all services ran as the superuser, they could act without restriction.

(((accounts,operator)))


Examples of system accounts are [username]``daemon``
, [username]``operator``
, [username]``bind``
, [username]``news``
, and [username]``www``
.

[username]``nobody``
 is the generic unprivileged system account.
However, the more services that use [username]``nobody``
, the more files and processes that user will become associated with, and hence the more privileged that user becomes.

[[_users_user]]
==== User Accounts

(((accounts,user)))


User accounts are assigned to real people and are used to log in and use the system.
Every person accessing the system should have a unique user account.
This allows the administrator to find out who is doing what and prevents users from clobbering the settings of other users.

Each user can set up their own environment to accommodate their use of the system, by configuring their default shell, editor, key bindings, and language settings.

Every user account on a FreeBSD system has certain information associated with it:

User name::
The user name is typed at the 
prompt.
Each user must have a unique user name.
There are a number of rules for creating valid user names which are documented in  {{< manpage "passwd" "5" >}}
.
It is recommended to use user names that consist of eight or fewer, all lower case characters in order to maintain backwards compatibility with applications.

Password::
Each account has an associated password.

User ID ([acronym]``UID``)::
The User ID ([acronym]``UID``) is a number used to uniquely identify the user to the FreeBSD system.
Commands that allow a user name to be specified will first convert it to the [acronym]``UID``.
It is recommended to use a UID less than 65535, since higher values may cause compatibility issues with some software.

Group ID ([acronym]``GID``)::
The Group ID ([acronym]``GID``) is a number used to uniquely identify the primary group that the user belongs to.
Groups are a mechanism for controlling access to resources based on a user's [acronym]``GID`` rather than their [acronym]``UID``.
This can significantly reduce the size of some configuration files and allows users to be members of more than one group.
It is recommended to use a GID of 65535 or lower as higher GIDs may break some software.

Login class::
Login classes are an extension to the group mechanism that provide additional flexibility when tailoring the system to different users.
Login classes are discussed further in <<_users_limiting>>.

Password change time::
By default, passwords do not expire.
However, password expiration can be enabled on a per-user basis, forcing some or all users to change their passwords after a certain amount of time has elapsed.

Account expiration time::
By default, FreeBSD does not expire accounts.
When creating accounts that need a limited lifespan, such as student accounts in a school, specify the account expiry date using  {{< manpage "pw" "8" >}}
.
After the expiry time has elapsed, the account cannot be used to log in to the system, although the account's directories and files will remain.

User's full name::
The user name uniquely identifies the account to FreeBSD, but does not necessarily reflect the user's real name.
Similar to a comment, this information can contain spaces, uppercase characters, and be more than 8 characters long.

Home directory::
The home directory is the full path to a directory on the system.
This is the user's starting directory when the user logs in.
A common convention is to put all user home directories under [path]``/home/username``
or [path]``/usr/home/username``
.
Each user stores their personal files and subdirectories in their own home directory.

User shell::
The shell provides the user's default environment for interacting with the system.
There are many different kinds of shells and experienced users will have their own preferences, which can be reflected in their account settings.


[[_users_superuser]]
==== The Superuser Account


The superuser account, usually called [username]``root``
, is used to manage the system with no limitations on privileges.
For this reason, it should not be used for day-to-day tasks like sending and receiving mail, general exploration of the system, or programming.

The superuser, unlike other user accounts, can operate without limits, and misuse of the superuser account may result in spectacular disasters.
User accounts are unable to destroy the operating system by mistake, so it is recommended to login as a user account and to only become the superuser when a command requires extra privilege.

Always double and triple-check any commands issued as the superuser, since an extra space or missing character can mean irreparable data loss.

There are several ways to gain superuser privilege.
While one can log in as [username]``root``
, this is highly discouraged.

Instead, use  {{< manpage "su" "1" >}}
 to become the superuser.
If `-` is specified when running this command, the user will also inherit the root user's environment.
The user running this command must be in the [groupname]``wheel``
 group or else the command will fail.
The user must also know the password for the [username]``root``
 user account.

In this example, the user only becomes superuser in order to run [command]``make install`` as this step requires superuser privilege.
Once the command completes, the user types [command]``exit`` to leave the superuser account and return to the privilege of their user account.

.Install a Program As the Superuser
====
----
% configure
% make
% su -Password:
# make install
# exit
% 
----
====


The built-in  {{< manpage "su" "1" >}}
 framework works well for single systems or small networks with just one system administrator.
An alternative is to install the [package]#security/sudo#
 package or port.
This software provides activity logging and allows the administrator to configure which users can run which commands as the superuser.

[[_users_modifying]]
=== Managing Accounts

(((accounts,modifying)))


FreeBSD provides a variety of different commands to manage user accounts.
The most common commands are summarized in <<_users_modifying_utilities>>, followed by some examples of their usage.
See the manual page for each utility for more details and usage examples.
[[_users_modifying_utilities]]
.Utilities for Managing User Accounts
[cols="1,1", frame="none", options="header"]
|===
| Command
| Summary

| {{< manpage "adduser" "8" >}}
|
The recommended command-line application for
		adding new users.

| {{< manpage "rmuser" "8" >}}
|
The recommended command-line application for
		removing users.

| {{< manpage "chpass" "1" >}}
|
A flexible tool for changing user database
		information.

| {{< manpage "passwd" "1" >}}
|
The command-line tool to change user
		passwords.

| {{< manpage "pw" "8" >}}
|
A powerful and flexible tool for modifying all
		aspects of user accounts.
|===

[[_users_adduser]]
==== adduser

(((adduser)))

(((/usr/share/skel)))

(((skeleton directory)))


The recommended program for adding new users is  {{< manpage "adduser" "8" >}}
.
When a new user is added, this program automatically updates [path]``/etc/passwd``
 and [path]``/etc/group``
.
It also creates a home directory for the new user, copies in the default configuration files from [path]``/usr/share/skel``
, and can optionally mail the new user a welcome message.
This utility must be run as the superuser.

The  {{< manpage "adduser" "8" >}}
 utility is interactive and walks through the steps for creating a new user account.
As seen in <<_users_modifying_adduser>>, either input the required information or press kbd:[Return]
	  to accept the default value shown in square brackets.
In this example, the user has been invited into the [groupname]``wheel``
 group, allowing them to become the superuser with  {{< manpage "su" "1" >}}
.
When finished, the utility will prompt to either create another user or to exit.

[[_users_modifying_adduser]]
.Adding a User on FreeBSD
====
----
# adduserUsername:jruFull name:J. Random UserUid (Leave empty for default):
Login group [jru]:
Login group is jru. Invite jru into other groups? []:wheelLogin class [default]:
Shell (sh csh tcsh zsh nologin) [sh]:zshHome directory [/home/jru]:
Home directory permissions (Leave empty for default):
Use password-based authentication? [yes]:
Use an empty password? (yes/no) [no]:
Use a random password? (yes/no) [no]:
Enter password:
Enter password again:
Lock out the account after creation? [no]:
Username   : jru
Password   : ****
Full Name  : J. Random User
Uid        : 1001
Class      :
Groups     : jru wheel
Home       : /home/jru
Shell      : /usr/local/bin/zsh
Locked     : no
OK? (yes/no):yesadduser: INFO: Successfully added (jru) to the user database.
Add another user? (yes/no):noGoodbye!
# 
----
====

[NOTE]
====
Since the password is not echoed when typed, be careful to not mistype the password when creating the user account.
====

[[_users_rmuser]]
==== rmuser

(((rmuser)))

(((accounts,removing)))


To completely remove a user from the system, run  {{< manpage "rmuser" "8" >}}
 as the superuser.
This command performs the following steps:


. Removes the user's  {{< manpage "crontab" "1" >}} entry, if one exists.
. Removes any  {{< manpage "at" "1" >}} jobs belonging to the user.
. Kills all processes owned by the user.
. Removes the user from the system's local password file.
. Optionally removes the user's home directory, if it is owned by the user.
. Removes the incoming mail files belonging to the user from [path]``/var/mail`` .
. Removes all files owned by the user from temporary file storage areas such as [path]``/tmp`` .
. Finally, removes the username from all groups to which it belongs in [path]``/etc/group`` . If a group becomes empty and the group name is the same as the username, the group is removed. This complements the per-user unique groups created by  {{< manpage "adduser" "8" >}} .

 {{< manpage "rmuser" "8" >}}
 cannot be used to remove superuser accounts since that is almost always an indication of massive destruction.

By default, an interactive mode is used, as shown in the following example.

.[command]``rmuser`` Interactive AccountRemoval
====
----
# rmuser jruMatching password entry:
jru:*:1001:1001::0:0:J. Random User:/home/jru:/usr/local/bin/zsh
Is this the entry you wish to remove?yRemove user's home directory (/home/jru)?yRemoving user (jru): mailspool home passwd.
# 
----
====

[[_users_chpass]]
==== chpass


Any user can use  {{< manpage "chpass" "1" >}}
 to change their default shell and personal information associated with their user account.
The superuser can use this utility to change additional account information for any user.

When passed no options, aside from an optional username,  {{< manpage "chpass" "1" >}}
 displays an editor containing user information.
When the user exits from the editor, the user database is updated with the new information.

[NOTE]
====
This utility will prompt for the user's password when exiting the editor, unless the utility is run as the superuser.
====


In <<_users_modifying_chpass_su>>, the superuser has typed [command]``chpass jru`` and is now viewing the fields that can be changed for this user.
If [username]``jru``
 runs this command instead, only the last six fields will be displayed and available for editing.
This is shown in <<_users_modifying_chpass_ru>>.

[[_users_modifying_chpass_su]]
.Using [command]``chpass`` asSuperuser
====
----
#Changing user database information for jru.
Login: jru
Password: *
Uid [#]: 1001
Gid [# or name]: 1001
Change [month day year]:
Expire [month day year]:
Class:
Home directory: /home/jru
Shell: /usr/local/bin/zsh
Full Name: J. Random User
Office Location:
Office Phone:
Home Phone:
Other information:
----
====

[[_users_modifying_chpass_ru]]
.Using [command]``chpass`` as RegularUser
====
----
#Changing user database information for jru.
Shell: /usr/local/bin/zsh
Full Name: J. Random User
Office Location:
Office Phone:
Home Phone:
Other information:
----
====

[NOTE]
====
The commands  {{< manpage "chfn" "1" >}}
 and  {{< manpage "chsh" "1" >}}
 are links to  {{< manpage "chpass" "1" >}}
, as are  {{< manpage "ypchpass" "1" >}}
,  {{< manpage "ypchfn" "1" >}}
, and  {{< manpage "ypchsh" "1" >}}
.
Since [acronym]``NIS`` support is automatic, specifying the `yp` before the command is not necessary.
How to configure NIS is covered in <<_network_servers>>.
====

[[_users_passwd]]
==== passwd

(((passwd)))

(((accounts,changing password)))


Any user can easily change their password using  {{< manpage "passwd" "1" >}}
.
To prevent accidental or unauthorized changes, this command will prompt for the user's original password before a new password can be set:

.Changing Your Password
====
----
% passwdChanging local password for jru.
Old password:
New password:
Retype new password:
passwd: updating the database...
passwd: done
----
====


The superuser can change any user's password by specifying the username when running  {{< manpage "passwd" "1" >}}
.
When this utility is run as the superuser, it will not prompt for the user's current password.
This allows the password to be changed when a user cannot remember the original password.

.Changing Another User's Password as theSuperuser
====
----
# passwd jruChanging local password for jru.
New password:
Retype new password:
passwd: updating the database...
passwd: done
----
====

[NOTE]
====
As with  {{< manpage "chpass" "1" >}}
,  {{< manpage "yppasswd" "1" >}}
 is a link to  {{< manpage "passwd" "1" >}}
, so [acronym]``NIS`` works with either command.
====

[[_users_pw]]
==== pw


The  {{< manpage "pw" "8" >}}
 utility can create, remove, modify, and display users and groups.
It functions as a front end to the system user and group files.  {{< manpage "pw" "8" >}}
	  has a very powerful set of command line options that make it suitable for use in shell scripts, but new users may find it more complicated than the other commands presented in this section.

[[_users_groups]]
=== Managing Groups

(((groups)))

(((/etc/groups)))

(((accounts,groups)))


A group is a list of users.
A group is identified by its group name and [acronym]``GID``.
In FreeBSD, the kernel uses the [acronym]``UID`` of a process, and the list of groups it belongs to, to determine what the process is allowed to do.
Most of the time, the [acronym]``GID`` of a user or process usually means the first group in the list.

The group name to [acronym]``GID`` mapping is listed in [path]``/etc/group``
.
This is a plain text file with four colon-delimited fields.
The first field is the group name, the second is the encrypted password, the third the [acronym]``GID``, and the fourth the comma-delimited list of members.
For a more complete description of the syntax, refer to  {{< manpage "group" "5" >}}
.

The superuser can modify [path]``/etc/group``
	using a text editor.
Alternatively,  {{< manpage "pw" "8" >}}
 can be used to add and edit groups.
For example, to add a group called [groupname]``teamtwo``
 and then confirm that it exists:

.Adding a Group Using  {{< manpage "pw" "8" >}}
====
----
# pw groupadd teamtwo
# pw groupshow teamtwoteamtwo:*:1100:
----
====


In this example, `1100` is the [acronym]``GID`` of [groupname]``teamtwo``
.
Right now, [groupname]``teamtwo``
 has no members.
This command will add [username]``jru``
 as a member of [groupname]``teamtwo``
.

.Adding User Accounts to a New Group Using{{< manpage "pw" "8" >}}
====
----
# pw groupmod teamtwo -M jru
# pw groupshow teamtwoteamtwo:*:1100:jru
----
====


The argument to [option]``-M`` is a comma-delimited list of users to be added to a new (empty) group or to replace the members of an existing group.
To the user, this group membership is different from (and in addition to) the user's primary group listed in the password file.
This means that the user will not show up as a member when using [option]``groupshow`` with  {{< manpage "pw" "8" >}}
, but will show up when the information is queried via  {{< manpage "id" "1" >}}
 or a similar tool.
When  {{< manpage "pw" "8" >}}
 is used to add a user to a group, it only manipulates [path]``/etc/group``
 and does not attempt to read additional data from [path]``/etc/passwd``
.

.Adding a New Member to a Group Using  {{< manpage "pw" "8" >}}
====
----
# pw groupmod teamtwo -m db
# pw groupshow teamtwoteamtwo:*:1100:jru,db
----
====


In this example, the argument to [option]``-m`` is a comma-delimited list of users who are to be added to the group.
Unlike the previous example, these users are appended to the group and do not replace existing users in the group.

.Using  {{< manpage "id" "1" >}}to Determine Group Membership
====
----
% id jruuid=1001(jru) gid=1001(jru) groups=1001(jru), 1100(teamtwo)
----
====


In this example, [username]``jru``
 is a member of the groups [groupname]``jru``
 and [groupname]``teamtwo``
.

For more information about this command and the format of [path]``/etc/group``
, refer to  {{< manpage "pw" "8" >}}
 and  {{< manpage "group" "5" >}}
.

== Permissions


In FreeBSD, every file and directory has an associated set of permissions and several utilities are available for viewing and modifying these permissions.
Understanding how permissions work is necessary to make sure that users are able to access the files that they need and are unable to improperly access the files used by the operating system or owned by other users.

This section discusses the traditional UNIX(R) permissions used in FreeBSD.
For finer grained file system access control, refer to <<_fs_acl>>.

In UNIX(R), basic permissions are assigned using three types of access: read, write, and execute.
These access types are used to determine file access to the file's owner, group, and others (everyone else).  The read, write, and execute permissions can be represented as the letters ``r``, ``w``, and ``x``.
They can also be represented as binary numbers as each permission is either on or off (``0``).  When represented as a number, the order is always read as ``rwx``, where `r` has an on value of ``4``, `w` has an on value of `2` and `x` has an on value of ``1``.

Table 4.1 summarizes the possible numeric and alphabetic possibilities.
When reading the "`Directory
	Listing`"
 column, a `-` is used to represent a permission that is set to off.

(((permissions)))

(((file permissions)))

.UNIX(R) Permissions
[cols="1,1,1", frame="none", options="header"]
|===
| Value
| Permission
| Directory Listing

|0
|No read, no write, no execute
|``---``

|1
|No read, no write, execute
|``--x``

|2
|No read, write, no execute
|``-w-``

|3
|No read, write, execute
|``-wx``

|4
|Read, no write, no execute
|``r--``

|5
|Read, no write, execute
|``r-x``

|6
|Read, write, no execute
|``rw-``

|7
|Read, write, execute
|``rwx``
|===

(((ls1)))

(((directories)))


Use the [option]``-l`` argument to  {{< manpage "ls" "1" >}}
 to view a long directory listing that includes a column of information about a file's permissions for the owner, group, and everyone else.
For example, a [command]``ls -l`` in an arbitrary directory may show:

----
% ls -ltotal 530
-rw-r--r--  1 root  wheel     512 Sep  5 12:31 myfile
-rw-r--r--  1 root  wheel     512 Sep  5 12:31 otherfile
-rw-r--r--  1 root  wheel    7680 Sep  5 12:31 email.txt
----


The first (leftmost) character in the first column indicates whether this file is a regular file, a directory, a special character device, a socket, or any other special pseudo-file device.
In this example, the `-` indicates a regular file.
The next three characters, `rw-` in this example, give the permissions for the owner of the file.
The next three characters, ``r--``, give the permissions for the group that the file belongs to.
The final three characters, ``r--``, give the permissions for the rest of the world.
A dash means that the permission is turned off.
In this example, the permissions are set so the owner can read and write to the file, the group can read the file, and the rest of the world can only read the file.
According to the table above, the permissions for this file would be ``644``, where each digit represents the three parts of the file's permission.

How does the system control permissions on devices? FreeBSD treats most hardware devices as a file that programs can open, read, and write data to.
These special device files are stored in [path]``/dev/``
.

Directories are also treated as files.
They have read, write, and execute permissions.
The executable bit for a directory has a slightly different meaning than that of files.
When a directory is marked executable, it means it is possible to change into that directory using  {{< manpage "cd" "1" >}}
.
This also means that it is possible to access the files within that directory, subject to the permissions on the files themselves.

In order to perform a directory listing, the read permission must be set on the directory.
In order to delete a file that one knows the name of, it is necessary to have write _and_ execute permissions to the directory containing the file.

There are more permission bits, but they are primarily used in special circumstances such as setuid binaries and sticky directories.
For more information on file permissions and how to set them, refer to  {{< manpage "chmod" "1" >}}
.

=== Symbolic Permissions
= Symbolic Permissions
:imagesdir: ./images
Tom Rhodes

(((permissions,symbolic)))


Symbolic permissions use characters instead of octal values to assign permissions to files or directories.
Symbolic permissions use the syntax of (who) (action) (permissions), where the following values are available:

[cols="1,1,1", frame="none", options="header"]
|===
| Option
| Letter
| Represents


|(who)
|u
|User

|(who)
|g
|Group owner

|(who)
|o
|Other

|(who)
|a
|All ("`world`"
)

|(action)
|+
|Adding permissions

|(action)
|-
|Removing permissions

|(action)
|=
|Explicitly set permissions

|(permissions)
|r
|Read

|(permissions)
|w
|Write

|(permissions)
|x
|Execute

|(permissions)
|t
|Sticky bit

|(permissions)
|s
|Set UID or GID
|===


These values are used with  {{< manpage "chmod" "1" >}}
, but with letters instead of numbers.
For example, the following command would block other users from accessing [replaceable]``FILE``:

----
% chmod go= FILE
----


A comma separated list can be provided when more than one set of changes to a file must be made.
For example, the following command removes the group and "`world`"
 write permission on [replaceable]``FILE``, and adds the execute permissions for everyone:

----
% chmod go-w,a+x FILE
----

=== FreeBSD File Flags
= FreeBSD File Flags
:imagesdir: ./images
Tom Rhodes


In addition to file permissions, FreeBSD supports the use of "`file flags`"
.
These flags add an additional level of security and control over files, but not directories.
With file flags, even [username]``root``
 can be prevented from removing or altering files.

File flags are modified using  {{< manpage "chflags" "1" >}}
.
For example, to enable the system undeletable flag on the file [path]``file1``
, issue the following command:

----
# chflags sunlink file1
----


To disable the system undeletable flag, put a "`no`"
 in front of the [option]``sunlink``:

----
# chflags nosunlink file1
----


To view the flags of a file, use [option]``-lo`` with  {{< manpage "ls" "1" >}}
:

----
# ls -lo file1
----

[source]
----
-rw-r--r--  1 trhodes  trhodes  sunlnk 0 Mar  1 05:54 file1
----


Several file flags may only be added or removed by the [username]``root``
 user.
In other cases, the file owner may set its file flags.
Refer to  {{< manpage "chflags" "1" >}}
 and  {{< manpage "chflags" "2" >}}
 for more information.

=== The setuid, setgid, and sticky Permissions
= The setuid,
	  setgid, and sticky
	  Permissions
:imagesdir: ./images
Tom Rhodes


Other than the permissions already discussed, there are three other specific settings that all administrators should know about.
They are the ``setuid``, ``setgid``, and `sticky`	permissions.

These settings are important for some UNIX(R) operations as they provide functionality not normally granted to normal users.
To understand them, the difference between the real user ID and effective user ID must be noted.

The real user ID is the [acronym]``UID`` who owns or starts the process.
The effective [acronym]``UID``	is the user ID the process runs as.
As an example,  {{< manpage "passwd" "1" >}}
 runs with the real user ID when a user changes their password.
However, in order to update the password database, the command runs as the effective ID of the [username]``root``
 user.
This allows users to change their passwords without seeing a `Permission Denied` error.

The setuid permission may be set by prefixing a permission set with the number four (4) as shown in the following example:

----
# chmod 4755 suidexample.sh
----


The permissions on [path]``suidexample.sh``
	now look like the following:

[source]
----
-rwsr-xr-x   1 trhodes  trhodes    63 Aug 29 06:36 suidexample.sh
----


Note that a `s` is now part of the permission set designated for the file owner, replacing the executable bit.
This allows utilities which need elevated permissions, such as  {{< manpage "passwd" "1" >}}
.

[NOTE]
====
The `nosuid` {{< manpage "mount" "8" >}}
 option will cause such binaries to silently fail without alerting the user.
That option is not completely reliable as a `nosuid` wrapper may be able to circumvent it.
====


To view this in real time, open two terminals.
On one, type [command]``passwd`` as a normal user.
While it waits for a new password, check the process table and look at the user information for  {{< manpage "passwd" "1" >}}
:

In terminal A:

----
Changing local password for trhodes
Old Password:
----


In terminal B:

----
# ps aux | grep passwd
----

----
trhodes  5232  0.0  0.2  3420  1608   0  R+    2:10AM   0:00.00 grep passwd
root     5211  0.0  0.2  3620  1724   2  I+    2:09AM   0:00.01 passwd
----


Although  {{< manpage "passwd" "1" >}}
 is run as a normal user, it is using the effective [acronym]``UID`` of [username]``root``
.

The `setgid` permission performs the same function as the `setuid` permission; except that it alters the group settings.
When an application or utility executes with this setting, it will be granted the permissions based on the group that owns the file, not the user who started the process.

To set the `setgid` permission on a file, provide  {{< manpage "chmod" "1" >}}
 with a leading two (2):

----
# chmod 2755 sgidexample.sh
----


In the following listing, notice that the `s` is now in the field designated for the group permission settings:

----
-rwxr-sr-x   1 trhodes  trhodes    44 Aug 31 01:49 sgidexample.sh
----

[NOTE]
====
In these examples, even though the shell script in question is an executable file, it will not run with a different [acronym]``EUID`` or effective user ID.
This is because shell scripts may not access the  {{< manpage "setuid" "2" >}}
 system calls.
====


The `setuid` and `setgid` permission bits may lower system security, by allowing for elevated permissions.
The third special permission, the ``sticky bit``, can strengthen the security of a system.

When the `sticky bit` is set on a directory, it allows file deletion only by the file owner.
This is useful to prevent file deletion in public directories, such as [path]``/tmp``
, by users who do not own the file.
To utilize this permission, prefix the permission set with a one (1):

----
# chmod 1777 /tmp
----


The `sticky bit` permission will display as a `t` at the very end of the permission set:

----
# ls -al / | grep tmp
----

----
drwxrwxrwt  10 root  wheel         512 Aug 31 01:49 tmp
----

[[_dirstructure]]
== Directory Structure


The FreeBSD directory hierarchy is fundamental to obtaining an overall understanding of the system.
The most important directory is root or, "`/`"
.
This directory is the first one mounted at boot time and it contains the base system necessary to prepare the operating system for multi-user operation.
The root directory also contains mount points for other file systems that are mounted during the transition to multi-user operation.

A mount point is a directory where additional file systems can be grafted onto a parent file system (usually the root file system).  This is further described in <<_disk_organization>>.
Standard mount points include [path]``/usr/``
, [path]``/var/``
, [path]``/tmp/``
, [path]``/mnt/``
, and [path]``/cdrom/``
.
These directories are usually referenced to entries in [path]``/etc/fstab``
.
This file is a table of various file systems and mount points and is read by the system.
Most of the file systems in [path]``/etc/fstab``
 are mounted automatically at boot time from the script  {{< manpage "rc" "8" >}}
 unless their entry includes [option]``noauto``.
Details can be found in <<_disks_fstab>>.

A complete description of the file system hierarchy is available in  {{< manpage "hier" "7" >}}
.
The following table provides a brief overview of the most common directories.



[cols="1,1", frame="none", options="header"]
|===
| Directory
| Description


|[path]``/``
|
Root directory of the file system.

|[path]``/bin/``
|
User utilities fundamental to both single-user
		and multi-user environments.

|[path]``/boot/``
|
Programs and configuration files used during
		operating system bootstrap.

|[path]``/boot/defaults/``
|
Default boot configuration files.  Refer to {{< manpage "loader.conf" "5" >}}
 for details.

|[path]``/dev/``
|
Device nodes.  Refer to  {{< manpage "intro" "4" >}}
 for
		details.

|[path]``/etc/``
|
System configuration files and scripts.

|[path]``/etc/defaults/``
|
Default system configuration files.  Refer to {{< manpage "rc" "8" >}}
 for details.

|[path]``/etc/mail/``
|
Configuration files for mail transport agents
		such as  {{< manpage "sendmail" "8" >}}
.

|[path]``/etc/periodic/``
|
Scripts that run daily, weekly, and monthly,
		via  {{< manpage "cron" "8" >}}
.  Refer to  {{< manpage "periodic" "8" >}}
 for
		details.

|[path]``/etc/ppp/``
| {{< manpage "ppp" "8" >}}
 configuration files.

|[path]``/mnt/``
|
Empty directory commonly used by system
		administrators as a temporary mount point.

|[path]``/proc/``
|
Process file system.  Refer to  {{< manpage "procfs" "5" >}}
, {{< manpage "mount_procfs" "8" >}}
 for details.

|[path]``/rescue/``
|
Statically linked programs for emergency
		recovery as described in  {{< manpage "rescue" "8" >}}
.

|[path]``/root/``
|
Home directory for the[username]``root``

		account.

|[path]``/sbin/``
|
System programs and administration utilities
		fundamental to both single-user and multi-user
		environments.

|[path]``/tmp/``
|
Temporary files which are usually__not__ preserved across a system
		reboot.  A memory-based file system is often mounted
		at [path]``/tmp``
.  This can be automated
		using the tmpmfs-related variables of  {{< manpage "rc.conf" "5" >}}

		or with an entry in [path]``/etc/fstab``
;
		refer to  {{< manpage "mdmfs" "8" >}}
 for details.

|[path]``/usr/``
|
The majority of user utilities and
		applications.

|[path]``/usr/bin/``
|
Common utilities, programming tools, and
		applications.

|[path]``/usr/include/``
|
Standard C include files.

|[path]``/usr/lib/``
|
Archive libraries.

|[path]``/usr/libdata/``
|
Miscellaneous utility data files.

|[path]``/usr/libexec/``
|
System daemons and system utilities executed
		by other programs.

|[path]``/usr/local/``
|
Local executables and libraries.  Also used as
		the default destination for the FreeBSD ports framework.
		Within[path]``/usr/local``
, the
		general layout sketched out by  {{< manpage "hier" "7" >}}
 for[path]``/usr``
 should be
		used.  Exceptions are the man directory, which is
		directly under [path]``/usr/local``
 rather than
		under [path]``/usr/local/share``
, and
		the ports documentation is in [path]``share/doc/port``
.

|[path]``/usr/obj/``
|
Architecture-specific target tree produced by
		building the [path]``/usr/src``

		tree.

|[path]``/usr/ports/``
|
The FreeBSD Ports Collection (optional).

|[path]``/usr/sbin/``
|
System daemons and system utilities executed
		by users.

|[path]``/usr/share/``
|
Architecture-independent files.

|[path]``/usr/src/``
|
BSD and/or local source files.

|[path]``/var/``
|
Multi-purpose log, temporary, transient, and
		spool files.  A memory-based file system is sometimes
		mounted at[path]``/var``
.  This can
		be automated using the varmfs-related variables in {{< manpage "rc.conf" "5" >}}
 or with an entry in[path]``/etc/fstab``
; refer to {{< manpage "mdmfs" "8" >}}
 for details.

|[path]``/var/log/``
|
Miscellaneous system log files.

|[path]``/var/mail/``
|
User mailbox files.

|[path]``/var/spool/``
|
Miscellaneous printer and mail system spooling
		directories.

|[path]``/var/tmp/``
|
Temporary files which are usually preserved
		across a system reboot, unless[path]``/var``
 is a
		memory-based file system.

|[path]``/var/yp/``
|
NIS maps.
|===

== Disk Organization


The smallest unit of organization that FreeBSD uses to find files is the filename.
Filenames are case-sensitive, which means that [path]``readme.txt``
 and [path]``README.TXT``
 are two separate files.
FreeBSD does not use the extension of a file to determine whether the file is a program, document, or some other form of data.

Files are stored in directories.
A directory may contain no files, or it may contain many hundreds of files.
A directory can also contain other directories, allowing a hierarchy of directories within one another in order to organize data.

Files and directories are referenced by giving the file or directory name, followed by a forward slash, ``/``, followed by any other directory names that are necessary.
For example, if the directory [path]``foo``
 contains a directory [path]``bar``
 which contains the file [path]``readme.txt``
, the full name, or [term]_path_
, to the file is [path]``foo/bar/readme.txt``
.
Note that this is different from Windows(TM)
 which uses `\` to separate file and directory names.
FreeBSD does not use drive letters, or other drive names in the path.
For example, one would not type [path]``c:\foo\bar\readme.txt``
 on FreeBSD.

Directories and files are stored in a file system.
Each file system contains exactly one directory at the very top level, called the [term]_root directory_
 for that file system.
This root directory can contain other directories.
One file system is designated the [term]_root file system_
 or ``/``.
Every other file system is [term]_mounted_
 under the root file system.
No matter how many disks are on the FreeBSD system, every directory appears to be part of the same disk.

Consider three file systems, called ``A``, ``B``, and ``C``.
Each file system has one root directory, which contains two other directories, called ``A1``, `A2` (and likewise ``B1``, `B2` and ``C1``, ``C2``).

Call `A` the root file system.
If  {{< manpage "ls" "1" >}}
 is used to view the contents of this directory, it will show two subdirectories, `A1` and ``A2``.
The directory tree looks like this:



image::basics/example-dir1[]


A file system must be mounted on to a directory in another file system.
When mounting file system `B` on to the directory ``A1``, the root directory of `B` replaces ``A1``, and the directories in `B` appear accordingly:



image::basics/example-dir2[]


Any files that are in the `B1` or `B2` directories can be reached with the path [path]``/A1/B1``
 or [path]``/A1/B2``
 as necessary.
Any files that were in [path]``/A1``
 have been temporarily hidden.
They will reappear if `B` is [term]_unmounted_
 from ``A``.

If `B` had been mounted on `A2` then the diagram would look like this:



image::basics/example-dir3[]


and the paths would be [path]``/A2/B1``
 and [path]``/A2/B2``
 respectively.

File systems can be mounted on top of one another.
Continuing the last example, the `C` file system could be mounted on top of the `B1` directory in the `B` file system, leading to this arrangement:



image::basics/example-dir4[]


Or `C` could be mounted directly on to the `A` file system, under the `A1` directory:



image::basics/example-dir5[]


It is entirely possible to have one large root file system, and not need to create any others.
There are some drawbacks to this approach, and one advantage.

.Benefits of Multiple File Systems
* Different file systems can have different [term]_mount options_ . For example, the root file system can be mounted read-only, making it impossible for users to inadvertently delete or edit a critical file. Separating user-writable file systems, such as [path]``/home`` , from other file systems allows them to be mounted [term]_nosuid_ . This option prevents the [term]_suid_ /[term]_guid_ bits on executables stored on the file system from taking effect, possibly improving security.
* FreeBSD automatically optimizes the layout of files on a file system, depending on how the file system is being used. So a file system that contains many small files that are written frequently will have a different optimization to one that contains fewer, larger files. By having one big file system this optimization breaks down.
* FreeBSD's file systems are robust if power is lost. However, a power loss at a critical point could still damage the structure of the file system. By splitting data over multiple file systems it is more likely that the system will still come up, making it easier to restore from backup as necessary.


.Benefit of a Single File System
* File systems are a fixed size. If you create a file system when you install FreeBSD and give it a specific size, you may later discover that you need to make the partition bigger. This is not easily accomplished without backing up, recreating the file system with the new size, and then restoring the backed up data.
+
IMPORTANT: FreeBSD features the  {{< manpage "growfs" "8" >}}
 command, which makes it possible to increase the size of file system on the fly, removing this limitation.
+



File systems are contained in partitions.
This does not have the same meaning as the common usage of the term partition (for example, MS-DOS(TM)
 partition), because of FreeBSD's UNIX(R) heritage.
Each partition is identified by a letter from `a` through to ``h``.
Each partition can contain only one file system, which means that file systems are often described by either their typical mount point in the file system hierarchy, or the letter of the partition they are contained in.

FreeBSD also uses disk space for [term]_swap space_
 to provide [term]_virtual memory_
.
This allows your computer to behave as though it has much more memory than it actually does.
When FreeBSD runs out of memory, it moves some of the data that is not currently being used to the swap space, and moves it back in (moving something else out) when it needs it.

Some partitions have certain conventions associated with them.

[cols="1,1", frame="none", options="header"]
|===
| Partition
| Convention


|``a``
|Normally contains the root file system.

|``b``
|Normally contains swap space.

|``c``
|Normally the same size as the enclosing slice.
	      This allows utilities that need to work on the entire
	      slice, such as a bad block scanner, to work on the
	      `c` partition.  A file system would not
	      normally be created on this partition.

|``d``
|Partition `d` used to have a
	      special meaning associated with it, although that is now
	      gone and `d` may work as any normal
	      partition.
|===


Disks in FreeBSD are divided into slices, referred to in Windows(TM)
 as partitions, which are numbered from 1 to 4.
These are then divided into partitions, which contain file systems, and are labeled using letters.

(((slices)))

(((partitions)))

(((dangerously dedicated)))


Slice numbers follow the device name, prefixed with an ``s``, starting at 1.
So "`da0__s1__`"
 is the first slice on the first SCSI drive.
There can only be four physical slices on a disk, but there can be logical slices inside physical slices of the appropriate type.
These extended slices are numbered starting at 5, so "`ada0__s5__`"
 is the first extended slice on the first SATA disk.
These devices are used by file systems that expect to occupy a slice.

Slices, "`dangerously dedicated`"
 physical drives, and other drives contain [term]_partitions_
, which are represented as letters from `a` to ``h``.
This letter is appended to the device name, so "`da0__a__`"
 is the `a` partition on the first `da` drive, which is "`dangerously dedicated`"
. "`ada1s3__e__`"
 is the fifth partition in the third slice of the second SATA disk drive.

Finally, each disk on the system is identified.
A disk name starts with a code that indicates the type of disk, and then a number, indicating which disk it is.
Unlike slices, disk numbering starts at 0.
Common codes are listed in <<_disks_naming>>.

When referring to a partition, include the disk name, ``s``, the slice number, and then the partition letter.
Examples are shown in <<_basics_disk_slice_part>>.

<<_basics_concept_disk_model>> shows a conceptual model of a disk layout.

When installing FreeBSD, configure the disk slices, create partitions within the slice to be used for FreeBSD, create a file system or swap space in each partition, and decide where each file system will be mounted.

[[_disks_naming]]
.Disk Device Names
[cols="1,1", frame="none", options="header"]
|===
| Drive Type
| Drive Device Name

|[acronym]``SATA`` and [acronym]``IDE``
	      hard drives
|``ada`` or
	      `ad`

|[acronym]``SCSI`` hard drives and
	      [acronym]``USB`` storage devices
|``da``

|[acronym]``SATA`` and [acronym]``IDE``[acronym]``CD-ROM`` drives
|``cd`` or
	      `acd`

|[acronym]``SCSI``[acronym]``CD-ROM``
	      drives
|``cd``

|Floppy drives
|``fd``

|Assorted non-standard [acronym]``CD-ROM``
	      drives
|``mcd`` for Mitsumi
	      [acronym]``CD-ROM`` and `scd` for
	      Sony [acronym]``CD-ROM`` devices

|[acronym]``SCSI`` tape drives
|``sa``

|[acronym]``IDE`` tape drives
|``ast``

|RAID drives
|Examples include `aacd` for
	      Adaptec(TM)
 AdvancedRAID, `mlxd` and
	      `mlyd` for Mylex(TM)
, `amrd` for AMI MegaRAID(TM)
, `idad` for Compaq Smart RAID,
	      `twed` for 3ware(TM)
 RAID.
|===

[[_basics_disk_slice_part]]
.Sample Disk, Slice, and Partition Names
====
[cols="1,1", frame="none", options="header"]
|===
| Name
| Meaning


|``ada0s1a``
|The first partition (``a``) on the
		first slice (``s1``) on the first
		[acronym]``SATA``
		disk (``ada0``).

|``da1s2e``
|The fifth partition (``e``) on the
		second slice (``s2``) on the second
		SCSI disk (``da1``).
|===
====

[[_basics_concept_disk_model]]
.Conceptual Model of a Disk
====
This diagram shows FreeBSD's view of the first [acronym]``SATA`` disk attached to the system.
Assume that the disk is 250{nbsp}GB in size, and contains an 80{nbsp}GB slice and a 170{nbsp}GB slice (MS-DOS(TM)
	partitions).  The first slice contains a Windows(TM)[acronym]``NTFS`` file system, [path]``C:``
, and the second slice contains a FreeBSD installation.
This example FreeBSD installation has four data partitions and a swap partition.

The four partitions each hold a file system.
Partition `a` is used for the root file system, `d` for [path]``/var/``
, `e` for [path]``/tmp/``
, and `f` for [path]``/usr/``
.
Partition letter `c` refers to the entire slice, and so is not used for ordinary partitions.



image::basics/disk-layout[]

====

[[_mount_unmount]]
== Mounting and Unmounting File Systems


The file system is best visualized as a tree, rooted, as it were, at [path]``/``
. [path]``/dev``
, [path]``/usr``
, and the other directories in the root directory are branches, which may have their own branches, such as [path]``/usr/local``
, and so on.

(((root file system)))


There are various reasons to house some of these directories on separate file systems. [path]``/var``
 contains the directories [path]``log/``
, [path]``spool/``
, and various types of temporary files, and as such, may get filled up.
Filling up the root file system is not a good idea, so splitting [path]``/var``
 from [path]``/``
 is often favorable.

Another common reason to contain certain directory trees on other file systems is if they are to be housed on separate physical disks, or are separate virtual disks, such as Network File System mounts, described in <<_network_nfs>>, or CDROM drives.

[[_disks_fstab]]
=== The fstab File

(((file systems,mounted with fstab)))


During the boot process (<<_boot>>), file systems listed in [path]``/etc/fstab``
 are automatically mounted except for the entries containing [option]``noauto``.
This file contains entries in the following format:

[source]
----
device       /mount-point fstype     options      dumpfreq     passno
----

`device`::
An existing device name as explained in <<_disks_naming>>.

`mount-point`::
An existing directory on which to mount the file system.

`fstype`::
The file system type to pass to  {{< manpage "mount" "8" >}}
.
The default FreeBSD file system is ``ufs``.

`options`::
Either [option]``rw`` for read-write file systems, or [option]``ro`` for read-only file systems, followed by any other options that may be needed.
A common option is [option]``noauto`` for file systems not normally mounted during the boot sequence.
Other options are listed in  {{< manpage "mount" "8" >}}
.

`dumpfreq`::
Used by  {{< manpage "dump" "8" >}}
to determine which file systems require dumping.
If the field is missing, a value of zero is assumed.

`passno`::
Determines the order in which file systems should be checked.
File systems that should be skipped should have their `passno` set to zero.
The root file system needs to be checked before everything else and should have its `passno` set to one.
The other file systems should be set to values greater than one.
If more than one file system has the same ``passno``,  {{< manpage "fsck" "8" >}}
will attempt to check file systems in parallel if possible.


Refer to  {{< manpage "fstab" "5" >}}
 for more information on the format of [path]``/etc/fstab``
 and its options.

[[_disks_mount]]
=== Using mount8


File systems are mounted using  {{< manpage "mount" "8" >}}
.
The most basic syntax is as follows:

====
----
# mount device mountpoint
----
====


This command provides many options which are described in  {{< manpage "mount" "8" >}}
, The most commonly used options include:

.Mount Options
[option]``-a``::
Mount all the file systems listed in [path]``/etc/fstab``
, except those marked as "`noauto`"
, excluded by the [option]``-t`` flag, or those that are already mounted.

[option]``-d``::
Do everything except for the actual mount system call.
This option is useful in conjunction with the [option]``-v`` flag to determine what  {{< manpage "mount" "8" >}}
is actually trying to do.

[option]``-f``::
Force the mount of an unclean file system (dangerous), or the revocation of write access when downgrading a file system's mount status from read-write to read-only.

[option]``-r``::
Mount the file system read-only.
This is identical to using [option]``-o ro``.

[option]``-t``[replaceable]``fstype``::
Mount the specified file system type or mount only file systems of the given type, if [option]``-a``	      is included.
"`ufs`"
is the default file system type.

[option]``-u``::
Update mount options on the file system.

[option]``-v``::
Be verbose.

[option]``-w``::
Mount the file system read-write.


The following options can be passed to [option]``-o``	as a comma-separated list:

nosuid::
Do not interpret setuid or setgid flags on the file system.
This is also a useful security option.


[[_disks_umount]]
=== Using umount8

(((file systems,unmounting)))


To unmount a file system use  {{< manpage "umount" "8" >}}
.
This command takes one parameter which can be a mountpoint, device name, [option]``-a`` or [option]``-A``.

All forms take [option]``-f`` to force unmounting, and [option]``-v`` for verbosity.
Be warned that [option]``-f`` is not generally a good idea as it might crash the computer or damage data on the file system.

To unmount all mounted file systems, or just the file system types listed after [option]``-t``, use [option]``-a`` or [option]``-A``.
Note that [option]``-A`` does not attempt to unmount the root file system.

[[_basics_processes]]
== Processes and Daemons


FreeBSD is a multi-tasking operating system.
Each program running at any one time is called a [term]_process_
.
Every running command starts at least one new process and there are a number of system processes that are run by FreeBSD.

Each process is uniquely identified by a number called a [term]_process ID_
 ([acronym]``PID``). Similar to files, each process has one owner and group, and the owner and group permissions are used to determine which files and devices the process can open.
Most processes also have a parent process that started them.
For example, the shell is a process, and any command started in the shell is a process which has the shell as its parent process.
The exception is a special process called  {{< manpage "init" "8" >}}
 which is always the first process to start at boot time and which always has a [acronym]``PID`` of ``1``.

Some programs are not designed to be run with continuous user input and disconnect from the terminal at the first opportunity.
For example, a web server responds to web requests, rather than user input.
Mail servers are another example of this type of application.
These types of programs are known as [term]_daemons_
.
The term daemon comes from Greek mythology and represents an entity that is neither good nor evil, and which invisibly performs useful tasks.
This is why the BSD mascot is the cheerful-looking daemon with sneakers and a pitchfork.

There is a convention to name programs that normally run as daemons with a trailing "`d`"
.
For example, [app]``BIND`` is the Berkeley Internet Name Domain, but the actual program that executes is [command]``named``.
The [app]``Apache`` web server program is [command]``httpd`` and the line printer spooling daemon is [command]``lpd``.
This is only a naming convention.
For example, the main mail daemon for the [app]``Sendmail`` application is [command]``sendmail``, and not ``maild``.

=== Viewing Processes


To see the processes running on the system, use  {{< manpage "ps" "1" >}}
	or  {{< manpage "top" "1" >}}
.
To display a static list of the currently running processes, their [acronym]``PID``s, how much memory they are using, and the command they were started with, use  {{< manpage "ps" "1" >}}
.
To display all the running processes and update the display every few seconds in order to interactively see what the computer is doing, use  {{< manpage "top" "1" >}}
.

By default,  {{< manpage "ps" "1" >}}
 only shows the commands that are running and owned by the user.
For example:

----
% psPID TT  STAT    TIME COMMAND
8203  0  Ss   0:00.59 /bin/csh
8895  0  R+   0:00.00 ps
----


The output from  {{< manpage "ps" "1" >}}
 is organized into a number of columns.
The `PID` column displays the process ID.
 [acronym]``PID``s are assigned starting at 1, go up to 99999, then wrap around back to the beginning.
However, a [acronym]``PID`` is not reassigned if it is already in use.
The `TT` column shows the tty the program is running on and `STAT`	shows the program's state.
 `TIME` is the amount of time the program has been running on the CPU.
This is usually not the elapsed time since the program was started, as most programs spend a lot of time waiting for things to happen before they need to spend time on the CPU.
Finally, `COMMAND` is the command that was used to start the program.

A number of different options are available to change the information that is displayed.
One of the most useful sets is ``auxww``, where  [option]``a`` displays information about all the running processes of all users, [option]``u`` displays the username and memory usage of the process' owner, [option]``x`` displays information about daemon processes, and [option]``ww``	causes  {{< manpage "ps" "1" >}}
 to display the full command line for each process, rather than truncating it once it gets too long to fit on the screen.

The output from  {{< manpage "top" "1" >}}
 is similar:

----
% toplast pid:  9609;  load averages:  0.56,  0.45,  0.36              up 0+00:20:03  10:21:46
107 processes: 2 running, 104 sleeping, 1 zombie
CPU:  6.2% user,  0.1% nice,  8.2% system,  0.4% interrupt, 85.1% idle
Mem: 541M Active, 450M Inact, 1333M Wired, 4064K Cache, 1498M Free
ARC: 992M Total, 377M MFU, 589M MRU, 250K Anon, 5280K Header, 21M Other
Swap: 2048M Total, 2048M Free

  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME   WCPU COMMAND
  557 root          1 -21  r31   136M 42296K select  0   2:20  9.96% Xorg
 8198 dru           2  52    0   449M 82736K select  3   0:08  5.96% kdeinit4
 8311 dru          27  30    0  1150M   187M uwait   1   1:37  0.98% firefox
  431 root          1  20    0 14268K  1728K select  0   0:06  0.98% moused
 9551 dru           1  21    0 16600K  2660K CPU3    3   0:01  0.98% top
 2357 dru           4  37    0   718M   141M select  0   0:21  0.00% kdeinit4
 8705 dru           4  35    0   480M    98M select  2   0:20  0.00% kdeinit4
 8076 dru           6  20    0   552M   113M uwait   0   0:12  0.00% soffice.bin
 2623 root          1  30   10 12088K  1636K select  3   0:09  0.00% powerd
 2338 dru           1  20    0   440M 84532K select  1   0:06  0.00% kwin
 1427 dru           5  22    0   605M 86412K select  1   0:05  0.00% kdeinit4
----


The output is split into two sections.
The header (the first five or six lines) shows the [acronym]``PID`` of the last process to run, the system load averages (which are a measure of how busy the system is), the system uptime (time since the last reboot) and the current time.
The other figures in the header relate to how many processes are running, how much memory and swap space has been used, and how much time the system is spending in different CPU states.
If the [acronym]``ZFS`` file system module has been loaded, an `ARC` line indicates how much data was read from the memory cache instead of from disk.

Below the header is a series of columns containing similar information to the output from  {{< manpage "ps" "1" >}}
, such as the [acronym]``PID``, username, amount of CPU time, and the command that started the process.
By default,  {{< manpage "top" "1" >}}
	also displays the amount of memory space taken by the process.
This is split into two columns: one for total size and one for resident size.
Total size is how much memory the application has needed and the resident size is how much it is actually using now.

 {{< manpage "top" "1" >}}
 automatically updates the display every two seconds.
A different interval can be specified with [option]``-s``.

[[_basics_daemons]]
=== Killing Processes


One way to communicate with any running process or daemon is to send a [term]_signal_
 using  {{< manpage "kill" "1" >}}
.
There are a number of different signals; some have a specific meaning while others are described in the application's documentation.
A user can only send a signal to a process they own and sending a signal to someone else's process will result in a permission denied error.
The exception is the [username]``root``
 user, who can send signals to anyone's processes.

The operating system can also send a signal to a process.
If an application is badly written and tries to access memory that it is not supposed to, FreeBSD will send the process the "`Segmentation Violation`"
 signal (``SIGSEGV``).  If an application has been written to use the  {{< manpage "alarm" "3" >}}
 system call to be alerted after a period of time has elapsed, it will be sent the "`Alarm`"
 signal (``SIGALRM``).

Two signals can be used to stop a process: `SIGTERM` and ``SIGKILL``. `SIGTERM` is the polite way to kill a process as the process can read the signal, close any log files it may have open, and attempt to finish what it is doing before shutting down.
In some cases, a process may ignore `SIGTERM` if it is in the middle of some task that cannot be interrupted.

`SIGKILL` cannot be ignored by a process.
Sending a `SIGKILL` to a process will usually stop that process there and then. footnote:[There are a few tasks that cannot be
	    interrupted.  For example, if the process is trying to
	    read from a file that is on another computer on the
	    network, and the other computer is unavailable, the
	    process is said to be uninterruptible.
	    Eventually the process will time out, typically after two
	    minutes.  As soon as this time out occurs the process will
	    be killed.]
.

Other commonly used signals are ``SIGHUP``, ``SIGUSR1``, and ``SIGUSR2``.
Since these are general purpose signals, different applications will respond differently.

For example, after changing a web server's configuration file, the web server needs to be told to re-read its configuration.
Restarting [command]``httpd`` would result in a brief outage period on the web server.
Instead, send the daemon the `SIGHUP` signal.
Be aware that different daemons will have different behavior, so refer to the documentation for the daemon to determine if `SIGHUP` will achieve the desired results.

.Procedure: Sending a Signal to a Process

This example shows how to send a signal to  {{< manpage "inetd" "8" >}}
.
The  {{< manpage "inetd" "8" >}}
 configuration file is [path]``/etc/inetd.conf``
, and  {{< manpage "inetd" "8" >}}
 will re-read this configuration file when it is sent a ``SIGHUP``.
. Find the [acronym]``PID`` of the process to send the signal to using  {{< manpage "pgrep" "1" >}} . In this example, the [acronym]``PID`` for  {{< manpage "inetd" "8" >}} is 198:
+

----
% pgrep -l inetd198  inetd -wW
----
. Use  {{< manpage "kill" "1" >}} to send the signal. Because  {{< manpage "inetd" "8" >}} is owned by [username]``root`` , use  {{< manpage "su" "1" >}} to become [username]``root`` first.
+

----
% su
Password: 
# /bin/kill -s HUP 198
----
+
Like most UNIX(R) commands,  {{< manpage "kill" "1" >}}
will not print any output if it is successful.
If a signal is sent to a process not owned by that user, the message `kill: [replaceable]``PID``: Operation
not permitted` will be displayed.
Mistyping the [acronym]``PID`` will either send the signal to the wrong process, which could have negative results, or will send the signal to a [acronym]``PID`` that is not currently in use, resulting in the error ``kill: [replaceable]``PID``: No such
process``.
+
.Why Use [command]``/bin/kill``?
NOTE: Many shells provide [command]``kill`` as a built in command, meaning that the shell will send the signal directly, rather than running [path]``/bin/kill``
.
Be aware that different shells have a different syntax for specifying the name of the signal to send.
Rather than try to learn all of them, it can be simpler to specify [command]``/bin/kill``.
+



When sending other signals, substitute `TERM` or `KILL` with the name of the signal.

[IMPORTANT]
====
Killing a random process on the system is a bad idea.
In particular,  {{< manpage "init" "8" >}}
, [acronym]``PID`` 1, is special.
Running [command]``/bin/kill -s KILL 1`` is a quick, and unrecommended, way to shutdown the system. _Always_ double check the arguments to  {{< manpage "kill" "1" >}}__before__ pressing kbd:[Return]
.
====

== Shells

(((command line)))


A [term]_shell_
 provides a command line interface for interacting with the operating system.
A shell receives commands from the input channel and executes them.
Many shells provide built in functions to help with everyday tasks such as file management, file globbing, command line editing, command macros, and environment variables.
FreeBSD comes with several shells, including the Bourne shell ( {{< manpage "sh" "1" >}}
) and the extended C shell ( {{< manpage "tcsh" "1" >}}
).  Other shells are available from the FreeBSD Ports Collection, such as [command]``zsh`` and [command]``bash``.

The shell that is used is really a matter of taste.
A C programmer might feel more comfortable with a C-like shell such as  {{< manpage "tcsh" "1" >}}
.
A Linux(TM)
 user might prefer [command]``bash``.
Each shell has unique properties that may or may not work with a user's preferred working environment, which is why there is a choice of which shell to use.

One common shell feature is filename completion.
After a user types the first few letters of a command or filename and presses kbd:[Tab]
, the shell completes the rest of the command or filename.
Consider two files called [path]``foobar``
 and [path]``football``
.
To delete [path]``foobar``
, the user might type [command]``rm foo`` and press kbd:[Tab]
 to complete the filename.

But the shell only shows [command]``rm foo``.
It was unable to complete the filename because both [path]``foobar``
 and [path]``football``
 start with ``foo``.
Some shells sound a beep or show all the choices if more than one name matches.
The user must then type more characters to identify the desired filename.
Typing a `t` and pressing kbd:[Tab]
 again is enough to let the shell determine which filename is desired and fill in the rest.

(((environment variables)))


Another feature of the shell is the use of environment variables.
Environment variables are a variable/key pair stored in the shell's environment.
This environment can be read by any program invoked by the shell, and thus contains a lot of program configuration. <<_shell_env_vars>> provides a list of common environment variables and their meanings.
Note that the names of environment variables are always in uppercase.
[[_shell_env_vars]]
.Common Environment Variables
[cols="1,1", frame="none", options="header"]
|===
| Variable
| Description

|[var]``USER``
|Current logged in user's name.

|[var]``PATH``
|Colon-separated list of directories to search for
	      binaries.

|[var]``DISPLAY``
|Network name of the
	      [app]``Xorg``
	      display to connect to, if available.

|[var]``SHELL``
|The current shell.

|[var]``TERM``
|The name of the user's type of terminal.  Used to
	      determine the capabilities of the terminal.

|[var]``TERMCAP``
|Database entry of the terminal escape codes to
	      perform various terminal functions.

|[var]``OSTYPE``
|Type of operating system.

|[var]``MACHTYPE``
|The system's CPU architecture.

|[var]``EDITOR``
|The user's preferred text editor.

|[var]``PAGER``
|The user's preferred utility for viewing text one
	      page at a time.

|[var]``MANPATH``
|Colon-separated list of directories to search for
	      manual pages.
|===

(((Bourne shells)))


How to set an environment variable differs between shells.
In  {{< manpage "tcsh" "1" >}}
 and  {{< manpage "csh" "1" >}}
, use [command]``setenv`` to set environment variables.
In  {{< manpage "sh" "1" >}}
 and [command]``bash``, use [command]``export`` to set the current environment variables.
This example sets the default [var]``EDITOR`` to [path]``/usr/local/bin/emacs``
 for the  {{< manpage "tcsh" "1" >}}
 shell:

----
% setenv EDITOR /usr/local/bin/emacs
----


The equivalent command for [command]``bash`` would be:

----
% export EDITOR="/usr/local/bin/emacs"
----


To expand an environment variable in order to see its current setting, type a `$` character in front of its name on the command line.
For example, [command]``echo $TERM`` displays the current [var]``$TERM`` setting.

Shells treat special characters, known as meta-characters, as special representations of data.
The most common meta-character is ``\*``, which represents any number of characters in a filename.
Meta-characters can be used to perform filename globbing.
For example, [command]``echo
	*`` is equivalent to [command]``ls`` because the shell takes all the files that match `\*` and [command]``echo`` lists them on the command line.

To prevent the shell from interpreting a special character, escape it from the shell by starting it with a backslash (``\``).  For example, [command]``echo
	$TERM`` prints the terminal setting whereas [command]``echo \$TERM`` literally prints the string ``$TERM``.

[[_changing_shells]]
=== Changing the Shell


The easiest way to permanently change the default shell is to use [command]``chsh``.
Running this command will open the editor that is configured in the [var]``EDITOR`` environment variable, which by default is set to  {{< manpage "vi" "1" >}}
.
Change the `Shell:`	line to the full path of the new shell.

Alternately, use [command]``chsh -s`` which will set the specified shell without opening an editor.
For example, to change the shell to [command]``bash``:

----
% chsh -s /usr/local/bin/bash
----

[NOTE]
====
The new shell _must_ be present in [path]``/etc/shells``
.
If the shell was installed from the FreeBSD Ports Collection as described in <<_ports>>, it should be automatically added to this file.
If it is missing, add it using this command, replacing the path with the path of the shell:

----
# echo /usr/local/bin/bash >> /etc/shells
----

Then, rerun  {{< manpage "chsh" "1" >}}
.
====

=== Advanced Shell Techniques
= Advanced Shell Techniques
:imagesdir: ./images
Tom Rhodes


The UNIX(R) shell is not just a command interpreter, it acts as a powerful tool which allows users to execute commands, redirect their output, redirect their input and chain commands together to improve the final command output.
When this functionality is mixed with built in commands, the user is provided with an environment that can maximize efficiency.

Shell redirection is the action of sending the output or the input of a command into another command or into a file.
To capture the output of the  {{< manpage "ls" "1" >}}
 command, for example, into a file, redirect the output:

----
% ls > directory_listing.txt
----


The directory contents will now be listed in [path]``directory_listing.txt``
.
Some commands can be used to read input, such as  {{< manpage "sort" "1" >}}
.
To sort this listing, redirect the input:

----
% sort < directory_listing.txt
----


The input will be sorted and placed on the screen.
To redirect that input into another file, one could redirect the output of  {{< manpage "sort" "1" >}}
 by mixing the direction:

----
% sort < directory_listing.txt > sorted.txt
----


In all of the previous examples, the commands are performing redirection using file descriptors.
Every UNIX(R) system has file descriptors, which include standard input (stdin), standard output (stdout), and standard error (stderr).  Each one has a purpose, where input could be a keyboard or a mouse, something that provides input.
Output could be a screen or paper in a printer.
And error would be anything that is used for diagnostic or error messages.
All three are considered [acronym]``I/O`` based file descriptors and sometimes considered streams.

Through the use of these descriptors, the shell allows output and input to be passed around through various commands and redirected to or from a file.
Another method of redirection is the pipe operator.

The UNIX(R) pipe operator, "`|`"
 allows the output of one command to be directly passed or directed to another program.
Basically, a pipe allows the standard output of a command to be passed as standard input to another command, for example:

----
% cat directory_listing.txt | sort | less
----


In that example, the contents of [path]``directory_listing.txt``
 will be sorted and the output passed to  {{< manpage "less" "1" >}}
.
This allows the user to scroll through the output at their own pace and prevent it from scrolling off the screen.

[[_editors]]
== Text Editors

(((text editors)))

(((editors)))


Most FreeBSD configuration is done by editing text files.
Because of this, it is a good idea to become familiar with a text editor.
FreeBSD comes with a few as part of the base system, and many more are available in the Ports Collection.

(((ee)))

(((editors,ee1)))


A simple editor to learn is  {{< manpage "ee" "1" >}}
, which stands for easy editor.
To start this editor, type [command]``ee
	[replaceable]``filename```` where [replaceable]``filename`` is the name of the file to be edited.
Once inside the editor, all of the commands for manipulating the editor's functions are listed at the top of the display.
The caret (``^``) represents kbd:[Ctrl]
, so `^e` expands to kbd:[Ctrl+e]
.
To leave  {{< manpage "ee" "1" >}}
, press kbd:[Esc]
, then choose the "`leave editor`"
 option from the main menu.
The editor will prompt to save any changes if the file has been modified.

(((editors)))

(((emacs)))


FreeBSD also comes with more powerful text editors, such as  {{< manpage "vi" "1" >}}
, as part of the base system.
Other editors, like [package]#editors/emacs#
 and [package]#editors/vim#
, are part of the FreeBSD Ports Collection.
These editors offer more functionality at the expense of being more complicated to learn.
Learning a more powerful editor such as [app]``vim`` or [app]``Emacs`` can save more time in the long run.

Many applications which modify files or require typed input will automatically open a text editor.
To change the default editor, set the [var]``EDITOR`` environment variable as described in <<_shells>>.

[[_basics_devices]]
== Devices and Device Nodes


A device is a term used mostly for hardware-related activities in a system, including disks, printers, graphics cards, and keyboards.
When FreeBSD boots, the majority of the boot messages refer to devices being detected.
A copy of the boot messages are saved to [path]``/var/run/dmesg.boot``
.

Each device has a device name and number.
For example, [path]``ada0``
 is the first SATA hard drive, while [path]``kbd0``
 represents the keyboard.

Most devices in FreeBSD must be accessed through special files called device nodes, which are located in [path]``/dev``
.

[[_basics_more_information]]
== Manual Pages

(((manual pages)))


The most comprehensive documentation on FreeBSD is in the form of manual pages.
Nearly every program on the system comes with a short reference manual explaining the basic operation and available arguments.
These manuals can be viewed using [command]``man``:

----
% man command
----


where [replaceable]``command`` is the name of the command to learn about.
For example, to learn more about  {{< manpage "ls" "1" >}}
, type:

----
% man ls
----


Manual pages are divided into sections which represent the type of topic.
In FreeBSD, the following sections are available:

. User commands.
. System calls and error numbers.
. Functions in the C libraries.
. Device drivers.
. File formats.
. Games and other diversions.
. Miscellaneous information.
. System maintenance and operation commands.
. System kernel interfaces.


In some cases, the same topic may appear in more than one section of the online manual.
For example, there is a [command]``chmod`` user command and a `chmod()` system call.
To tell  {{< manpage "man" "1" >}}
 which section to display, specify the section number:

----
% man 1 chmod
----


This will display the manual page for the user command  {{< manpage "chmod" "1" >}}
.
References to a particular section of the online manual are traditionally placed in parenthesis in written documentation, so  {{< manpage "chmod" "1" >}}
 refers to the user command and  {{< manpage "chmod" "2" >}}
 refers to the system call.

If the name of the manual page is unknown, use [command]``man
	-k`` to search for keywords in the manual page descriptions:

----
% man -k mail
----


This command displays a list of commands that have the keyword "`mail`"
 in their descriptions.
This is equivalent to using  {{< manpage "apropos" "1" >}}
.

To read the descriptions for all of the commands in [path]``/usr/bin``
, type:

----
% cd /usr/bin
% man -f * | more
----


or

----
% cd /usr/bin
% whatis * |more
----

[[_basics_info]]
=== GNU Info Files

(((Free Software Foundation)))


FreeBSD includes several applications and utilities produced by the Free Software Foundation (FSF).  In addition to manual pages, these programs may include hypertext documents called `info` files.
These can be viewed using  {{< manpage "info" "1" >}}
 or, if [package]#editors/emacs#
 is installed, the info mode of [app]``emacs``.

To use  {{< manpage "info" "1" >}}
, type:

----
% info
----


For a brief introduction, type ``h``.
For a quick command reference, type ``?``.

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]